// 文法詳解(微語意/易混淆文法的深入說明)。獨立於 content-data.json,不會被內容重匯出覆蓋。
// key=文法 id;value=HTML(渲染時過 furiganaHTMLRich→自動 furigana+即點即查)。要新增照格式加一筆即可。
window.GRAMMAR_DETAIL = {
  "n5-51": "<div class='gd-sec'><b>核心觀念</b>：三個都在講「給／收東西」,差別在<b>站在誰的立場</b>和<b>方向</b>。同一件事,選哪個動詞取決於你把視角放在誰身上。</div><div class='gd-sec'><span class='gd-tag'>あげます</span><b>給出去（視角在給的人）</b><br>主語＝給的人。方向：我方→別人,或第三者 A→B。<br>例：<span class='gd-jp'>私は友だちにプレゼントをあげます。</span>（我送朋友禮物）<br>⚠ <b>不能</b>用在「別人給我」。</div><div class='gd-sec'><span class='gd-tag'>もらいます</span><b>得到（視角在收的人）</b><br>主語＝收的人。方向：別人→我方。來源用「に／から」。<br>例：<span class='gd-jp'>私は友だちにプレゼントをもらいます。</span>（我收到朋友給的禮物）</div><div class='gd-sec'><span class='gd-tag'>くれます</span><b>別人給我方（視角在收的人）</b><br>主語＝給的人,但方向<b>一定朝向我／自己人</b>。<br>例：<span class='gd-jp'>友だちが私にプレゼントをくれます。</span>（朋友給我禮物）</div><div class='gd-sec'><b>あげる vs くれる（都是「給」,差在方向）</b><br>・給別人 →「あげる」（私は彼にあげる）<br>・別人給我 →「くれる」（彼が私にくれる）</div><div class='gd-warn'><b>最常見的錯誤</b><br>✗ <span class='gd-jp'>母は私におこづかいをあげます。</span><br>✓ <span class='gd-jp'>母は私におこづかいをくれます。</span><br>→ 給「我」的一律用 <b>くれる</b>,不能用 あげる。</div><div class='gd-sec'><b>內外（ウチ・ソト）</b>：家人、自己公司的人算「我方」,所以「弟が私に本をくれた」也用くれる。<br><b>敬語</b>：あげる→さしあげる（給上位）／やる（給下位、動植物）；もらう→いただく；くれる→くださる。</div>",
  "n4-30": "<div class='gd-sec'><b>核心觀念</b>：把「授受動詞」接在て形後面,講的就不是「給東西」,而是<b>給／收一個「行為（幫忙做某事）」</b>。方向邏輯和物品授受一樣。</div><div class='gd-sec'><span class='gd-tag'>～てあげる</span><b>我（方）為別人做（施惠）</b><br>例：<span class='gd-jp'>私は友だちに本を貸してあげた。</span>（我借書給朋友）<br>⚠ 對長輩、不熟的人用容易有「我特地幫你」的<b>施恩感</b>,失禮,要小心。對上位用「～てさしあげる」也仍偏失禮,多改用別的說法。</div><div class='gd-sec'><span class='gd-tag'>～てもらう</span><b>請／讓別人為我做（我受惠,主語＝我）</b><br>例：<span class='gd-jp'>私は友だちに宿題を手伝ってもらった。</span>（我請朋友幫我做作業）<br>對上位：<span class='gd-jp'>先生に説明していただいた。</span></div><div class='gd-sec'><span class='gd-tag'>～てくれる</span><b>別人為我（方）做（我受惠,主語＝對方,帶感謝語氣）</b><br>例：<span class='gd-jp'>友だちが宿題を手伝ってくれた。</span>（朋友幫我做了作業）<br>對上位：<span class='gd-jp'>先生が教えてくださった。</span></div><div class='gd-warn'><b>てもらう vs てくれる（同一件事,只是視角不同）</b><br>・<span class='gd-jp'>（私は）友だちに手伝ってもらった。</span> 主語＝<b>我</b>（受益者）<br>・<span class='gd-jp'>友だちが（私を）手伝ってくれた。</span> 主語＝<b>對方</b>（施予者）<br>兩句都對、意思一樣,看你想把句子的主角放在誰身上。</div>",
  "n4-17": "<div class='gd-sec'><b>接續</b>：辞書形／名詞＋の ＋ ために<br><b>意思</b>：為了～（<b>意志性的目的</b>）。前面是「你想達成的目標」,後面是「為此採取的行動」。</div><div class='gd-sec'>例：<span class='gd-jp'>日本語を勉強するために、日本へ行きます。</span>（為了學日文去日本）<br><span class='gd-jp'>家族のために、頑張って働いています。</span>（為了家人努力工作）</div><div class='gd-sec'><b>ために（目的） vs ように（目的）— 最容易混</b><br>・<b>ために</b>：接<b>意志動詞</b>（自己能直接控制的動作）,前後常同一主語。<br>　<span class='gd-jp'>試験に合格するために、勉強する。</span><br>・<b>ように</b>：接<b>非意志動詞／可能形／否定</b>（結果、能力、狀態,不能直接控制）。<br>　<span class='gd-jp'>試験に合格できるように、勉強する。</span><br>→ 「合格する」是意志→ために；「合格できる（能力）」是非意志→ように。</div><div class='gd-sec'><b>vs から／ので</b>：ために是「為了達成目的」,不是「原因」。「因為～所以～」要用から／ので。</div>",
  "n4-18": "<div class='gd-sec'><b>接續</b>：た形／名詞＋の ＋ ために<br><b>意思</b>：因為～（<b>原因、理由</b>）。語氣較<b>書面、客觀</b>,後面常是<b>負面或非預期的結果</b>。</div><div class='gd-sec'>例：<span class='gd-jp'>大雪のために、新幹線が止まりました。</span>（因為大雪,新幹線停駛）<br><span class='gd-jp'>事故があったために、道が込んでいる。</span>（因為出了事故,路很塞）</div><div class='gd-warn'><b>同樣是「ために」,目的還是原因怎麼分？看接續！</b><br>・<b>辞書形</b>＋ために → <b>目的</b>（為了）：<span class='gd-jp'>合格するために勉強する。</span><br>・<b>た形／狀態</b>＋ために → <b>原因</b>（因為）：<span class='gd-jp'>雪が降ったために遅れた。</span><br>簡單記：後面是「我要去做的行動」＝目的；後面是「已經發生的結果」＝原因。</div><div class='gd-sec'><b>vs から／ので</b>：ために（原因）較<b>正式、書面、偏負面結果</b>；日常口語講原因多用から／ので。</div>",
  "n4-19": "<div class='gd-sec'><b>接續</b>：辞書形／ない形 ＋ ように<br><b>意思</b>：為了能夠～／為了不～。用在<b>自己不能直接控制</b>的結果（能力、狀態、避免某事）。</div><div class='gd-sec'>例：<span class='gd-jp'>日本語が話せるように、毎日練習しています。</span>（為了能說日文,每天練習）<br><span class='gd-jp'>忘れないように、メモしておきます。</span>（為了不忘記,先記下來）</div><div class='gd-warn'><b>ように vs ために（一定要分清）</b><br>・<b>ように</b>＋<b>非意志</b>：可能形（話せる）、否定（忘れない）、自然動詞（治る）。<br>・<b>ために</b>＋<b>意志</b>：自己能直接做的動作（話す、勉強する）。<br>對照：<span class='gd-jp'>痩せるために運動する</span>（意志·為了瘦）／<span class='gd-jp'>痩せられるように運動する</span>（能力·為了能瘦）。</div><div class='gd-sec'>ように 前後主語<b>可以不同</b>（例：子供が食べられるように、小さく切る）；ために 前後多為同一人。</div>",
  "n4-20": "<div class='gd-sec'><b>兩個長很像,但一個講「自然變化」,一個講「刻意努力」。</b></div><div class='gd-sec'><span class='gd-tag'>～ようになる</span><b>變得會／能～（自然、非刻意的變化結果）</b><br>接：辞書形／可能形／ない形。<br>例：<span class='gd-jp'>練習して、日本語が話せるようになりました。</span>（練習後變得會說日文了）<br><span class='gd-jp'>最近、朝早く起きられるようになった。</span></div><div class='gd-sec'><span class='gd-tag'>～ようにする</span><b>盡量做到～／養成習慣（有意識地努力）</b><br>接：辞書形／ない形。<br>例：<span class='gd-jp'>毎日野菜を食べるようにしています。</span>（盡量每天吃菜）<br><span class='gd-jp'>夜遅くコーヒーを飲まないようにしている。</span></div><div class='gd-warn'><b>一句話分辨</b><br>・<b>なる</b>＝結果、自然而然「變成這樣」（沒有刻意）。<br>・<b>する</b>＝過程、自己刻意「努力這樣做」。<br>對照：<span class='gd-jp'>食べられるようになった</span>（變得敢吃了·結果）／<span class='gd-jp'>食べるようにしている</span>（盡量去吃·努力）。</div>"
};
