// vocab-n5-en.js — N5 單字英文(pilot,未上線;lang=en 時 by-index merge 到 VOCAB_N5)。Sonnet 翻+Haiku 校。w/r 日文不動。
const VOCAB_N5_EN = [
  {"w": "私", "m": "I", "c": "n."},
  {"w": "僕", "m": "I (male)", "c": "n."},
  {"w": "あなた", "m": "you", "c": "n."},
  {"w": "彼", "m": "he", "c": "n."},
  {"w": "彼女", "m": "she", "c": "n."},
  {"w": "皆さん", "m": "everyone", "c": "n."},
  {"w": "人", "m": "person", "c": "n."},
  {"w": "方", "m": "person (polite)", "c": "n."},
  {"w": "子供", "m": "child", "c": "n."},
  {"w": "男", "m": "man", "c": "n."},
  {"w": "女", "m": "woman", "c": "n."},
  {"w": "男の子", "m": "boy", "c": "n."},
  {"w": "女の子", "m": "girl", "c": "n."},
  {"w": "大人", "m": "adult", "c": "n."},
  {"w": "友達", "m": "friend", "c": "n."},
  {"w": "名前", "m": "name", "c": "n."},
  {"w": "家族", "m": "family", "c": "n."},
  {"w": "お父さん", "m": "father", "c": "n."},
  {"w": "お母さん", "m": "mother", "c": "n."},
  {"w": "お兄さん", "m": "older brother", "c": "n."},
  {"w": "お姉さん", "m": "older sister", "c": "n."},
  {"w": "弟", "m": "younger brother", "c": "n."},
  {"w": "妹", "m": "younger sister", "c": "n."},
  {"w": "兄弟", "m": "siblings", "c": "n."},
  {"w": "奥さん", "m": "wife", "c": "n."},
  {"w": "主人", "m": "husband", "c": "n."},
  {"w": "両親", "m": "parents", "c": "n."},
  {"w": "息子", "m": "son", "c": "n."},
  {"w": "娘", "m": "daughter", "c": "n."},
  {"w": "お祖父さん", "m": "grandfather", "c": "n."},
  {"w": "お祖母さん", "m": "grandmother", "c": "n."},
  {"w": "おじさん", "m": "uncle", "c": "n."},
  {"w": "おばさん", "m": "aunt", "c": "n."},
  {"w": "先生", "m": "teacher", "c": "n."},
  {"w": "学生", "m": "student", "c": "n."},
  {"w": "留学生", "m": "international student", "c": "n."},
  {"w": "会社員", "m": "company employee", "c": "n."},
  {"w": "銀行員", "m": "bank employee", "c": "n."},
  {"w": "医者", "m": "doctor", "c": "n."},
  {"w": "警官", "m": "police officer", "c": "n."},
  {"w": "店員", "m": "store clerk", "c": "n."},
  {"w": "時間", "m": "time", "c": "n."},
  {"w": "今", "m": "now", "c": "n."},
  {"w": "今日", "m": "today", "c": "n."},
  {"w": "明日", "m": "tomorrow", "c": "n."},
  {"w": "昨日", "m": "yesterday", "c": "n."},
  {"w": "今朝", "m": "this morning", "c": "n."},
  {"w": "今晩", "m": "tonight", "c": "n."},
  {"w": "朝", "m": "morning", "c": "n."},
  {"w": "昼", "m": "noon", "c": "n."},
  {"w": "夜", "m": "night", "c": "n."},
  {"w": "夕方", "m": "evening", "c": "n."},
  {"w": "晩", "m": "evening/night", "c": "n."},
  {"w": "午前", "m": "morning (a.m.)", "c": "n."},
  {"w": "午後", "m": "afternoon (p.m.)", "c": "n."},
  {"w": "毎日", "m": "every day", "c": "n."},
  {"w": "毎朝", "m": "every morning", "c": "n."},
  {"w": "毎晩", "m": "every night", "c": "n."},
  {"w": "毎週", "m": "every week", "c": "n."},
  {"w": "毎月", "m": "every month", "c": "n."},
  {"w": "毎年", "m": "every year", "c": "n."},
  {"w": "先週", "m": "last week", "c": "n."},
  {"w": "今週", "m": "this week", "c": "n."},
  {"w": "来週", "m": "next week", "c": "n."},
  {"w": "先月", "m": "last month", "c": "n."},
  {"w": "今月", "m": "this month", "c": "n."},
  {"w": "来月", "m": "next month", "c": "n."},
  {"w": "去年", "m": "last year", "c": "n."},
  {"w": "今年", "m": "this year", "c": "n."},
  {"w": "来年", "m": "next year", "c": "n."},
  {"w": "再来年", "m": "year after next", "c": "n."},
  {"w": "一昨日", "m": "the day before yesterday", "c": "n."},
  {"w": "明後日", "m": "the day after tomorrow", "c": "n."},
  {"w": "誕生日", "m": "birthday", "c": "n."},
  {"w": "休み", "m": "rest; holiday", "c": "n."},
  {"w": "月曜日", "m": "Monday", "c": "n."},
  {"w": "火曜日", "m": "Tuesday", "c": "n."},
  {"w": "水曜日", "m": "Wednesday", "c": "n."},
  {"w": "木曜日", "m": "Thursday", "c": "n."},
  {"w": "金曜日", "m": "Friday", "c": "n."},
  {"w": "土曜日", "m": "Saturday", "c": "n."},
  {"w": "日曜日", "m": "Sunday", "c": "n."},
  {"w": "一月", "m": "January", "c": "n."},
  {"w": "二月", "m": "February", "c": "n."},
  {"w": "三月", "m": "March", "c": "n."},
  {"w": "四月", "m": "April", "c": "n."},
  {"w": "五月", "m": "May", "c": "n."},
  {"w": "六月", "m": "June", "c": "n."},
  {"w": "七月", "m": "July", "c": "n."},
  {"w": "八月", "m": "August", "c": "n."},
  {"w": "九月", "m": "September", "c": "n."},
  {"w": "十月", "m": "October", "c": "n."},
  {"w": "十一月", "m": "November", "c": "n."},
  {"w": "十二月", "m": "December", "c": "n."},
  {"w": "所", "m": "place", "c": "n."},
  {"w": "家", "m": "house", "c": "n."},
  {"w": "うち", "m": "home (one's own)", "c": "n."},
  {"w": "部屋", "m": "room", "c": "n."},
  {"w": "台所", "m": "kitchen", "c": "n."},
  {"w": "玄関", "m": "entryway", "c": "n."},
  {"w": "庭", "m": "garden", "c": "n."},
  {"w": "お手洗い", "m": "restroom", "c": "n."},
  {"w": "お風呂", "m": "bath", "c": "n."},
  {"w": "学校", "m": "school", "c": "n."},
  {"w": "大学", "m": "university", "c": "n."},
  {"w": "教室", "m": "classroom", "c": "n."},
  {"w": "図書館", "m": "library", "c": "n."},
  {"w": "食堂", "m": "cafeteria", "c": "n."},
  {"w": "病院", "m": "hospital", "c": "n."},
  {"w": "銀行", "m": "bank", "c": "n."},
  {"w": "郵便局", "m": "post office", "c": "n."},
  {"w": "会社", "m": "company", "c": "n."},
  {"w": "店", "m": "store", "c": "n."},
  {"w": "喫茶店", "m": "café", "c": "n."},
  {"w": "レストラン", "m": "restaurant", "c": "n."},
  {"w": "デパート", "m": "department store", "c": "n."},
  {"w": "スーパー", "m": "supermarket", "c": "n."},
  {"w": "ホテル", "m": "hotel", "c": "n."},
  {"w": "映画館", "m": "movie theater", "c": "n."},
  {"w": "公園", "m": "park", "c": "n."},
  {"w": "駅", "m": "station", "c": "n."},
  {"w": "空港", "m": "airport", "c": "n."},
  {"w": "町", "m": "town", "c": "n."},
  {"w": "国", "m": "country", "c": "n."},
  {"w": "外国", "m": "foreign country", "c": "n."},
  {"w": "入口", "m": "entrance", "c": "n."},
  {"w": "出口", "m": "exit", "c": "n."},
  {"w": "門", "m": "gate", "c": "n."},
  {"w": "橋", "m": "bridge", "c": "n."},
  {"w": "道", "m": "road, way", "c": "n."},
  {"w": "交差点", "m": "intersection", "c": "n."},
  {"w": "信号", "m": "traffic light", "c": "n."},
  {"w": "プール", "m": "pool", "c": "n."},
  {"w": "エレベーター", "m": "elevator", "c": "n."},
  {"w": "階段", "m": "stairs", "c": "n."},
  {"w": "上", "m": "top, above", "c": "n."},
  {"w": "下", "m": "bottom, below", "c": "n."},
  {"w": "前", "m": "front", "c": "n."},
  {"w": "後ろ", "m": "back, behind", "c": "n."},
  {"w": "右", "m": "right", "c": "n."},
  {"w": "左", "m": "left", "c": "n."},
  {"w": "中", "m": "inside", "c": "n."},
  {"w": "外", "m": "outside", "c": "n."},
  {"w": "隣", "m": "next door, neighbor", "c": "n."},
  {"w": "近く", "m": "nearby", "c": "n."},
  {"w": "横", "m": "side", "c": "n."},
  {"w": "間", "m": "between", "c": "n."},
  {"w": "向こう", "m": "opposite side, over there", "c": "n."},
  {"w": "こちら", "m": "this way, here", "c": "n."},
  {"w": "そちら", "m": "that way, there", "c": "n."},
  {"w": "あちら", "m": "that way over there", "c": "n."},
  {"w": "どちら", "m": "which way", "c": "n."},
  {"w": "東", "m": "east", "c": "n."},
  {"w": "西", "m": "west", "c": "n."},
  {"w": "南", "m": "south", "c": "n."},
  {"w": "北", "m": "north", "c": "n."},
  {"w": "食べ物", "m": "food", "c": "n."},
  {"w": "飲み物", "m": "drink", "c": "n."},
  {"w": "ご飯", "m": "cooked rice, meal", "c": "n."},
  {"w": "朝ご飯", "m": "breakfast", "c": "n."},
  {"w": "昼ご飯", "m": "lunch", "c": "n."},
  {"w": "晩ご飯", "m": "dinner", "c": "n."},
  {"w": "パン", "m": "bread", "c": "n."},
  {"w": "卵", "m": "egg", "c": "n."},
  {"w": "肉", "m": "meat", "c": "n."},
  {"w": "魚", "m": "fish", "c": "n."},
  {"w": "野菜", "m": "vegetable", "c": "n."},
  {"w": "果物", "m": "fruit", "c": "n."},
  {"w": "りんご", "m": "apple", "c": "n."},
  {"w": "みかん", "m": "mandarin orange", "c": "n."},
  {"w": "料理", "m": "cooking, dish", "c": "n."},
  {"w": "お弁当", "m": "boxed lunch", "c": "n."},
  {"w": "お菓子", "m": "snack, sweets", "c": "n."},
  {"w": "水", "m": "water", "c": "n."},
  {"w": "お茶", "m": "tea", "c": "n."},
  {"w": "紅茶", "m": "black tea", "c": "n."},
  {"w": "コーヒー", "m": "coffee", "c": "n."},
  {"w": "牛乳", "m": "milk", "c": "n."},
  {"w": "ジュース", "m": "juice", "c": "n."},
  {"w": "お酒", "m": "alcohol", "c": "n."},
  {"w": "砂糖", "m": "sugar", "c": "n."},
  {"w": "塩", "m": "salt", "c": "n."},
  {"w": "醤油", "m": "soy sauce", "c": "n."},
  {"w": "物", "m": "thing", "c": "n."},
  {"w": "本", "m": "book", "c": "n."},
  {"w": "雑誌", "m": "magazine", "c": "n."},
  {"w": "新聞", "m": "newspaper", "c": "n."},
  {"w": "辞書", "m": "dictionary", "c": "n."},
  {"w": "教科書", "m": "textbook", "c": "n."},
  {"w": "ノート", "m": "notebook", "c": "n."},
  {"w": "手紙", "m": "letter", "c": "n."},
  {"w": "葉書", "m": "postcard", "c": "n."},
  {"w": "切手", "m": "stamp", "c": "n."},
  {"w": "封筒", "m": "envelope", "c": "n."},
  {"w": "鉛筆", "m": "pencil", "c": "n."},
  {"w": "ペン", "m": "pen", "c": "n."},
  {"w": "ボールペン", "m": "ballpoint pen", "c": "n."},
  {"w": "消しゴム", "m": "eraser", "c": "n."},
  {"w": "紙", "m": "paper", "c": "n."},
  {"w": "鍵", "m": "key", "c": "n."},
  {"w": "傘", "m": "umbrella", "c": "n."},
  {"w": "鞄", "m": "bag", "c": "n."},
  {"w": "財布", "m": "wallet", "c": "n."},
  {"w": "箱", "m": "box", "c": "n."},
  {"w": "時計", "m": "clock, watch", "c": "n."},
  {"w": "眼鏡", "m": "glasses", "c": "n."},
  {"w": "写真", "m": "photo", "c": "n."},
  {"w": "カメラ", "m": "camera", "c": "n."},
  {"w": "花", "m": "flower", "c": "n."},
  {"w": "テーブル", "m": "table", "c": "n."},
  {"w": "椅子", "m": "chair", "c": "n."},
  {"w": "机", "m": "desk", "c": "n."},
  {"w": "ベッド", "m": "bed", "c": "n."},
  {"w": "窓", "m": "window", "c": "n."},
  {"w": "ドア", "m": "door", "c": "n."},
  {"w": "電気", "m": "electricity, light", "c": "n."},
  {"w": "電話", "m": "telephone", "c": "n."},
  {"w": "テレビ", "m": "television", "c": "n."},
  {"w": "ラジオ", "m": "radio", "c": "n."},
  {"w": "パソコン", "m": "computer", "c": "n."},
  {"w": "エアコン", "m": "air conditioner", "c": "n."},
  {"w": "冷蔵庫", "m": "refrigerator", "c": "n."},
  {"w": "洗濯機", "m": "washing machine", "c": "n."},
  {"w": "石鹸", "m": "soap", "c": "n."},
  {"w": "タオル", "m": "towel", "c": "n."},
  {"w": "コップ", "m": "cup, glass", "c": "n."},
  {"w": "茶碗", "m": "rice bowl", "c": "n."},
  {"w": "皿", "m": "plate", "c": "n."},
  {"w": "箸", "m": "chopsticks", "c": "n."},
  {"w": "スプーン", "m": "spoon", "c": "n."},
  {"w": "フォーク", "m": "fork", "c": "n."},
  {"w": "ナイフ", "m": "knife", "c": "n."},
  {"w": "服", "m": "clothes", "c": "n."},
  {"w": "洋服", "m": "Western clothes", "c": "n."},
  {"w": "シャツ", "m": "shirt", "c": "n."},
  {"w": "Tシャツ", "m": "T-shirt", "c": "n."},
  {"w": "セーター", "m": "sweater", "c": "n."},
  {"w": "コート", "m": "coat", "c": "n."},
  {"w": "ズボン", "m": "pants", "c": "n."},
  {"w": "スカート", "m": "skirt", "c": "n."},
  {"w": "靴", "m": "shoes", "c": "n."},
  {"w": "靴下", "m": "socks", "c": "n."},
  {"w": "帽子", "m": "hat, cap", "c": "n."},
  {"w": "ネクタイ", "m": "necktie", "c": "n."},
  {"w": "体", "m": "body", "c": "n."},
  {"w": "頭", "m": "head", "c": "n."},
  {"w": "顔", "m": "face", "c": "n."},
  {"w": "目", "m": "eye", "c": "n."},
  {"w": "耳", "m": "ear", "c": "n."},
  {"w": "口", "m": "mouth", "c": "n."},
  {"w": "鼻", "m": "nose", "c": "n."},
  {"w": "歯", "m": "tooth", "c": "n."},
  {"w": "手", "m": "hand", "c": "n."},
  {"w": "足", "m": "foot, leg", "c": "n."},
  {"w": "指", "m": "finger", "c": "n."},
  {"w": "背", "m": "back; height", "c": "n."},
  {"w": "お腹", "m": "stomach, belly", "c": "n."},
  {"w": "声", "m": "voice", "c": "n."},
  {"w": "天気", "m": "weather", "c": "n."},
  {"w": "雨", "m": "rain", "c": "n."},
  {"w": "雪", "m": "snow", "c": "n."},
  {"w": "風", "m": "wind", "c": "n."},
  {"w": "空", "m": "sky", "c": "n."},
  {"w": "海", "m": "sea", "c": "n."},
  {"w": "山", "m": "mountain", "c": "n."},
  {"w": "川", "m": "river", "c": "n."},
  {"w": "木", "m": "tree", "c": "n."},
  {"w": "池", "m": "pond", "c": "n."},
  {"w": "動物", "m": "animal", "c": "n."},
  {"w": "犬", "m": "dog", "c": "n."},
  {"w": "猫", "m": "cat", "c": "n."},
  {"w": "鳥", "m": "bird", "c": "n."},
  {"w": "車", "m": "car", "c": "n."},
  {"w": "自転車", "m": "bicycle", "c": "n."},
  {"w": "タクシー", "m": "taxi", "c": "n."},
  {"w": "バス", "m": "bus", "c": "n."},
  {"w": "電車", "m": "train", "c": "n."},
  {"w": "地下鉄", "m": "subway", "c": "n."},
  {"w": "飛行機", "m": "airplane", "c": "n."},
  {"w": "船", "m": "ship, boat", "c": "n."},
  {"w": "切符", "m": "ticket", "c": "n."},
  {"w": "仕事", "m": "work, job", "c": "n."},
  {"w": "勉強", "m": "study", "c": "n."},
  {"w": "宿題", "m": "homework", "c": "n."},
  {"w": "試験", "m": "exam, test", "c": "n."},
  {"w": "テスト", "m": "test, quiz", "c": "n."},
  {"w": "問題", "m": "problem, question", "c": "n."},
  {"w": "質問", "m": "question", "c": "n."},
  {"w": "答え", "m": "answer", "c": "n."},
  {"w": "授業", "m": "class, lesson", "c": "n."},
  {"w": "練習", "m": "practice", "c": "n."},
  {"w": "旅行", "m": "travel, trip", "c": "n."},
  {"w": "散歩", "m": "walk, stroll", "c": "n."},
  {"w": "買い物", "m": "shopping", "c": "n."},
  {"w": "映画", "m": "movie", "c": "n."},
  {"w": "音楽", "m": "music", "c": "n."},
  {"w": "歌", "m": "song", "c": "n."},
  {"w": "スポーツ", "m": "sports", "c": "n."},
  {"w": "サッカー", "m": "soccer", "c": "n."},
  {"w": "テニス", "m": "tennis", "c": "n."},
  {"w": "水泳", "m": "swimming", "c": "n."},
  {"w": "ゲーム", "m": "game", "c": "n."},
  {"w": "パーティー", "m": "party", "c": "n."},
  {"w": "お祭り", "m": "festival", "c": "n."},
  {"w": "結婚式", "m": "wedding ceremony", "c": "n."},
  {"w": "言葉", "m": "language; word", "c": "n."},
  {"w": "意味", "m": "meaning", "c": "n."},
  {"w": "漢字", "m": "kanji, Chinese character", "c": "n."},
  {"w": "文", "m": "sentence", "c": "n."},
  {"w": "日本語", "m": "Japanese (language)", "c": "n."},
  {"w": "英語", "m": "English (language)", "c": "n."},
  {"w": "外国語", "m": "foreign language", "c": "n."},
  {"w": "お金", "m": "money", "c": "n."},
  {"w": "荷物", "m": "luggage, baggage", "c": "n."},
  {"w": "お土産", "m": "souvenir", "c": "n."},
  {"w": "プレゼント", "m": "present, gift", "c": "n."},
  {"w": "電話番号", "m": "phone number", "c": "n."},
  {"w": "住所", "m": "address", "c": "n."},
  {"w": "地図", "m": "map", "c": "n."},
  {"w": "番号", "m": "number", "c": "n."},
  {"w": "色", "m": "color", "c": "n."},
  {"w": "赤", "m": "red", "c": "n."},
  {"w": "青", "m": "blue", "c": "n."},
  {"w": "白", "m": "white", "c": "n."},
  {"w": "黒", "m": "black", "c": "n."},
  {"w": "音", "m": "sound", "c": "n."},
  {"w": "話", "m": "talk; story", "c": "n."},
  {"w": "心", "m": "heart, mind", "c": "n."},
  {"w": "気", "m": "spirit, feeling", "c": "n."},
  {"w": "病気", "m": "illness, sickness", "c": "n."},
  {"w": "風邪", "m": "cold (illness)", "c": "n."},
  {"w": "薬", "m": "medicine", "c": "n."},
  {"w": "ページ", "m": "page", "c": "n."},
  {"w": "クラス", "m": "class (group)", "c": "n."},
  {"w": "トイレ", "m": "toilet, restroom", "c": "n."},
  {"w": "シャワー", "m": "shower", "c": "n."},
  {"w": "お正月", "m": "New Year", "c": "n."},
  {"w": "用事", "m": "errand, business", "c": "n."},
  {"w": "約束", "m": "promise, appointment", "c": "n."},
  {"w": "趣味", "m": "hobby", "c": "n."},
  {"w": "世界", "m": "world", "c": "n."},
  {"w": "社会", "m": "society", "c": "n."},
  {"w": "経済", "m": "economy", "c": "n."},
  {"w": "文化", "m": "culture", "c": "n."},
  {"w": "歴史", "m": "history", "c": "n."},
  {"w": "ニュース", "m": "news", "c": "n."},
  {"w": "一つ", "m": "one (item)", "c": "n."},
  {"w": "二つ", "m": "two (items)", "c": "n."},
  {"w": "三つ", "m": "three (items)", "c": "n."},
  {"w": "四つ", "m": "four (items)", "c": "n."},
  {"w": "五つ", "m": "five (items)", "c": "n."},
  {"w": "六つ", "m": "six (items)", "c": "n."},
  {"w": "七つ", "m": "seven (items)", "c": "n."},
  {"w": "八つ", "m": "eight (items)", "c": "n."},
  {"w": "九つ", "m": "nine (items)", "c": "n."},
  {"w": "十", "m": "ten (items)", "c": "n."},
  {"w": "半分", "m": "half", "c": "n."},
  {"w": "全部", "m": "all, everything", "c": "n."},
  {"w": "日本", "m": "Japan", "c": "n."},
  {"w": "中国", "m": "China", "c": "n."},
  {"w": "韓国", "m": "South Korea", "c": "n."},
  {"w": "アメリカ", "m": "United States", "c": "n."},
  {"w": "イギリス", "m": "United Kingdom", "c": "n."},
  {"w": "フランス", "m": "France", "c": "n."},
  {"w": "ドイツ", "m": "Germany", "c": "n."},
  {"w": "食べる", "m": "to eat", "c": "v."},
  {"w": "見る", "m": "to see, to watch", "c": "v."},
  {"w": "起きる", "m": "to get up", "c": "v."},
  {"w": "寝る", "m": "to sleep", "c": "v."},
  {"w": "出る", "m": "to go out, to leave", "c": "v."},
  {"w": "入れる", "m": "to put in", "c": "v."},
  {"w": "出かける", "m": "to go out", "c": "v."},
  {"w": "開ける", "m": "to open", "c": "v."},
  {"w": "閉める", "m": "to close", "c": "v."},
  {"w": "つける", "m": "to turn on", "c": "v."},
  {"w": "消す", "m": "to turn off; to erase", "c": "v."},
  {"w": "教える", "m": "to teach; to tell", "c": "v."},
  {"w": "覚える", "m": "to memorize, to remember", "c": "v."},
  {"w": "忘れる", "m": "to forget", "c": "v."},
  {"w": "見せる", "m": "to show", "c": "v."},
  {"w": "答える", "m": "to answer", "c": "v."},
  {"w": "借りる", "m": "to borrow", "c": "v."},
  {"w": "浴びる", "m": "to pour over oneself, to bathe in", "c": "v."},
  {"w": "降りる", "m": "to get off, to descend", "c": "v."},
  {"w": "着る", "m": "to wear (upper body)", "c": "v."},
  {"w": "できる", "m": "to be able to, can", "c": "v."},
  {"w": "いる", "m": "to be, to exist (living things)", "c": "v."},
  {"w": "掛ける", "m": "to make (a phone call)", "c": "v."},
  {"w": "疲れる", "m": "to get tired", "c": "v."},
  {"w": "止める", "m": "to stop (something)", "c": "v."},
  {"w": "並べる", "m": "to line up, to arrange", "c": "v."},
  {"w": "始める", "m": "to begin (something)", "c": "v."},
  {"w": "生まれる", "m": "to be born", "c": "v."},
  {"w": "考える", "m": "to think, to consider", "c": "v."},
  {"w": "行く", "m": "to go", "c": "v."},
  {"w": "来る", "m": "to come", "c": "v."},
  {"w": "帰る", "m": "to go home, to return", "c": "v."},
  {"w": "ある", "m": "to be, to exist (non-living things)", "c": "v."},
  {"w": "する", "m": "to do", "c": "v."},
  {"w": "なる", "m": "to become", "c": "v."},
  {"w": "言う", "m": "to say", "c": "v."},
  {"w": "聞く", "m": "to listen; to ask", "c": "v."},
  {"w": "話す", "m": "to speak", "c": "v."},
  {"w": "読む", "m": "to read", "c": "v."},
  {"w": "書く", "m": "to write", "c": "v."},
  {"w": "飲む", "m": "to drink", "c": "v."},
  {"w": "買う", "m": "to buy", "c": "v."},
  {"w": "売る", "m": "to sell", "c": "v."},
  {"w": "待つ", "m": "to wait", "c": "v."},
  {"w": "立つ", "m": "to stand", "c": "v."},
  {"w": "座る", "m": "to sit", "c": "v."},
  {"w": "入る", "m": "to enter", "c": "v."},
  {"w": "乗る", "m": "to ride, to get on", "c": "v."},
  {"w": "走る", "m": "to run", "c": "v."},
  {"w": "歩く", "m": "to walk", "c": "v."},
  {"w": "泳ぐ", "m": "to swim", "c": "v."},
  {"w": "遊ぶ", "m": "to play", "c": "v."},
  {"w": "使う", "m": "to use", "c": "v."},
  {"w": "作る", "m": "to make", "c": "v."},
  {"w": "持つ", "m": "to hold, to have", "c": "v."},
  {"w": "置く", "m": "to put, to place", "c": "v."},
  {"w": "送る", "m": "to send", "c": "v."},
  {"w": "返す", "m": "to return (something)", "c": "v."},
  {"w": "貸す", "m": "to lend", "c": "v."},
  {"w": "押す", "m": "to push, to press", "c": "v."},
  {"w": "引く", "m": "to pull; to play (an instrument)", "c": "v."},
  {"w": "切る", "m": "to cut", "c": "v."},
  {"w": "撮る", "m": "to take (a photo)", "c": "v."},
  {"w": "取る", "m": "to take, to pick up", "c": "v."},
  {"w": "吸う", "m": "to smoke, to inhale", "c": "v."},
  {"w": "洗う", "m": "to wash", "c": "v."},
  {"w": "磨く", "m": "to brush (teeth)", "c": "v."},
  {"w": "渡す", "m": "to hand over", "c": "v."},
  {"w": "渡る", "m": "to cross", "c": "v."},
  {"w": "曲がる", "m": "to turn (a corner)", "c": "v."},
  {"w": "止まる", "m": "to stop (of its own accord)", "c": "v."},
  {"w": "動く", "m": "to move", "c": "v."},
  {"w": "開く", "m": "to open (by itself)", "c": "v."},
  {"w": "閉まる", "m": "to close (by itself)", "c": "v."},
  {"w": "付く", "m": "to turn on (by itself), to light up", "c": "v."},
  {"w": "消える", "m": "to disappear, to go out", "c": "v."},
  {"w": "掛かる", "m": "to take (time)", "c": "v."},
  {"w": "始まる", "m": "to begin (by itself)", "c": "v."},
  {"w": "終わる", "m": "to end", "c": "v."},
  {"w": "住む", "m": "to live, to reside", "c": "v."},
  {"w": "働く", "m": "to work", "c": "v."},
  {"w": "休む", "m": "to rest", "c": "v."},
  {"w": "出す", "m": "to take out", "c": "v."},
  {"w": "届く", "m": "to arrive, to reach", "c": "v."},
  {"w": "習う", "m": "to learn", "c": "v."},
  {"w": "会う", "m": "to meet", "c": "v."},
  {"w": "歌う", "m": "to sing", "c": "v."},
  {"w": "弾く", "m": "to play (an instrument)", "c": "v."},
  {"w": "吹く", "m": "to blow", "c": "v."},
  {"w": "降る", "m": "to fall (rain/snow)", "c": "v."},
  {"w": "飛ぶ", "m": "to fly", "c": "v."},
  {"w": "死ぬ", "m": "to die", "c": "v."},
  {"w": "要る", "m": "to need", "c": "v."},
  {"w": "知る", "m": "to know", "c": "v."},
  {"w": "分かる", "m": "to understand", "c": "v."},
  {"w": "思う", "m": "to think", "c": "v."},
  {"w": "困る", "m": "to be troubled", "c": "v."},
  {"w": "頼む", "m": "to ask, to request", "c": "v."},
  {"w": "呼ぶ", "m": "to call", "c": "v."},
  {"w": "笑う", "m": "to laugh", "c": "v."},
  {"w": "泣く", "m": "to cry", "c": "v."},
  {"w": "怒る", "m": "to get angry", "c": "v."},
  {"w": "違う", "m": "to be different, to be wrong", "c": "v."},
  {"w": "並ぶ", "m": "to line up, to stand in a line", "c": "v."},
  {"w": "登る", "m": "to climb", "c": "v."},
  {"w": "脱ぐ", "m": "to take off", "c": "v."},
  {"w": "履く", "m": "to wear (lower body/feet)", "c": "v."},
  {"w": "被る", "m": "to wear (on the head)", "c": "v."},
  {"w": "もらう", "m": "to receive", "c": "v."},
  {"w": "あげる", "m": "to give", "c": "v."},
  {"w": "くれる", "m": "to give (to me)", "c": "v."},
  {"w": "なくす", "m": "to lose", "c": "v."},
  {"w": "勉強する", "m": "to study", "c": "v."},
  {"w": "散歩する", "m": "to take a walk", "c": "v."},
  {"w": "旅行する", "m": "to travel", "c": "v."},
  {"w": "買い物する", "m": "to shop, to buy things", "c": "v."},
  {"w": "料理する", "m": "to cook", "c": "v."},
  {"w": "洗濯する", "m": "to do laundry", "c": "v."},
  {"w": "掃除する", "m": "to clean", "c": "v."},
  {"w": "電話する", "m": "to make a phone call", "c": "v."},
  {"w": "結婚する", "m": "to marry", "c": "v."},
  {"w": "練習する", "m": "to practice", "c": "v."},
  {"w": "コピーする", "m": "to copy, to photocopy", "c": "v."},
  {"w": "運動する", "m": "to exercise", "c": "v."},
  {"w": "心配する", "m": "to worry", "c": "v."},
  {"w": "食事する", "m": "to have a meal", "c": "v."},
  {"w": "準備する", "m": "to prepare", "c": "v."},
  {"w": "紹介する", "m": "to introduce", "c": "v."},
  {"w": "大きい", "m": "big, large", "c": "i-adj"},
  {"w": "小さい", "m": "small", "c": "i-adj"},
  {"w": "高い", "m": "tall, high; expensive", "c": "i-adj"},
  {"w": "安い", "m": "cheap", "c": "i-adj"},
  {"w": "低い", "m": "low", "c": "i-adj"},
  {"w": "新しい", "m": "new", "c": "i-adj"},
  {"w": "古い", "m": "old", "c": "i-adj"},
  {"w": "良い", "m": "good", "c": "i-adj"},
  {"w": "悪い", "m": "bad", "c": "i-adj"},
  {"w": "多い", "m": "many, a lot", "c": "i-adj"},
  {"w": "少ない", "m": "few, little", "c": "i-adj"},
  {"w": "長い", "m": "long", "c": "i-adj"},
  {"w": "短い", "m": "short", "c": "i-adj"},
  {"w": "広い", "m": "wide, spacious", "c": "i-adj"},
  {"w": "狭い", "m": "narrow", "c": "i-adj"},
  {"w": "重い", "m": "heavy", "c": "i-adj"},
  {"w": "軽い", "m": "light (weight)", "c": "i-adj"},
  {"w": "太い", "m": "thick", "c": "i-adj"},
  {"w": "細い", "m": "thin", "c": "i-adj"},
  {"w": "近い", "m": "near, close", "c": "i-adj"},
  {"w": "遠い", "m": "far", "c": "i-adj"},
  {"w": "速い", "m": "fast", "c": "i-adj"},
  {"w": "遅い", "m": "slow; late", "c": "i-adj"},
  {"w": "早い", "m": "early", "c": "i-adj"},
  {"w": "強い", "m": "strong", "c": "i-adj"},
  {"w": "弱い", "m": "weak", "c": "i-adj"},
  {"w": "暑い", "m": "hot (weather)", "c": "i-adj"},
  {"w": "熱い", "m": "hot (to the touch)", "c": "i-adj"},
  {"w": "寒い", "m": "cold (weather)", "c": "i-adj"},
  {"w": "冷たい", "m": "cold (to the touch)", "c": "i-adj"},
  {"w": "暖かい", "m": "warm", "c": "i-adj"},
  {"w": "涼しい", "m": "cool", "c": "i-adj"},
  {"w": "甘い", "m": "sweet", "c": "i-adj"},
  {"w": "辛い", "m": "spicy", "c": "i-adj"},
  {"w": "美味しい", "m": "delicious", "c": "i-adj"},
  {"w": "不味い", "m": "bad-tasting, unappetizing", "c": "i-adj"},
  {"w": "忙しい", "m": "busy", "c": "i-adj"},
  {"w": "楽しい", "m": "fun, enjoyable", "c": "i-adj"},
  {"w": "嬉しい", "m": "happy, glad", "c": "i-adj"},
  {"w": "悲しい", "m": "sad", "c": "i-adj"},
  {"w": "寂しい", "m": "lonely", "c": "i-adj"},
  {"w": "怖い", "m": "scary, frightening", "c": "i-adj"},
  {"w": "痛い", "m": "painful, hurts", "c": "i-adj"},
  {"w": "面白い", "m": "interesting, funny", "c": "i-adj"},
  {"w": "つまらない", "m": "boring", "c": "i-adj"},
  {"w": "難しい", "m": "difficult", "c": "i-adj"},
  {"w": "易しい", "m": "easy", "c": "i-adj"},
  {"w": "優しい", "m": "kind, gentle", "c": "i-adj"},
  {"w": "厳しい", "m": "strict", "c": "i-adj"},
  {"w": "明るい", "m": "bright", "c": "i-adj"},
  {"w": "暗い", "m": "dark", "c": "i-adj"},
  {"w": "白い", "m": "white", "c": "i-adj"},
  {"w": "黒い", "m": "black", "c": "i-adj"},
  {"w": "赤い", "m": "red", "c": "i-adj"},
  {"w": "青い", "m": "blue", "c": "i-adj"},
  {"w": "黄色い", "m": "yellow", "c": "i-adj"},
  {"w": "丸い", "m": "round", "c": "i-adj"},
  {"w": "四角い", "m": "square", "c": "i-adj"},
  {"w": "若い", "m": "young", "c": "i-adj"},
  {"w": "欲しい", "m": "wanted, desired", "c": "i-adj"},
  {"w": "眠い", "m": "sleepy", "c": "i-adj"},
  {"w": "うるさい", "m": "noisy", "c": "i-adj"},
  {"w": "汚い", "m": "dirty", "c": "i-adj"},
  {"w": "危ない", "m": "dangerous", "c": "i-adj"},
  {"w": "珍しい", "m": "rare, unusual", "c": "i-adj"},
  {"w": "可愛い", "m": "cute", "c": "i-adj"},
  {"w": "かっこいい", "m": "cool, good-looking", "c": "i-adj"},
  {"w": "すごい", "m": "amazing, incredible", "c": "i-adj"},
  {"w": "素晴らしい", "m": "wonderful, splendid", "c": "i-adj"},
  {"w": "正しい", "m": "correct", "c": "i-adj"},
  {"w": "元気", "m": "energetic, healthy", "c": "na-adj"},
  {"w": "好き", "m": "liked, fond of", "c": "na-adj"},
  {"w": "嫌い", "m": "disliked, hated", "c": "na-adj"},
  {"w": "大好き", "m": "love, like very much", "c": "na-adj"},
  {"w": "大嫌い", "m": "hate, dislike strongly", "c": "na-adj"},
  {"w": "上手", "m": "skillful, good at", "c": "na-adj"},
  {"w": "下手", "m": "unskillful, poor at", "c": "na-adj"},
  {"w": "有名", "m": "famous", "c": "na-adj"},
  {"w": "静か", "m": "quiet", "c": "na-adj"},
  {"w": "賑やか", "m": "lively, bustling", "c": "na-adj"},
  {"w": "親切", "m": "kind", "c": "na-adj"},
  {"w": "丁寧", "m": "polite", "c": "na-adj"},
  {"w": "便利", "m": "convenient", "c": "na-adj"},
  {"w": "不便", "m": "inconvenient", "c": "na-adj"},
  {"w": "簡単", "m": "simple, easy", "c": "na-adj"},
  {"w": "複雑", "m": "complicated", "c": "na-adj"},
  {"w": "大切", "m": "important", "c": "na-adj"},
  {"w": "大丈夫", "m": "fine, all right", "c": "na-adj"},
  {"w": "綺麗", "m": "beautiful; clean", "c": "na-adj"},
  {"w": "暇", "m": "free (time)", "c": "na-adj"},
  {"w": "色々", "m": "various", "c": "na-adj"},
  {"w": "大変", "m": "tough, terrible; very", "c": "na-adj"},
  {"w": "立派", "m": "admirable, splendid", "c": "na-adj"},
  {"w": "特別", "m": "special", "c": "na-adj"},
  {"w": "同じ", "m": "same", "c": "na-adj"},
  {"w": "ハンサム", "m": "handsome", "c": "na-adj"},
  {"w": "とても", "m": "very", "c": "adv"},
  {"w": "たくさん", "m": "a lot, many", "c": "adv"},
  {"w": "少し", "m": "a little", "c": "adv"},
  {"w": "ちょっと", "m": "a bit, a little", "c": "adv"},
  {"w": "もっと", "m": "more", "c": "adv"},
  {"w": "一番", "m": "most, number one", "c": "adv"},
  {"w": "よく", "m": "often; well, carefully", "c": "adv"},
  {"w": "いつも", "m": "always", "c": "adv"},
  {"w": "時々", "m": "sometimes", "c": "adv"},
  {"w": "たまに", "m": "occasionally", "c": "adv"},
  {"w": "あまり", "m": "not very", "c": "adv"},
  {"w": "全然", "m": "completely (not); not at all", "c": "adv"},
  {"w": "まだ", "m": "still; not yet", "c": "adv"},
  {"w": "もう", "m": "already", "c": "adv"},
  {"w": "すぐ", "m": "right away; soon", "c": "adv"},
  {"w": "ゆっくり", "m": "slowly", "c": "adv"},
  {"w": "だんだん", "m": "gradually", "c": "adv"},
  {"w": "初めて", "m": "for the first time", "c": "adv"},
  {"w": "まず", "m": "first", "c": "adv"},
  {"w": "多分", "m": "probably", "c": "adv"},
  {"w": "きっと", "m": "surely; certainly", "c": "adv"},
  {"w": "本当に", "m": "really", "c": "adv"},
  {"w": "大体", "m": "roughly; mostly", "c": "adv"},
  {"w": "一緒に", "m": "together", "c": "adv"},
  {"w": "また", "m": "again", "c": "adv"},
  {"w": "まっすぐ", "m": "straight", "c": "adv"},
  {"w": "ちゃんと", "m": "properly", "c": "adv"},
  {"w": "はっきり", "m": "clearly", "c": "adv"},
  {"w": "どうぞ", "m": "please", "c": "adv"},
  {"w": "どう", "m": "how", "c": "adv"},
  {"w": "なぜ", "m": "why", "c": "adv"},
  {"w": "どうして", "m": "why", "c": "adv"},
  {"w": "どうやって", "m": "how (to do something)", "c": "adv"},
  {"w": "どのくらい", "m": "how much/how long", "c": "adv"},
  {"w": "いくら", "m": "how much (cost)", "c": "adv"},
  {"w": "いくつ", "m": "how many; how old", "c": "adv"},
  {"w": "いつ", "m": "when", "c": "adv"},
  {"w": "どこ", "m": "where", "c": "adv"},
  {"w": "何", "m": "what", "c": "adv"},
  {"w": "誰", "m": "who", "c": "adv"},
  {"w": "もう少し", "m": "a little more", "c": "adv"},
  {"w": "そろそろ", "m": "soon; about time to", "c": "adv"},
  {"w": "やっと", "m": "finally; at last", "c": "adv"},
  {"w": "さっき", "m": "a moment ago", "c": "adv"},
  {"w": "もう一度", "m": "once more", "c": "adv"},
  {"w": "必ず", "m": "always; without fail", "c": "adv"},
  {"w": "絶対", "m": "absolutely", "c": "adv"},
  {"w": "特に", "m": "especially", "c": "adv"},
  {"w": "普通", "m": "normal; usual", "c": "adv"},
  {"w": "はい", "m": "yes", "c": "other"},
  {"w": "いいえ", "m": "no", "c": "other"},
  {"w": "ええ", "m": "yes (casual)", "c": "other"},
  {"w": "いい", "m": "good", "c": "other"},
  {"w": "おはようございます", "m": "good morning", "c": "other"},
  {"w": "こんにちは", "m": "hello; good afternoon", "c": "other"},
  {"w": "こんばんは", "m": "good evening", "c": "other"},
  {"w": "さようなら", "m": "goodbye", "c": "other"},
  {"w": "おやすみなさい", "m": "good night", "c": "other"},
  {"w": "すみません", "m": "excuse me; sorry", "c": "other"},
  {"w": "ごめんなさい", "m": "I'm sorry", "c": "other"},
  {"w": "ありがとうございます", "m": "thank you", "c": "other"},
  {"w": "どういたしまして", "m": "you're welcome", "c": "other"},
  {"w": "いただきます", "m": "(said before eating) let's eat", "c": "other"},
  {"w": "ごちそうさまでした", "m": "(said after eating) that was a feast", "c": "other"},
  {"w": "行ってきます", "m": "I'm off; see you later", "c": "other"},
  {"w": "行ってらっしゃい", "m": "take care; see you", "c": "other"},
  {"w": "ただいま", "m": "I'm home", "c": "other"},
  {"w": "お帰りなさい", "m": "welcome home", "c": "other"},
  {"w": "お願いします", "m": "please; I ask this of you", "c": "other"},
  {"w": "初めまして", "m": "nice to meet you", "c": "other"},
  {"w": "よろしくお願いします", "m": "please treat me well; nice to meet you", "c": "other"},
  {"w": "お元気ですか", "m": "how are you", "c": "other"},
  {"w": "お大事に", "m": "take care (of yourself)", "c": "other"},
  {"w": "お誕生日おめでとう", "m": "happy birthday", "c": "other"},
  {"w": "おめでとうございます", "m": "congratulations", "c": "other"},
  {"w": "失礼します", "m": "excuse me (entering/leaving)", "c": "other"},
  {"w": "ちょっと待ってください", "m": "please wait a moment", "c": "other"},
  {"w": "でも", "m": "but", "c": "other"},
  {"w": "しかし", "m": "however", "c": "other"},
  {"w": "そして", "m": "and then", "c": "other"},
  {"w": "それから", "m": "after that", "c": "other"},
  {"w": "それで", "m": "so; and so", "c": "other"},
  {"w": "だから", "m": "so; therefore", "c": "other"},
  {"w": "けれども", "m": "but; although", "c": "other"},
  {"w": "それに", "m": "moreover; besides", "c": "other"},
  {"w": "または", "m": "or", "c": "other"},
  {"w": "これ", "m": "this", "c": "other"},
  {"w": "それ", "m": "that", "c": "other"},
  {"w": "あれ", "m": "that (over there)", "c": "other"},
  {"w": "どれ", "m": "which", "c": "other"},
  {"w": "この", "m": "this ~", "c": "other"},
  {"w": "その", "m": "that ~", "c": "other"},
  {"w": "あの", "m": "that ~ (over there)", "c": "other"},
  {"w": "どの", "m": "which ~", "c": "other"},
  {"w": "ここ", "m": "here", "c": "other"},
  {"w": "そこ", "m": "there", "c": "other"},
  {"w": "あそこ", "m": "over there", "c": "other"},
  {"w": "こう", "m": "like this", "c": "other"},
  {"w": "そう", "m": "like that", "c": "other"},
  {"w": "ああ", "m": "like that (over there)", "c": "other"},
  {"w": "こんな", "m": "like this; this kind of", "c": "other"},
  {"w": "そんな", "m": "like that; that kind of", "c": "other"},
  {"w": "あんな", "m": "like that (over there); that kind of", "c": "other"},
  {"w": "どんな", "m": "what kind of", "c": "other"},
  {"w": "ぐらい", "m": "about; approximately", "c": "other"},
  {"w": "ごろ", "m": "around (time)", "c": "other"},
  {"w": "まで", "m": "until; up to", "c": "other"},
  {"w": "から", "m": "from", "c": "other"},
  {"w": "と", "m": "and; with", "c": "other"},
  {"w": "や", "m": "and (partial listing)", "c": "other"},
  {"w": "など", "m": "and so on; etc.", "c": "other"},
  {"w": "だけ", "m": "only", "c": "other"},
  {"w": "しか", "m": "only (+ negative)", "c": "other"},
  {"w": "ほう", "m": "side; direction", "c": "other"},
  {"w": "みんな", "m": "everyone", "c": "other"},
  {"w": "自分", "m": "oneself", "c": "other"},
  {"w": "こと", "m": "thing; matter", "c": "other"},
  {"w": "ため", "m": "for the sake of", "c": "other"},
  {"w": "つもり", "m": "intend to", "c": "other"},
  {"w": "はず", "m": "should; expected to", "c": "other"},
  {"w": "ところ", "m": "just about to", "c": "other"},
  {"w": "ばかり", "m": "only; just (did)", "c": "other"},
  {"w": "そうです", "m": "I hear that; it's said that", "c": "other"},
  {"w": "ようだ", "m": "it seems; looks like", "c": "other"},
  {"w": "かもしれない", "m": "might; maybe", "c": "other"},
  {"w": "なければならない", "m": "must; have to", "c": "other"},
  {"w": "てもいい", "m": "may; it's okay to", "c": "other"},
  {"w": "てはいけない", "m": "must not; may not", "c": "other"},
  {"w": "たい", "m": "want to", "c": "other"},
  {"w": "ましょう", "m": "let's", "c": "other"},
  {"w": "でしょう", "m": "probably; I guess", "c": "other"},
  {"w": "そうだ", "m": "seems like; looks like (hearsay/appearance auxiliary)", "c": "other"},
  {"w": "ください", "m": "please (give/do)", "c": "other"},
  {"w": "お疲れ様です", "m": "thank you for your hard work", "c": "other"},
  {"w": "あのう", "m": "um, excuse me (filler)", "c": "other"},
  {"w": "ええと", "m": "um, let me see (filler, thinking)", "c": "other"},
];
