const VOCAB_N5 = [
// 名詞
// ── 人・人称 ──
{w:"私",r:"わたし",m:"我",c:"名",ex:{j:"私は学生です。",z:"我是學生。",e:"I am a student."}},
{w:"僕",r:"ぼく",m:"我(男)",c:"名",ex:{j:"僕はサッカーが好きです。",z:"我喜歡足球。",e:"I like soccer."}},
{w:"あなた",r:"あなた",m:"你",c:"名",ex:{j:"あなたの名前は何ですか。",z:"你的名字是什麼？",e:"What is your name?"}},
{w:"彼",r:"かれ",m:"他",c:"名",ex:{j:"彼は先生です。",z:"他是老師。",e:"He is a teacher."}},
{w:"彼女",r:"かのじょ",m:"她",c:"名",ex:{j:"彼女はとても親切です。",z:"她非常親切。",e:"She is very kind."}},
{w:"皆さん",r:"みなさん",m:"大家",c:"名",ex:{j:"皆さん、おはようございます。",z:"大家早安。",e:"Good morning, everyone."}},
{w:"人",r:"ひと",m:"人",c:"名",ex:{j:"公園にたくさんの人がいます。",z:"公園裡有很多人。",e:"There are many people in the park."}},
{w:"方",r:"かた",m:"(敬)位",c:"名",ex:{j:"あの方は田中さんです。",z:"那位是田中先生。",e:"That person is Mr. Tanaka."}},
{w:"子供",r:"こども",m:"小孩",c:"名",ex:{j:"子供が公園で遊んでいます。",z:"小孩在公園裡玩。",e:"The children are playing in the park."}},
{w:"男",r:"おとこ",m:"男性",c:"名",ex:{j:"あそこに男の人がいます。",z:"那裡有一個男的。",e:"There is a man over there."}},
{w:"女",r:"おんな",m:"女性",c:"名",ex:{j:"女の人が本を読んでいます。",z:"一個女的在看書。",e:"A woman is reading a book."}},
{w:"男の子",r:"おとこのこ",m:"男孩",c:"名",ex:{j:"あの男の子は私の弟です。",z:"那個男孩是我弟弟。",e:"That boy is my little brother."}},
{w:"女の子",r:"おんなのこ",m:"女孩",c:"名",ex:{j:"かわいい女の子が笑っています。",z:"可愛的女孩在笑。",e:"A cute girl is smiling."}},
{w:"大人",r:"おとな",m:"大人",c:"名",ex:{j:"この映画は大人だけの映画です。",z:"這部電影是只有大人能看的電影。",e:"This movie is only for adults."}},
{w:"友達",r:"ともだち",m:"朋友",c:"名",ex:{j:"友達と映画を見ました。",z:"我和朋友看了電影。",e:"I watched a movie with my friend."}},
{w:"名前",r:"なまえ",m:"名字",c:"名",ex:{j:"ここに名前を書いてください。",z:"請在這裡寫上名字。",e:"Please write your name here."}},
// ── 家族 ──
{w:"家族",r:"かぞく",m:"家人",c:"名",ex:{j:"私の家族は四人です。",z:"我家有四個人。",e:"My family has four people."}},
{w:"お父さん",r:"おとうさん",m:"爸爸",c:"名",ex:{j:"お父さんは毎日働いています。",z:"爸爸每天都在工作。",e:"My father works every day."}},
{w:"お母さん",r:"おかあさん",m:"媽媽",c:"名",ex:{j:"お母さんは料理が上手です。",z:"媽媽很會做菜。",e:"My mother is good at cooking."}},
{w:"お兄さん",r:"おにいさん",m:"哥哥",c:"名",ex:{j:"お兄さんは大学生ですか。",z:"你哥哥是大學生嗎？",e:"Is your older brother a college student?"}},
{w:"お姉さん",r:"おねえさん",m:"姐姐",c:"名",ex:{j:"お姉さんはとてもきれいです。",z:"姐姐非常漂亮。",e:"My older sister is very beautiful."}},
{w:"弟",r:"おとうと",m:"弟弟",c:"名",ex:{j:"弟は今年五歳です。",z:"弟弟今年五歲。",e:"My little brother is five years old this year."}},
{w:"妹",r:"いもうと",m:"妹妹",c:"名",ex:{j:"妹はピアノを習っています。",z:"妹妹在學鋼琴。",e:"My little sister is learning piano."}},
{w:"兄弟",r:"きょうだい",m:"兄弟姊妹",c:"名",ex:{j:"兄弟が三人います。",z:"我有三個兄弟姊妹。",e:"I have three siblings."}},
{w:"奥さん",r:"おくさん",m:"太太",c:"名",ex:{j:"田中さんの奥さんは日本人です。",z:"田中先生的太太是日本人。",e:"Mr. Tanaka's wife is Japanese."}},
{w:"主人",r:"しゅじん",m:"丈夫",c:"名",ex:{j:"主人は会社員です。",z:"我丈夫是上班族。",e:"My husband is an office worker."}},
{w:"両親",r:"りょうしん",m:"雙親",c:"名",ex:{j:"両親は大阪に住んでいます。",z:"我的雙親住在大阪。",e:"My parents live in Osaka."}},
{w:"息子",r:"むすこ",m:"兒子",c:"名",ex:{j:"息子は小学生です。",z:"我兒子是小學生。",e:"My son is an elementary school student."}},
{w:"娘",r:"むすめ",m:"女兒",c:"名",ex:{j:"娘は歌が好きです。",z:"我女兒喜歡唱歌。",e:"My daughter likes singing."}},
{w:"お祖父さん",r:"おじいさん",m:"爺爺",c:"名",ex:{j:"お祖父さんは元気です。",z:"爺爺很健康。",e:"My grandfather is doing well."}},
{w:"お祖母さん",r:"おばあさん",m:"奶奶",c:"名",ex:{j:"お祖母さんはとても元気です。",z:"奶奶非常健康有精神。",e:"My grandmother is very healthy and energetic."}},
{w:"おじさん",r:"おじさん",m:"叔叔",c:"名",ex:{j:"おじさんは車を二台持っています。",z:"叔叔有兩台車。",e:"My uncle has two cars."}},
{w:"おばさん",r:"おばさん",m:"阿姨",c:"名",ex:{j:"おばさんはケーキを作るのが上手です。",z:"阿姨很會做蛋糕。",e:"My aunt is good at making cakes."}},
// ── 職業・身分 ──
{w:"先生",r:"せんせい",m:"老師",c:"名",ex:{j:"田中先生は日本語を教えています。",z:"田中老師在教日文。",e:"Mr. Tanaka teaches Japanese."}},
{w:"学生",r:"がくせい",m:"學生",c:"名",ex:{j:"私は大学の学生です。",z:"我是大學生。",e:"I am a university student."}},
{w:"留学生",r:"りゅうがくせい",m:"留學生",c:"名",ex:{j:"クラスに留学生が三人います。",z:"班上有三個留學生。",e:"There are three international students in the class."}},
{w:"会社員",r:"かいしゃいん",m:"公司職員",c:"名",ex:{j:"父は会社員です。",z:"我爸爸是公司職員。",e:"My father is a company employee."}},
{w:"銀行員",r:"ぎんこういん",m:"銀行員",c:"名",ex:{j:"姉は銀行員になりました。",z:"姐姐成為了銀行員。",e:"My older sister became a bank clerk."}},
{w:"医者",r:"いしゃ",m:"醫生",c:"名",ex:{j:"熱があるので医者に行きます。",z:"因為發燒,所以要去看醫生。",e:"I have a fever, so I'm going to the doctor."}},
{w:"警官",r:"けいかん",m:"警察",c:"名",ex:{j:"あそこに警官が立っています。",z:"那裡站著一位警察。",e:"A police officer is standing over there."}},
{w:"店員",r:"てんいん",m:"店員",c:"名",ex:{j:"あの店員はとても親切です。",z:"那位店員非常親切。",e:"That shop clerk is very kind."}},
// ── 時間 ──
{w:"時間",r:"じかん",m:"時間",c:"名",ex:{j:"今日は時間がありません。",z:"今天沒有時間。",e:"I don't have time today."}},
{w:"今",r:"いま",m:"現在",c:"名",ex:{j:"今、何時ですか。",z:"現在幾點?",e:"What time is it now?"}},
{w:"今日",r:"きょう",m:"今天",c:"名",ex:{j:"今日は天気がいいです。",z:"今天天氣很好。",e:"The weather is nice today."}},
{w:"明日",r:"あした",m:"明天",c:"名",ex:{j:"明日、友達に会います。",z:"明天要見朋友。",e:"I'm going to meet my friend tomorrow."}},
{w:"昨日",r:"きのう",m:"昨天",c:"名",ex:{j:"昨日、映画を見ました。",z:"昨天看了電影。",e:"I watched a movie yesterday."}},
{w:"今朝",r:"けさ",m:"今天早上",c:"名",ex:{j:"今朝はパンを食べました。",z:"今天早上吃了麵包。",e:"I ate bread this morning."}},
{w:"今晩",r:"こんばん",m:"今晚",c:"名",ex:{j:"今晩、家で勉強します。",z:"今晚要在家讀書。",e:"I'll study at home tonight."}},
{w:"朝",r:"あさ",m:"早上",c:"名",ex:{j:"朝は六時に起きます。",z:"早上六點起床。",e:"I wake up at six in the morning."}},
{w:"昼",r:"ひる",m:"中午",c:"名",ex:{j:"昼はいつもラーメンを食べます。",z:"中午總是吃拉麵。",e:"I always eat ramen at noon."}},
{w:"夜",r:"よる",m:"晚上",c:"名",ex:{j:"夜は星がきれいです。",z:"晚上星星很漂亮。",e:"The stars are beautiful at night."}},
{w:"夕方",r:"ゆうがた",m:"傍晚",c:"名",ex:{j:"夕方、散歩をします。",z:"傍晚會去散步。",e:"I take a walk in the evening."}},
{w:"晩",r:"ばん",m:"晚間",c:"名",ex:{j:"晩ご飯はもう食べました。",z:"晚飯已經吃過了。",e:"I have already eaten dinner."}},
{w:"午前",r:"ごぜん",m:"上午",c:"名",ex:{j:"午前中は会議があります。",z:"上午有會議。",e:"There is a meeting in the morning."}},
{w:"午後",r:"ごご",m:"下午",c:"名",ex:{j:"午後から雨が降ります。",z:"下午開始會下雨。",e:"It will rain from the afternoon."}},
{w:"毎日",r:"まいにち",m:"每天",c:"名",ex:{j:"毎日、日本語を勉強します。",z:"每天學習日文。",e:"I study Japanese every day."}},
{w:"毎朝",r:"まいあさ",m:"每天早上",c:"名",ex:{j:"毎朝、コーヒーを飲みます。",z:"每天早上喝咖啡。",e:"I drink coffee every morning."}},
{w:"毎晩",r:"まいばん",m:"每晚",c:"名",ex:{j:"毎晩、歯を磨きます。",z:"每晚刷牙。",e:"I brush my teeth every night."}},
{w:"毎週",r:"まいしゅう",m:"每週",c:"名",ex:{j:"毎週、日曜日に休みます。",z:"每週日休息。",e:"I take a rest every Sunday."}},
{w:"毎月",r:"まいつき",m:"每月",c:"名",ex:{j:"毎月、本を三冊買います。",z:"每個月買三本書。",e:"I buy three books every month."}},
{w:"毎年",r:"まいとし",m:"每年",c:"名",ex:{j:"毎年、夏に海へ行きます。",z:"每年夏天都會去海邊。",e:"Every year I go to the sea in summer."}},
{w:"先週",r:"せんしゅう",m:"上週",c:"名",ex:{j:"先週は、とても忙しかったです。",z:"上週非常忙。",e:"Last week was very busy."}},
{w:"今週",r:"こんしゅう",m:"這週",c:"名",ex:{j:"今週は、テストがあります。",z:"這週有考試。",e:"There is a test this week."}},
{w:"来週",r:"らいしゅう",m:"下週",c:"名",ex:{j:"来週、友だちに会います。",z:"下週要和朋友見面。",e:"I will meet my friend next week."}},
{w:"先月",r:"せんげつ",m:"上個月",c:"名",ex:{j:"先月、日本へ来ました。",z:"上個月來到了日本。",e:"I came to Japan last month."}},
{w:"今月",r:"こんげつ",m:"這個月",c:"名",ex:{j:"今月は、雨の日が多いです。",z:"這個月雨天很多。",e:"There are many rainy days this month."}},
{w:"来月",r:"らいげつ",m:"下個月",c:"名",ex:{j:"来月、国へ帰ります。",z:"下個月要回國。",e:"I will return to my country next month."}},
{w:"去年",r:"きょねん",m:"去年",c:"名",ex:{j:"去年、京都で写真をたくさん撮りました。",z:"去年在京都拍了很多照片。",e:"Last year I took many photos in Kyoto."}},
{w:"今年",r:"ことし",m:"今年",c:"名",ex:{j:"今年、日本語の勉強を始めました。",z:"今年開始學日語了。",e:"I started studying Japanese this year."}},
{w:"来年",r:"らいねん",m:"明年",c:"名",ex:{j:"来年、大学に入りたいです。",z:"明年想上大學。",e:"I want to enter university next year."}},
{w:"再来年",r:"さらいねん",m:"後年",c:"名",ex:{j:"再来年、また日本へ来ます。",z:"後年會再來日本。",e:"I will come to Japan again the year after next."}},
{w:"一昨日",r:"おととい",m:"前天",c:"名",ex:{j:"一昨日、映画を見ました。",z:"前天看了電影。",e:"I watched a movie the day before yesterday."}},
{w:"明後日",r:"あさって",m:"後天",c:"名",ex:{j:"明後日、テストがあります。",z:"後天有考試。",e:"There is a test the day after tomorrow."}},
{w:"誕生日",r:"たんじょうび",m:"生日",c:"名",ex:{j:"私の誕生日は五月です。",z:"我的生日在五月。",e:"My birthday is in May."}},
{w:"休み",r:"やすみ",m:"休息・假日",c:"名",ex:{j:"明日は休みです。",z:"明天是假日。",e:"Tomorrow is a day off."}},
// ── 曜日 ──
{w:"月曜日",r:"げつようび",m:"星期一",c:"名",ex:{j:"月曜日から学校が始まります。",z:"星期一開始上學。",e:"School starts on Monday."}},
{w:"火曜日",r:"かようび",m:"星期二",c:"名",ex:{j:"火曜日に病院へ行きます。",z:"星期二要去醫院。",e:"I will go to the hospital on Tuesday."}},
{w:"水曜日",r:"すいようび",m:"星期三",c:"名",ex:{j:"水曜日は、いつも早く帰ります。",z:"星期三總是早回家。",e:"I always go home early on Wednesday."}},
{w:"木曜日",r:"もくようび",m:"星期四",c:"名",ex:{j:"木曜日に日本語のクラスがあります。",z:"星期四有日語課。",e:"I have a Japanese class on Thursday."}},
{w:"金曜日",r:"きんようび",m:"星期五",c:"名",ex:{j:"金曜日の夜、友だちと食事をします。",z:"星期五晚上和朋友吃飯。",e:"I have dinner with friends on Friday night."}},
{w:"土曜日",r:"どようび",m:"星期六",c:"名",ex:{j:"土曜日は、家で本を読みます。",z:"星期六在家看書。",e:"On Saturday I read books at home."}},
{w:"日曜日",r:"にちようび",m:"星期日",c:"名",ex:{j:"日曜日は、どこにも行きません。",z:"星期日哪裡都不去。",e:"I don't go anywhere on Sunday."}},
// ── 月份 ──
{w:"一月",r:"いちがつ",m:"一月",c:"名",ex:{j:"一月は、とても寒いです。",z:"一月非常冷。",e:"January is very cold."}},
{w:"二月",r:"にがつ",m:"二月",c:"名",ex:{j:"二月に、日本で雪を見ました。",z:"二月在日本看到了雪。",e:"I saw snow in Japan in February."}},
{w:"三月",r:"さんがつ",m:"三月",c:"名",ex:{j:"三月に、学校を卒業します。",z:"三月要從學校畢業。",e:"I will graduate from school in March."}},
{w:"四月",r:"しがつ",m:"四月",c:"名",ex:{j:"四月から、新しい仕事を始めます。",z:"四月開始新工作。",e:"I will start a new job in April."}},
{w:"五月",r:"ごがつ",m:"五月",c:"名",ex:{j:"五月は、天気がいいです。",z:"五月天氣很好。",e:"The weather is nice in May."}},
{w:"六月",r:"ろくがつ",m:"六月",c:"名",ex:{j:"六月は、雨がよく降ります。",z:"六月常常下雨。",e:"It rains often in June."}},
{w:"七月",r:"しちがつ",m:"七月",c:"名",ex:{j:"七月に、海で泳ぎます。",z:"七月要在海裡游泳。",e:"I will swim in the sea in July."}},
{w:"八月",r:"はちがつ",m:"八月",c:"名",ex:{j:"八月は、とても暑いです。",z:"八月非常熱。",e:"August is very hot."}},
{w:"九月",r:"くがつ",m:"九月",c:"名",ex:{j:"九月に日本へ行きます。",z:"九月要去日本。",e:"I will go to Japan in September."}},
{w:"十月",r:"じゅうがつ",m:"十月",c:"名",ex:{j:"十月は少し涼しいです。",z:"十月有點涼。",e:"It is a little cool in October."}},
{w:"十一月",r:"じゅういちがつ",m:"十一月",c:"名",ex:{j:"十一月に試験があります。",z:"十一月有考試。",e:"There is an exam in November."}},
{w:"十二月",r:"じゅうにがつ",m:"十二月",c:"名",ex:{j:"十二月はとても寒いです。",z:"十二月很冷。",e:"December is very cold."}},
// ── 場所 ──
{w:"所",r:"ところ",m:"地方",c:"名",ex:{j:"ここは静かな所です。",z:"這裡是個安靜的地方。",e:"This is a quiet place."}},
{w:"家",r:"いえ",m:"家",c:"名",ex:{j:"私の家は駅の近くです。",z:"我家在車站附近。",e:"My house is near the station."}},
{w:"うち",r:"うち",m:"(自己)家",c:"名",ex:{j:"今日はうちで晩ご飯を食べます。",z:"今天在家裡吃晚飯。",e:"Today I will eat dinner at home."}},
{w:"部屋",r:"へや",m:"房間",c:"名",ex:{j:"私の部屋は明るいです。",z:"我的房間很明亮。",e:"My room is bright."}},
{w:"台所",r:"だいどころ",m:"廚房",c:"名",ex:{j:"母は台所で料理をしています。",z:"媽媽在廚房做菜。",e:"My mother is cooking in the kitchen."}},
{w:"玄関",r:"げんかん",m:"玄關",c:"名",ex:{j:"玄関で靴を脱ぎます。",z:"在玄關脫鞋子。",e:"I take off my shoes at the entrance."}},
{w:"庭",r:"にわ",m:"庭院",c:"名",ex:{j:"庭に花がたくさんあります。",z:"庭院裡有很多花。",e:"There are many flowers in the garden."}},
{w:"お手洗い",r:"おてあらい",m:"洗手間",c:"名",ex:{j:"すみません、お手洗いはどこですか。",z:"不好意思,洗手間在哪裡?",e:"Excuse me, where is the restroom?"}},
{w:"お風呂",r:"おふろ",m:"浴室",c:"名",ex:{j:"毎晩お風呂に入ります。",z:"每天晚上都會泡澡。",e:"I take a bath every night."}},
{w:"学校",r:"がっこう",m:"學校",c:"名",ex:{j:"私は毎日学校へ行きます。",z:"我每天去學校。",e:"I go to school every day."}},
{w:"大学",r:"だいがく",m:"大學",c:"名",ex:{j:"兄は東京の大学で勉強しています。",z:"哥哥在東京的大學讀書。",e:"My older brother studies at a university in Tokyo."}},
{w:"教室",r:"きょうしつ",m:"教室",c:"名",ex:{j:"教室に学生が三人います。",z:"教室裡有三個學生。",e:"There are three students in the classroom."}},
{w:"図書館",r:"としょかん",m:"圖書館",c:"名",ex:{j:"図書館で本を借りました。",z:"在圖書館借了書。",e:"I borrowed a book at the library."}},
{w:"食堂",r:"しょくどう",m:"食堂",c:"名",ex:{j:"お昼は食堂でご飯を食べます。",z:"中午在食堂吃飯。",e:"I eat lunch at the cafeteria."}},
{w:"病院",r:"びょういん",m:"醫院",c:"名",ex:{j:"風邪をひいたので病院へ行きます。",z:"因為感冒了所以去醫院。",e:"I have a cold, so I am going to the hospital."}},
{w:"銀行",r:"ぎんこう",m:"銀行",c:"名",ex:{j:"銀行でお金を下ろします。",z:"在銀行領錢。",e:"I withdraw money at the bank."}},
{w:"郵便局",r:"ゆうびんきょく",m:"郵局",c:"名",ex:{j:"郵便局で切手を買いました。",z:"在郵局買了郵票。",e:"I bought stamps at the post office."}},
{w:"会社",r:"かいしゃ",m:"公司",c:"名",ex:{j:"父は毎朝会社へ行きます。",z:"爸爸每天早上去公司。",e:"My father goes to the company every morning."}},
{w:"店",r:"みせ",m:"店",c:"名",ex:{j:"あの店は野菜が安いです。",z:"那家店的蔬菜很便宜。",e:"That shop has cheap vegetables."}},
{w:"喫茶店",r:"きっさてん",m:"咖啡店",c:"名",ex:{j:"友達と喫茶店でコーヒーを飲みました。",z:"和朋友在咖啡店喝了咖啡。",e:"I drank coffee with a friend at a coffee shop."}},
{w:"レストラン",r:"れすとらん",m:"餐廳",c:"名",ex:{j:"今晩レストランで食事をします。",z:"今晚在餐廳用餐。",e:"Tonight I will have a meal at a restaurant."}},
{w:"デパート",r:"でぱーと",m:"百貨公司",c:"名",ex:{j:"デパートでかばんを買いました。",z:"在百貨公司買了包包。",e:"I bought a bag at the department store."}},
{w:"スーパー",r:"すーぱー",m:"超市",c:"名",ex:{j:"スーパーで卵と牛乳を買います。",z:"在超市買雞蛋和牛奶。",e:"I buy eggs and milk at the supermarket."}},
{w:"ホテル",r:"ほてる",m:"旅館",c:"名",ex:{j:"京都のホテルに泊まりました。",z:"住在京都的旅館。",e:"I stayed at a hotel in Kyoto."}},
{w:"映画館",r:"えいがかん",m:"電影院",c:"名",ex:{j:"映画館で新しい映画を見ました。",z:"在電影院看了新電影。",e:"I watched a new movie at the cinema."}},
{w:"公園",r:"こうえん",m:"公園",c:"名",ex:{j:"日曜日に公園を散歩します。",z:"星期天在公園散步。",e:"I take a walk in the park on Sundays."}},
{w:"駅",r:"えき",m:"車站",c:"名",ex:{j:"駅で友だちを待ちます。",z:"我在車站等朋友。",e:"I'll wait for my friend at the station."}},
{w:"空港",r:"くうこう",m:"機場",c:"名",ex:{j:"空港まで車で行きます。",z:"開車去機場。",e:"I'm going to the airport by car."}},
{w:"町",r:"まち",m:"城鎮",c:"名",ex:{j:"この町はとても静かです。",z:"這個城鎮很安靜。",e:"This town is very quiet."}},
{w:"国",r:"くに",m:"國家",c:"名",ex:{j:"どの国から来ましたか。",z:"你來自哪個國家?",e:"Which country are you from?"}},
{w:"外国",r:"がいこく",m:"外國",c:"名",ex:{j:"外国で働きたいです。",z:"我想在外國工作。",e:"I want to work in a foreign country."}},
{w:"入口",r:"いりぐち",m:"入口",c:"名",ex:{j:"入口はあちらです。",z:"入口在那邊。",e:"The entrance is over there."}},
{w:"出口",r:"でぐち",m:"出口",c:"名",ex:{j:"出口はどこですか。",z:"出口在哪裡?",e:"Where is the exit?"}},
{w:"門",r:"もん",m:"門",c:"名",ex:{j:"学校の門の前で会いましょう。",z:"我們在學校的門前見面吧。",e:"Let's meet in front of the school gate."}},
{w:"橋",r:"はし",m:"橋",c:"名",ex:{j:"あの橋を渡ってください。",z:"請過那座橋。",e:"Please cross that bridge."}},
{w:"道",r:"みち",m:"路",c:"名",ex:{j:"この道はまっすぐです。",z:"這條路是直的。",e:"This road is straight."}},
{w:"交差点",r:"こうさてん",m:"十字路口",c:"名",ex:{j:"次の交差点を右に曲がります。",z:"在下一個十字路口右轉。",e:"Turn right at the next intersection."}},
{w:"信号",r:"しんごう",m:"紅綠燈",c:"名",ex:{j:"信号が赤ですから、止まってください。",z:"因為紅綠燈是紅的,請停下來。",e:"The light is red, so please stop."}},
{w:"プール",r:"ぷーる",m:"游泳池",c:"名",ex:{j:"夏はよくプールで泳ぎます。",z:"夏天我常在游泳池游泳。",e:"In summer I often swim in the pool."}},
{w:"エレベーター",r:"えれべーたー",m:"電梯",c:"名",ex:{j:"エレベーターで五階まで行きます。",z:"搭電梯到五樓。",e:"I'll take the elevator to the fifth floor."}},
{w:"階段",r:"かいだん",m:"樓梯",c:"名",ex:{j:"階段を上って二階に行きます。",z:"上樓梯到二樓。",e:"I go up the stairs to the second floor."}},
// ── 方向・位置 ──
{w:"上",r:"うえ",m:"上面",c:"名",ex:{j:"机の上に本があります。",z:"書桌上面有書。",e:"There is a book on the desk."}},
{w:"下",r:"した",m:"下面",c:"名",ex:{j:"いすの下に猫がいます。",z:"椅子下面有貓。",e:"There is a cat under the chair."}},
{w:"前",r:"まえ",m:"前面",c:"名",ex:{j:"駅の前にコンビニがあります。",z:"車站前面有便利商店。",e:"There is a convenience store in front of the station."}},
{w:"後ろ",r:"うしろ",m:"後面",c:"名",ex:{j:"わたしの後ろに立ってください。",z:"請站在我後面。",e:"Please stand behind me."}},
{w:"右",r:"みぎ",m:"右邊",c:"名",ex:{j:"銀行は右にあります。",z:"銀行在右邊。",e:"The bank is on the right."}},
{w:"左",r:"ひだり",m:"左邊",c:"名",ex:{j:"左を見てください。",z:"請看左邊。",e:"Please look to the left."}},
{w:"中",r:"なか",m:"裡面",c:"名",ex:{j:"かばんの中に財布があります。",z:"包包裡面有錢包。",e:"There is a wallet in the bag."}},
{w:"外",r:"そと",m:"外面",c:"名",ex:{j:"外は寒いです。",z:"外面很冷。",e:"It's cold outside."}},
{w:"隣",r:"となり",m:"隔壁",c:"名",ex:{j:"わたしの隣に座ってください。",z:"請坐在我隔壁。",e:"Please sit next to me."}},
{w:"近く",r:"ちかく",m:"附近",c:"名",ex:{j:"家の近くに公園があります。",z:"家附近有公園。",e:"There is a park near my house."}},
{w:"横",r:"よこ",m:"旁邊",c:"名",ex:{j:"テレビの横に時計があります。",z:"電視旁邊有時鐘。",e:"There is a clock beside the TV."}},
{w:"間",r:"あいだ",m:"之間",c:"名",ex:{j:"銀行と郵便局の間にお店があります。",z:"銀行和郵局之間有一家店。",e:"There is a shop between the bank and the post office."}},
{w:"向こう",r:"むこう",m:"對面",c:"名",ex:{j:"道の向こうに駅が見えます。",z:"路的對面看得到車站。",e:"You can see the station across the road."}},
{w:"こちら",r:"こちら",m:"這邊",c:"名",ex:{j:"こちらへどうぞ。",z:"請往這邊走。",e:"This way, please."}},
{w:"そちら",r:"そちら",m:"那邊",c:"名",ex:{j:"そちらの天気はどうですか。",z:"你那邊的天氣如何?",e:"How is the weather over there?"}},
{w:"あちら",r:"あちら",m:"那邊(遠)",c:"名",ex:{j:"トイレはあちらです。",z:"洗手間在那邊。",e:"The restroom is over there."}},
{w:"どちら",r:"どちら",m:"哪邊",c:"名",ex:{j:"駅はどちらですか。",z:"車站在哪邊呢?",e:"Which way is the station?"}},
{w:"東",r:"ひがし",m:"東",c:"名",ex:{j:"太陽は東から出ます。",z:"太陽從東邊升起。",e:"The sun rises from the east."}},
{w:"西",r:"にし",m:"西",c:"名",ex:{j:"わたしの部屋は西を向いています。",z:"我的房間朝西。",e:"My room faces west."}},
{w:"南",r:"みなみ",m:"南",c:"名",ex:{j:"日本の南は暑いです。",z:"日本的南部很熱。",e:"The south of Japan is hot."}},
{w:"北",r:"きた",m:"北",c:"名",ex:{j:"北の空に星が見えます。",z:"北邊的天空看得到星星。",e:"You can see stars in the northern sky."}},
// ── 食べ物・飲み物 ──
{w:"食べ物",r:"たべもの",m:"食物",c:"名",ex:{j:"好きな食べ物は何ですか。",z:"你喜歡的食物是什麼?",e:"What food do you like?"}},
{w:"飲み物",r:"のみもの",m:"飲料",c:"名",ex:{j:"飲み物は何がいいですか。",z:"飲料要喝什麼好呢?",e:"What would you like to drink?"}},
{w:"ご飯",r:"ごはん",m:"飯・餐",c:"名",ex:{j:"もうご飯を食べましたか。",z:"你已經吃飯了嗎?",e:"Have you eaten yet?"}},
{w:"朝ご飯",r:"あさごはん",m:"早餐",c:"名",ex:{j:"毎朝、朝ご飯を食べます。",z:"我每天早上都吃早餐。",e:"I eat breakfast every morning."}},
{w:"昼ご飯",r:"ひるごはん",m:"午餐",c:"名",ex:{j:"昼ご飯は友だちと食べます。",z:"午餐我和朋友一起吃。",e:"I eat lunch with my friend."}},
{w:"晩ご飯",r:"ばんごはん",m:"晚餐",c:"名",ex:{j:"今日の晩ご飯はカレーです。",z:"今天的晚餐是咖哩。",e:"Tonight's dinner is curry."}},
{w:"パン",r:"ぱん",m:"麵包",c:"名",ex:{j:"朝はパンを食べます。",z:"早上我吃麵包。",e:"I eat bread in the morning."}},
{w:"卵",r:"たまご",m:"蛋",c:"名",ex:{j:"卵を二つ買いました。",z:"我買了兩顆蛋。",e:"I bought two eggs."}},
{w:"肉",r:"にく",m:"肉",c:"名",ex:{j:"わたしは肉が好きです。",z:"我喜歡吃肉。",e:"I like meat."}},
{w:"魚",r:"さかな",m:"魚",c:"名",ex:{j:"昨日、魚を食べました。",z:"我昨天吃了魚。",e:"I ate fish yesterday."}},
{w:"野菜",r:"やさい",m:"蔬菜",c:"名",ex:{j:"野菜をたくさん食べてください。",z:"請多吃蔬菜。",e:"Please eat lots of vegetables."}},
{w:"果物",r:"くだもの",m:"水果",c:"名",ex:{j:"果物は体にいいです。",z:"水果對身體很好。",e:"Fruit is good for your health."}},
{w:"りんご",r:"りんご",m:"蘋果",c:"名",ex:{j:"りんごを一つください。",z:"請給我一顆蘋果。",e:"One apple, please."}},
{w:"みかん",r:"みかん",m:"橘子",c:"名",ex:{j:"冬はみかんをよく食べます。",z:"冬天我常吃橘子。",e:"I often eat mandarin oranges in winter."}},
{w:"料理",r:"りょうり",m:"料理",c:"名",ex:{j:"母の料理はおいしいです。",z:"媽媽做的菜很好吃。",e:"My mother's cooking is delicious."}},
{w:"お弁当",r:"おべんとう",m:"便當",c:"名",ex:{j:"公園でお弁当を食べました。",z:"我在公園吃了便當。",e:"I ate a bento in the park."}},
{w:"お菓子",r:"おかし",m:"點心",c:"名",ex:{j:"子どもはお菓子が大好きです。",z:"小孩最喜歡點心了。",e:"Children love sweets."}},
{w:"水",r:"みず",m:"水",c:"名",ex:{j:"水を一杯ください。",z:"請給我一杯水。",e:"A glass of water, please."}},
{w:"お茶",r:"おちゃ",m:"茶",c:"名",ex:{j:"どうぞ、お茶を飲んでください。",z:"請喝茶。",e:"Please have some tea."}},
{w:"紅茶",r:"こうちゃ",m:"紅茶",c:"名",ex:{j:"わたしは毎朝紅茶を飲みます。",z:"我每天早上喝紅茶。",e:"I drink black tea every morning."}},
{w:"コーヒー",r:"こーひー",m:"咖啡",c:"名",ex:{j:"コーヒーは苦いです。",z:"咖啡很苦。",e:"Coffee is bitter."}},
{w:"牛乳",r:"ぎゅうにゅう",m:"牛奶",c:"名",ex:{j:"わたしは毎日、牛乳を飲みます。",z:"我每天喝牛奶。",e:"I drink milk every day."}},
{w:"ジュース",r:"じゅーす",m:"果汁",c:"名",ex:{j:"子どもはジュースが好きです。",z:"小孩喜歡果汁。",e:"Children like juice."}},
{w:"お酒",r:"おさけ",m:"酒",c:"名",ex:{j:"お酒はあまり飲みません。",z:"我不太喝酒。",e:"I don't drink much alcohol."}},
{w:"砂糖",r:"さとう",m:"糖",c:"名",ex:{j:"コーヒーに砂糖を入れます。",z:"在咖啡裡加糖。",e:"I put sugar in my coffee."}},
{w:"塩",r:"しお",m:"鹽",c:"名",ex:{j:"この料理は塩が少ないです。",z:"這道菜鹽放得很少。",e:"This dish doesn't have much salt."}},
{w:"醤油",r:"しょうゆ",m:"醬油",c:"名",ex:{j:"寿司に醤油をつけて食べます。",z:"壽司沾醬油吃。",e:"I eat sushi dipped in soy sauce."}},
// ── 物・日用品 ──
{w:"物",r:"もの",m:"東西",c:"名",ex:{j:"机の上に物がたくさんあります。",z:"桌上有很多東西。",e:"There are a lot of things on the desk."}},
{w:"本",r:"ほん",m:"書",c:"名",ex:{j:"毎晩、寝る前に本を読みます。",z:"每天晚上睡前看書。",e:"I read a book every night before bed."}},
{w:"雑誌",r:"ざっし",m:"雜誌",c:"名",ex:{j:"電車の中で雑誌を読みました。",z:"我在電車裡看了雜誌。",e:"I read a magazine on the train."}},
{w:"新聞",r:"しんぶん",m:"報紙",c:"名",ex:{j:"父は朝、新聞を読みます。",z:"爸爸早上看報紙。",e:"My father reads the newspaper in the morning."}},
{w:"辞書",r:"じしょ",m:"字典",c:"名",ex:{j:"わからない言葉を辞書で調べます。",z:"用字典查不懂的單字。",e:"I look up words I don't know in the dictionary."}},
{w:"教科書",r:"きょうかしょ",m:"教科書",c:"名",ex:{j:"教科書を開いてください。",z:"請翻開教科書。",e:"Please open your textbook."}},
{w:"ノート",r:"のーと",m:"筆記本",c:"名",ex:{j:"新しいノートを一冊買いました。",z:"我買了一本新的筆記本。",e:"I bought a new notebook."}},
{w:"手紙",r:"てがみ",m:"信",c:"名",ex:{j:"友達に手紙を書きます。",z:"我寫信給朋友。",e:"I write a letter to my friend."}},
{w:"葉書",r:"はがき",m:"明信片",c:"名",ex:{j:"旅行先から葉書を送りました。",z:"我從旅行地寄了明信片。",e:"I sent a postcard from where I was traveling."}},
{w:"切手",r:"きって",m:"郵票",c:"名",ex:{j:"封筒に切手を貼ります。",z:"在信封上貼郵票。",e:"I put a stamp on the envelope."}},
{w:"封筒",r:"ふうとう",m:"信封",c:"名",ex:{j:"この封筒に手紙を入れてください。",z:"請把信放進這個信封裡。",e:"Please put the letter in this envelope."}},
{w:"鉛筆",r:"えんぴつ",m:"鉛筆",c:"名",ex:{j:"鉛筆で名前を書きます。",z:"用鉛筆寫名字。",e:"I write my name with a pencil."}},
{w:"ペン",r:"ぺん",m:"筆",c:"名",ex:{j:"赤いペンを貸してください。",z:"請借我紅筆。",e:"Please lend me the red pen."}},
{w:"ボールペン",r:"ぼーるぺん",m:"原子筆",c:"名",ex:{j:"このボールペンで手紙を書きます。",z:"用這支原子筆寫信。",e:"I write a letter with this ballpoint pen."}},
{w:"消しゴム",r:"けしごむ",m:"橡皮擦",c:"名",ex:{j:"消しゴムで字を消しました。",z:"我用橡皮擦擦掉了字。",e:"I erased the letters with an eraser."}},
{w:"紙",r:"かみ",m:"紙",c:"名",ex:{j:"紙に地図を書きます。",z:"在紙上畫地圖。",e:"I draw a map on paper."}},
{w:"鍵",r:"かぎ",m:"鑰匙",c:"名",ex:{j:"家の鍵をなくしました。",z:"我把家裡的鑰匙弄丟了。",e:"I lost my house key."}},
{w:"傘",r:"かさ",m:"傘",c:"名",ex:{j:"雨が降るから、傘を持って行きます。",z:"因為會下雨，所以帶傘去。",e:"It's going to rain, so I'll take an umbrella."}},
{w:"鞄",r:"かばん",m:"包包",c:"名",ex:{j:"新しい鞄がほしいです。",z:"我想要一個新包包。",e:"I want a new bag."}},
{w:"財布",r:"さいふ",m:"錢包",c:"名",ex:{j:"財布にお金がありません。",z:"錢包裡沒有錢。",e:"There's no money in my wallet."}},
{w:"箱",r:"はこ",m:"箱子",c:"名",ex:{j:"この箱は重いです。",z:"這個箱子很重。",e:"This box is heavy."}},
{w:"時計",r:"とけい",m:"時鐘・手錶",c:"名",ex:{j:"壁の時計は十時です。",z:"牆上的時鐘是十點。",e:"The clock on the wall says ten o'clock."}},
{w:"眼鏡",r:"めがね",m:"眼鏡",c:"名",ex:{j:"眼鏡をかけて本を読みます。",z:"戴著眼鏡看書。",e:"I read a book with my glasses on."}},
{w:"写真",r:"しゃしん",m:"照片",c:"名",ex:{j:"家族の写真を撮りました。",z:"我拍了家人的照片。",e:"I took a photo of my family."}},
{w:"カメラ",r:"かめら",m:"相機",c:"名",ex:{j:"新しいカメラで写真を撮ります。",z:"用新相機拍照。",e:"I take photos with my new camera."}},
{w:"花",r:"はな",m:"花",c:"名",ex:{j:"庭にきれいな花が咲いています。",z:"庭院裡開著漂亮的花。",e:"Beautiful flowers are blooming in the garden."}},
{w:"テーブル",r:"てーぶる",m:"桌子",c:"名",ex:{j:"テーブルの上に料理を並べます。",z:"把菜擺在桌子上。",e:"I arrange the dishes on the table."}},
{w:"椅子",r:"いす",m:"椅子",c:"名",ex:{j:"この椅子はとても軽いです。",z:"這張椅子非常輕。",e:"This chair is very light."}},
{w:"机",r:"つくえ",m:"書桌",c:"名",ex:{j:"机の上に本があります。",z:"書桌上有書。",e:"There is a book on the desk."}},
{w:"ベッド",r:"べっど",m:"床",c:"名",ex:{j:"疲れたので、早くベッドで寝ます。",z:"因為累了,我要早點在床上睡覺。",e:"I'm tired, so I'll sleep in bed early."}},
{w:"窓",r:"まど",m:"窗戶",c:"名",ex:{j:"暑いですから、窓を開けてください。",z:"因為很熱,請把窗戶打開。",e:"It's hot, so please open the window."}},
{w:"ドア",r:"どあ",m:"門",c:"名",ex:{j:"すみません、そのドアを閉めてください。",z:"不好意思,請把那扇門關上。",e:"Excuse me, please close that door."}},
{w:"電気",r:"でんき",m:"電・燈",c:"名",ex:{j:"寝る前に電気を消します。",z:"睡覺前把燈關掉。",e:"I turn off the light before going to bed."}},
{w:"電話",r:"でんわ",m:"電話",c:"名",ex:{j:"あとで母に電話をします。",z:"我等一下要打電話給媽媽。",e:"I'll call my mother later."}},
{w:"テレビ",r:"てれび",m:"電視",c:"名",ex:{j:"毎晩テレビでニュースを見ます。",z:"每天晚上都看電視上的新聞。",e:"I watch the news on TV every night."}},
{w:"ラジオ",r:"らじお",m:"收音機",c:"名",ex:{j:"朝はいつもラジオを聞きます。",z:"早上總是聽收音機。",e:"I always listen to the radio in the morning."}},
{w:"パソコン",r:"ぱそこん",m:"電腦",c:"名",ex:{j:"仕事でパソコンを使います。",z:"工作時使用電腦。",e:"I use a computer for work."}},
{w:"エアコン",r:"えあこん",m:"冷氣",c:"名",ex:{j:"部屋が暑いので、エアコンをつけます。",z:"房間很熱,所以開冷氣。",e:"The room is hot, so I'll turn on the air conditioner."}},
{w:"冷蔵庫",r:"れいぞうこ",m:"冰箱",c:"名",ex:{j:"牛乳は冷蔵庫の中にあります。",z:"牛奶在冰箱裡面。",e:"The milk is in the refrigerator."}},
{w:"洗濯機",r:"せんたくき",m:"洗衣機",c:"名",ex:{j:"洗濯機でシャツを洗います。",z:"用洗衣機洗襯衫。",e:"I wash my shirt with the washing machine."}},
{w:"石鹸",r:"せっけん",m:"肥皂",c:"名",ex:{j:"石鹸で手をきれいに洗います。",z:"用肥皂把手洗乾淨。",e:"I wash my hands clean with soap."}},
{w:"タオル",r:"たおる",m:"毛巾",c:"名",ex:{j:"新しいタオルで顔を拭きます。",z:"用新的毛巾擦臉。",e:"I wipe my face with a new towel."}},
{w:"コップ",r:"こっぷ",m:"杯子",c:"名",ex:{j:"コップに水を入れます。",z:"把水倒進杯子裡。",e:"I pour water into the cup."}},
{w:"茶碗",r:"ちゃわん",m:"碗",c:"名",ex:{j:"茶碗にご飯を入れます。",z:"把飯裝進碗裡。",e:"I put the rice into the bowl."}},
{w:"皿",r:"さら",m:"盤子",c:"名",ex:{j:"皿を三枚買いました。",z:"我買了三個盤子。",e:"I bought three plates."}},
{w:"箸",r:"はし",m:"筷子",c:"名",ex:{j:"日本人は箸でご飯を食べます。",z:"日本人用筷子吃飯。",e:"Japanese people eat rice with chopsticks."}},
{w:"スプーン",r:"すぷーん",m:"湯匙",c:"名",ex:{j:"スプーンでスープを飲みます。",z:"用湯匙喝湯。",e:"I drink soup with a spoon."}},
{w:"フォーク",r:"ふぉーく",m:"叉子",c:"名",ex:{j:"フォークでケーキを食べます。",z:"用叉子吃蛋糕。",e:"I eat cake with a fork."}},
{w:"ナイフ",r:"ないふ",m:"刀子",c:"名",ex:{j:"ナイフでパンを切ります。",z:"用刀子切麵包。",e:"I cut bread with a knife."}},
// ── 衣類 ──
{w:"服",r:"ふく",m:"衣服",c:"名",ex:{j:"今日は新しい服を着ます。",z:"今天穿新衣服。",e:"I'll wear new clothes today."}},
{w:"洋服",r:"ようふく",m:"西服",c:"名",ex:{j:"デパートで洋服を買いました。",z:"在百貨公司買了衣服。",e:"I bought clothes at the department store."}},
{w:"シャツ",r:"しゃつ",m:"襯衫",c:"名",ex:{j:"白いシャツはとてもきれいです。",z:"白色的襯衫很漂亮。",e:"The white shirt is very pretty."}},
{w:"Tシャツ",r:"てぃーしゃつ",m:"T恤",c:"名",ex:{j:"夏はいつもTシャツを着ます。",z:"夏天總是穿T恤。",e:"I always wear a T-shirt in summer."}},
{w:"セーター",r:"せーたー",m:"毛衣",c:"名",ex:{j:"寒いので、セーターを着ます。",z:"因為很冷,所以穿毛衣。",e:"It's cold, so I'll wear a sweater."}},
{w:"コート",r:"こーと",m:"大衣",c:"名",ex:{j:"冬は暖かいコートが要ります。",z:"冬天需要一件溫暖的大衣。",e:"I need a warm coat in winter."}},
{w:"ズボン",r:"ずぼん",m:"褲子",c:"名",ex:{j:"この黒いズボンは少し長いです。",z:"這條黑色的褲子有點長。",e:"These black pants are a little long."}},
{w:"スカート",r:"すかーと",m:"裙子",c:"名",ex:{j:"妹は赤いスカートが好きです。",z:"妹妹喜歡紅色的裙子。",e:"My younger sister likes red skirts."}},
{w:"靴",r:"くつ",m:"鞋子",c:"名",ex:{j:"新しい靴を買いました。",z:"我買了新鞋子。",e:"I bought new shoes."}},
{w:"靴下",r:"くつした",m:"襪子",c:"名",ex:{j:"白い靴下をはいています。",z:"我穿著白色的襪子。",e:"I'm wearing white socks."}},
{w:"帽子",r:"ぼうし",m:"帽子",c:"名",ex:{j:"暑いので帽子をかぶります。",z:"因為很熱，所以戴帽子。",e:"It's hot, so I'll wear a hat."}},
{w:"ネクタイ",r:"ねくたい",m:"領帶",c:"名",ex:{j:"父は青いネクタイをしています。",z:"爸爸打著藍色的領帶。",e:"My father is wearing a blue tie."}},
// ── 身体 ──
{w:"体",r:"からだ",m:"身體",c:"名",ex:{j:"毎日運動して、体を強くします。",z:"每天運動，讓身體變強壯。",e:"I exercise every day to make my body stronger."}},
{w:"頭",r:"あたま",m:"頭",c:"名",ex:{j:"今日は頭が痛いです。",z:"今天我頭很痛。",e:"My head hurts today."}},
{w:"顔",r:"かお",m:"臉",c:"名",ex:{j:"朝起きて、顔を洗います。",z:"早上起床後洗臉。",e:"I wake up in the morning and wash my face."}},
{w:"目",r:"め",m:"眼睛",c:"名",ex:{j:"彼女は目が大きいです。",z:"她的眼睛很大。",e:"She has big eyes."}},
{w:"耳",r:"みみ",m:"耳朵",c:"名",ex:{j:"うさぎは耳が長いです。",z:"兔子的耳朵很長。",e:"Rabbits have long ears."}},
{w:"口",r:"くち",m:"嘴巴",c:"名",ex:{j:"口を大きく開けてください。",z:"請把嘴巴張大。",e:"Please open your mouth wide."}},
{w:"鼻",r:"はな",m:"鼻子",c:"名",ex:{j:"風邪で鼻が赤いです。",z:"因為感冒，鼻子紅紅的。",e:"My nose is red from a cold."}},
{w:"歯",r:"は",m:"牙齒",c:"名",ex:{j:"寝る前に歯を磨きます。",z:"睡覺前刷牙。",e:"I brush my teeth before going to bed."}},
{w:"手",r:"て",m:"手",c:"名",ex:{j:"ご飯の前に手を洗ってください。",z:"吃飯前請洗手。",e:"Please wash your hands before eating."}},
{w:"足",r:"あし",m:"腳",c:"名",ex:{j:"たくさん歩いて、足が痛いです。",z:"走了很多路，腳很痛。",e:"I walked a lot, so my feet hurt."}},
{w:"指",r:"ゆび",m:"手指",c:"名",ex:{j:"指でボタンを押します。",z:"用手指按按鈕。",e:"I press the button with my finger."}},
{w:"背",r:"せ",m:"背・身高",c:"名",ex:{j:"弟は背が高いです。",z:"弟弟個子很高。",e:"My younger brother is tall."}},
{w:"お腹",r:"おなか",m:"肚子",c:"名",ex:{j:"お腹がすきました。",z:"我肚子餓了。",e:"I'm hungry."}},
{w:"声",r:"こえ",m:"聲音",c:"名",ex:{j:"先生の声は大きいです。",z:"老師的聲音很大。",e:"The teacher's voice is loud."}},
// ── 自然・天気 ──
{w:"天気",r:"てんき",m:"天氣",c:"名",ex:{j:"今日はいい天気ですね。",z:"今天天氣真好呢。",e:"The weather is nice today, isn't it?"}},
{w:"雨",r:"あめ",m:"雨",c:"名",ex:{j:"朝から雨が降っています。",z:"從早上開始就在下雨。",e:"It's been raining since morning."}},
{w:"雪",r:"ゆき",m:"雪",c:"名",ex:{j:"冬になると雪が降ります。",z:"到了冬天就會下雪。",e:"It snows when winter comes."}},
{w:"風",r:"かぜ",m:"風",c:"名",ex:{j:"今日は風が強いです。",z:"今天風很大。",e:"The wind is strong today."}},
{w:"空",r:"そら",m:"天空",c:"名",ex:{j:"空が青くてきれいです。",z:"天空又藍又漂亮。",e:"The sky is blue and beautiful."}},
{w:"海",r:"うみ",m:"海",c:"名",ex:{j:"夏に家族と海へ行きます。",z:"夏天要和家人去海邊。",e:"I'm going to the sea with my family in summer."}},
{w:"山",r:"やま",m:"山",c:"名",ex:{j:"あの山はとても高いです。",z:"那座山非常高。",e:"That mountain is very tall."}},
{w:"川",r:"かわ",m:"河",c:"名",ex:{j:"川で魚を見ました。",z:"在河裡看到了魚。",e:"I saw fish in the river."}},
{w:"木",r:"き",m:"樹",c:"名",ex:{j:"公園に大きい木があります。",z:"公園裡有一棵大樹。",e:"There is a big tree in the park."}},
{w:"池",r:"いけ",m:"池塘",c:"名",ex:{j:"池に魚がたくさんいます。",z:"池塘裡有很多魚。",e:"There are many fish in the pond."}},
// ── 動物 ──
{w:"動物",r:"どうぶつ",m:"動物",c:"名",ex:{j:"わたしは動物が好きです。",z:"我喜歡動物。",e:"I like animals."}},
{w:"犬",r:"いぬ",m:"狗",c:"名",ex:{j:"うちの犬はとてもかわいいです。",z:"我家的狗非常可愛。",e:"My dog is very cute."}},
{w:"猫",r:"ねこ",m:"貓",c:"名",ex:{j:"うちの猫はとてもかわいいです。",z:"我家的貓非常可愛。",e:"My cat is very cute."}},
{w:"鳥",r:"とり",m:"鳥",c:"名",ex:{j:"空を鳥が飛んでいます。",z:"天空中有鳥在飛。",e:"A bird is flying in the sky."}},
// ── 交通 ──
{w:"車",r:"くるま",m:"車",c:"名",ex:{j:"父は毎日車で会社へ行きます。",z:"爸爸每天開車去公司。",e:"My father goes to the office by car every day."}},
{w:"自転車",r:"じてんしゃ",m:"腳踏車",c:"名",ex:{j:"わたしは自転車で学校へ行きます。",z:"我騎腳踏車去學校。",e:"I go to school by bicycle."}},
{w:"タクシー",r:"たくしー",m:"計程車",c:"名",ex:{j:"雨なのでタクシーで帰ります。",z:"因為下雨,我搭計程車回家。",e:"Because it's raining, I'll go home by taxi."}},
{w:"バス",r:"ばす",m:"公車",c:"名",ex:{j:"駅までバスで行きます。",z:"我搭公車到車站。",e:"I go to the station by bus."}},
{w:"電車",r:"でんしゃ",m:"電車",c:"名",ex:{j:"電車はもう来ましたか。",z:"電車已經來了嗎?",e:"Has the train already come?"}},
{w:"地下鉄",r:"ちかてつ",m:"地鐵",c:"名",ex:{j:"東京では地下鉄がとても便利です。",z:"在東京地鐵非常方便。",e:"The subway is very convenient in Tokyo."}},
{w:"飛行機",r:"ひこうき",m:"飛機",c:"名",ex:{j:"来月、飛行機で日本へ行きます。",z:"下個月我要搭飛機去日本。",e:"Next month I'll go to Japan by plane."}},
{w:"船",r:"ふね",m:"船",c:"名",ex:{j:"島まで船で行きました。",z:"我搭船去了那座島。",e:"I went to the island by boat."}},
{w:"切符",r:"きっぷ",m:"車票",c:"名",ex:{j:"駅で電車の切符を買います。",z:"我在車站買電車的車票。",e:"I buy a train ticket at the station."}},
// ── 活動・行事 ──
{w:"仕事",r:"しごと",m:"工作",c:"名",ex:{j:"今日は仕事がたくさんあります。",z:"今天有很多工作。",e:"I have a lot of work today."}},
{w:"勉強",r:"べんきょう",m:"學習",c:"名",ex:{j:"毎晩、日本語の勉強をします。",z:"我每天晚上學習日語。",e:"I study Japanese every night."}},
{w:"宿題",r:"しゅくだい",m:"作業",c:"名",ex:{j:"宿題はもう終わりました。",z:"作業已經寫完了。",e:"I have already finished my homework."}},
{w:"試験",r:"しけん",m:"考試",c:"名",ex:{j:"来週、数学の試験があります。",z:"下週有數學考試。",e:"There is a math exam next week."}},
{w:"テスト",r:"てすと",m:"測驗",c:"名",ex:{j:"明日のテストはむずかしいですか。",z:"明天的測驗難嗎?",e:"Is tomorrow's test difficult?"}},
{w:"問題",r:"もんだい",m:"問題",c:"名",ex:{j:"この問題はよくわかりません。",z:"這個問題我不太懂。",e:"I don't really understand this problem."}},
{w:"質問",r:"しつもん",m:"提問",c:"名",ex:{j:"先生に質問をしました。",z:"我向老師提問了。",e:"I asked the teacher a question."}},
{w:"答え",r:"こたえ",m:"答案",c:"名",ex:{j:"この問題の答えはこれです。",z:"這個問題的答案是這個。",e:"The answer to this problem is this."}},
{w:"授業",r:"じゅぎょう",m:"課程",c:"名",ex:{j:"授業は九時に始まります。",z:"課程九點開始。",e:"The class starts at nine o'clock."}},
{w:"練習",r:"れんしゅう",m:"練習",c:"名",ex:{j:"毎日ピアノの練習をします。",z:"我每天練習鋼琴。",e:"I practice the piano every day."}},
{w:"旅行",r:"りょこう",m:"旅行",c:"名",ex:{j:"夏に家族と旅行に行きます。",z:"夏天我要和家人去旅行。",e:"I'm going on a trip with my family in summer."}},
{w:"散歩",r:"さんぽ",m:"散步",c:"名",ex:{j:"朝、公園を散歩します。",z:"早上我在公園散步。",e:"I take a walk in the park in the morning."}},
{w:"買い物",r:"かいもの",m:"購物",c:"名",ex:{j:"母とスーパーで買い物をしました。",z:"我和媽媽在超市購物了。",e:"I went shopping at the supermarket with my mother."}},
{w:"映画",r:"えいが",m:"電影",c:"名",ex:{j:"週末に友だちと映画を見ます。",z:"週末我和朋友看電影。",e:"I watch a movie with my friend on the weekend."}},
{w:"音楽",r:"おんがく",m:"音樂",c:"名",ex:{j:"わたしは音楽を聞くのが好きです。",z:"我喜歡聽音樂。",e:"I like listening to music."}},
{w:"歌",r:"うた",m:"歌",c:"名",ex:{j:"彼女は歌がとても上手です。",z:"她歌唱得非常好。",e:"She is very good at singing."}},
{w:"スポーツ",r:"すぽーつ",m:"運動",c:"名",ex:{j:"わたしはスポーツがあまり好きではありません。",z:"我不太喜歡運動。",e:"I don't really like sports."}},
{w:"サッカー",r:"さっかー",m:"足球",c:"名",ex:{j:"日曜日に公園でサッカーをします。",z:"星期天我在公園踢足球。",e:"I play soccer in the park on Sundays."}},
{w:"テニス",r:"てにす",m:"網球",c:"名",ex:{j:"友だちと一緒にテニスをしました。",z:"我和朋友一起打了網球。",e:"I played tennis together with my friend."}},
{w:"水泳",r:"すいえい",m:"游泳",c:"名",ex:{j:"夏休みに毎日水泳をします。",z:"暑假我每天游泳。",e:"I swim every day during summer vacation."}},
{w:"ゲーム",r:"げーむ",m:"遊戲",c:"名",ex:{j:"弟は部屋でゲームをしています。",z:"弟弟在房間裡打電動。",e:"My little brother is playing games in his room."}},
{w:"パーティー",r:"ぱーてぃー",m:"派對",c:"名",ex:{j:"金曜日に友だちのパーティーへ行きます。",z:"星期五我要去朋友的派對。",e:"I'm going to my friend's party on Friday."}},
{w:"お祭り",r:"おまつり",m:"祭典",c:"名",ex:{j:"夏のお祭りはとてもにぎやかです。",z:"夏天的祭典非常熱鬧。",e:"The summer festival is very lively."}},
{w:"結婚式",r:"けっこんしき",m:"婚禮",c:"名",ex:{j:"来月、姉の結婚式があります。",z:"下個月有姊姊的婚禮。",e:"My older sister's wedding is next month."}},
// ── 言語・文化 ──
{w:"言葉",r:"ことば",m:"語言・詞",c:"名",ex:{j:"この言葉の読み方がわかりません。",z:"我不知道這個詞的讀法。",e:"I don't know how to read this word."}},
{w:"意味",r:"いみ",m:"意思",c:"名",ex:{j:"この漢字の意味を教えてください。",z:"請告訴我這個漢字的意思。",e:"Please tell me the meaning of this kanji."}},
{w:"漢字",r:"かんじ",m:"漢字",c:"名",ex:{j:"漢字を書くのは難しいです。",z:"寫漢字很難。",e:"Writing kanji is difficult."}},
{w:"文",r:"ぶん",m:"句子",c:"名",ex:{j:"先生と一緒にこの文を読みます。",z:"我和老師一起讀這個句子。",e:"I read this sentence together with the teacher."}},
{w:"日本語",r:"にほんご",m:"日語",c:"名",ex:{j:"わたしは毎日日本語を勉強しています。",z:"我每天都在學日語。",e:"I study Japanese every day."}},
{w:"英語",r:"えいご",m:"英語",c:"名",ex:{j:"父は英語が上手です。",z:"爸爸英語很好。",e:"My father is good at English."}},
{w:"外国語",r:"がいこくご",m:"外語",c:"名",ex:{j:"外国語が話せますか。",z:"你會說外語嗎?",e:"Can you speak a foreign language?"}},
// ── 抽象名詞・その他 ──
{w:"お金",r:"おかね",m:"錢",c:"名",ex:{j:"今日はお金を持っていません。",z:"我今天沒帶錢。",e:"I don't have any money today."}},
{w:"荷物",r:"にもつ",m:"行李",c:"名",ex:{j:"荷物が重くて大変です。",z:"行李很重,好辛苦。",e:"The luggage is heavy and it's tough."}},
{w:"お土産",r:"おみやげ",m:"伴手禮",c:"名",ex:{j:"京都でお土産を買いました。",z:"我在京都買了伴手禮。",e:"I bought souvenirs in Kyoto."}},
{w:"プレゼント",r:"ぷれぜんと",m:"禮物",c:"名",ex:{j:"母の日にプレゼントをあげます。",z:"母親節我要送禮物。",e:"I'll give a present on Mother's Day."}},
{w:"電話番号",r:"でんわばんごう",m:"電話號碼",c:"名",ex:{j:"あなたの電話番号を教えてください。",z:"請告訴我你的電話號碼。",e:"Please tell me your phone number."}},
{w:"住所",r:"じゅうしょ",m:"住址",c:"名",ex:{j:"ここに住所を書いてください。",z:"請在這裡寫上住址。",e:"Please write your address here."}},
{w:"地図",r:"ちず",m:"地圖",c:"名",ex:{j:"駅の前で地図を見ました。",z:"我在車站前看了地圖。",e:"I looked at the map in front of the station."}},
{w:"番号",r:"ばんごう",m:"號碼",c:"名",ex:{j:"わたしの席の番号は三番です。",z:"我座位的號碼是三號。",e:"My seat number is three."}},
{w:"色",r:"いろ",m:"顏色",c:"名",ex:{j:"この花の色はきれいですね。",z:"這朵花的顏色很漂亮呢。",e:"The color of this flower is beautiful."}},
{w:"赤",r:"あか",m:"紅色",c:"名",ex:{j:"信号が赤になりました。",z:"紅綠燈變紅了。",e:"The traffic light turned red."}},
{w:"青",r:"あお",m:"藍色",c:"名",ex:{j:"わたしは青が好きです。",z:"我喜歡藍色。",e:"I like the color blue."}},
{w:"白",r:"しろ",m:"白色",c:"名",ex:{j:"わたしのシャツは白です。",z:"我的襯衫是白色的。",e:"My shirt is white."}},
{w:"黒",r:"くろ",m:"黑色",c:"名",ex:{j:"わたしのかばんは黒です。",z:"我的包包是黑色的。",e:"My bag is black."}},
{w:"音",r:"おと",m:"聲音",c:"名",ex:{j:"となりの部屋から音が聞こえます。",z:"從隔壁房間傳來聲音。",e:"I can hear a sound from the next room."}},
{w:"話",r:"はなし",m:"話・故事",c:"名",ex:{j:"先生の話はおもしろかったです。",z:"老師的話很有趣。",e:"The teacher's talk was interesting."}},
{w:"心",r:"こころ",m:"心",c:"名",ex:{j:"友だちは心が優しい人です。",z:"朋友是心地善良的人。",e:"My friend is a kind-hearted person."}},
{w:"気",r:"き",m:"精神・氣",c:"名",ex:{j:"田中さんは気が優しい人です。",z:"田中先生是個心地善良的人。",e:"Mr. Tanaka is a kind-hearted person."}},
{w:"病気",r:"びょうき",m:"生病",c:"名",ex:{j:"きのうは病気で学校を休みました。",z:"昨天我因為生病沒去學校。",e:"I was absent from school yesterday because I was sick."}},
{w:"風邪",r:"かぜ",m:"感冒",c:"名",ex:{j:"風邪をひきました。",z:"我感冒了。",e:"I caught a cold."}},
{w:"薬",r:"くすり",m:"藥",c:"名",ex:{j:"食後に薬を飲みます。",z:"飯後吃藥。",e:"I take medicine after meals."}},
{w:"ページ",r:"ぺーじ",m:"頁",c:"名",ex:{j:"教科書の十ページを開いてください。",z:"請翻開課本第十頁。",e:"Please open the textbook to page ten."}},
{w:"クラス",r:"くらす",m:"班級",c:"名",ex:{j:"私のクラスは三十人います。",z:"我的班級有三十個人。",e:"There are thirty people in my class."}},
{w:"トイレ",r:"といれ",m:"廁所",c:"名",ex:{j:"トイレはどこですか。",z:"廁所在哪裡?",e:"Where is the toilet?"}},
{w:"シャワー",r:"しゃわー",m:"淋浴",c:"名",ex:{j:"毎朝シャワーを浴びます。",z:"我每天早上淋浴。",e:"I take a shower every morning."}},
{w:"お正月",r:"おしょうがつ",m:"新年",c:"名",ex:{j:"お正月に家族と会います。",z:"新年時和家人見面。",e:"I meet my family at New Year."}},
{w:"用事",r:"ようじ",m:"事情",c:"名",ex:{j:"今日は用事があります。",z:"我今天有事情。",e:"I have something to do today."}},
{w:"約束",r:"やくそく",m:"約定",c:"名",ex:{j:"友達と約束をしました。",z:"我和朋友約好了。",e:"I made a promise with my friend."}},
{w:"趣味",r:"しゅみ",m:"興趣",c:"名",ex:{j:"私の趣味は音楽です。",z:"我的興趣是音樂。",e:"My hobby is music."}},
{w:"世界",r:"せかい",m:"世界",c:"名",ex:{j:"世界には色々な国があります。",z:"世界上有各式各樣的國家。",e:"There are many countries in the world."}},
{w:"社会",r:"しゃかい",m:"社會",c:"名",ex:{j:"社会のニュースを見ます。",z:"我看社會新聞。",e:"I watch social news."}},
{w:"経済",r:"けいざい",m:"經濟",c:"名",ex:{j:"日本の経済を勉強しています。",z:"我正在學習日本的經濟。",e:"I am studying Japan's economy."}},
{w:"文化",r:"ぶんか",m:"文化",c:"名",ex:{j:"日本の文化が好きです。",z:"我喜歡日本的文化。",e:"I like Japanese culture."}},
{w:"歴史",r:"れきし",m:"歷史",c:"名",ex:{j:"歴史の本を読みます。",z:"我讀歷史書。",e:"I read history books."}},
{w:"ニュース",r:"にゅーす",m:"新聞",c:"名",ex:{j:"毎晩ニュースを見ます。",z:"我每天晚上看新聞。",e:"I watch the news every night."}},
// ── 数・助数詞 ──
{w:"一つ",r:"ひとつ",m:"一個",c:"名",ex:{j:"りんごを一つください。",z:"請給我一個蘋果。",e:"Please give me one apple."}},
{w:"二つ",r:"ふたつ",m:"兩個",c:"名",ex:{j:"みかんを二つ買いました。",z:"我買了兩個橘子。",e:"I bought two mandarin oranges."}},
{w:"三つ",r:"みっつ",m:"三個",c:"名",ex:{j:"箱が三つあります。",z:"有三個箱子。",e:"There are three boxes."}},
{w:"四つ",r:"よっつ",m:"四個",c:"名",ex:{j:"いすが四つ必要です。",z:"需要四把椅子。",e:"I need four chairs."}},
{w:"五つ",r:"いつつ",m:"五個",c:"名",ex:{j:"卵を五つ使います。",z:"我用五個蛋。",e:"I use five eggs."}},
{w:"六つ",r:"むっつ",m:"六個",c:"名",ex:{j:"お皿が六つあります。",z:"有六個盤子。",e:"There are six plates."}},
{w:"七つ",r:"ななつ",m:"七個",c:"名",ex:{j:"かばんの中に飴が七つあります。",z:"包包裡有七個糖果。",e:"There are seven candies in the bag."}},
{w:"八つ",r:"やっつ",m:"八個",c:"名",ex:{j:"クッキーを八つ焼きました。",z:"我烤了八個餅乾。",e:"I baked eight cookies."}},
{w:"九つ",r:"ここのつ",m:"九個",c:"名",ex:{j:"ボールが九つあります。",z:"有九個球。",e:"There are nine balls."}},
{w:"十",r:"とお",m:"十個",c:"名",ex:{j:"みかんが十あります。",z:"有十個橘子。",e:"There are ten mandarin oranges."}},
{w:"半分",r:"はんぶん",m:"一半",c:"名",ex:{j:"ケーキを半分食べました。",z:"我吃了一半的蛋糕。",e:"I ate half of the cake."}},
{w:"全部",r:"ぜんぶ",m:"全部",c:"名",ex:{j:"宿題を全部しました。",z:"我把作業全部做完了。",e:"I did all the homework."}},
// ── 国名 ──
{w:"日本",r:"にほん",m:"日本",c:"名",ex:{j:"私は日本に住んでいます。",z:"我住在日本。",e:"I live in Japan."}},
{w:"中国",r:"ちゅうごく",m:"中國",c:"名",ex:{j:"友達は中国から来ました。",z:"我朋友來自中國。",e:"My friend came from China."}},
{w:"韓国",r:"かんこく",m:"韓國",c:"名",ex:{j:"わたしは韓国のドラマが好きです。",z:"我喜歡韓國的連續劇。",e:"I like Korean dramas."}},
{w:"アメリカ",r:"あめりか",m:"美國",c:"名",ex:{j:"来月アメリカへ行きます。",z:"下個月要去美國。",e:"I'm going to America next month."}},
{w:"イギリス",r:"いぎりす",m:"英國",c:"名",ex:{j:"友だちはイギリスに住んでいます。",z:"朋友住在英國。",e:"My friend lives in England."}},
{w:"フランス",r:"ふらんす",m:"法國",c:"名",ex:{j:"フランスのパンはおいしいです。",z:"法國的麵包很好吃。",e:"French bread is delicious."}},
{w:"ドイツ",r:"どいつ",m:"德國",c:"名",ex:{j:"この車はドイツのです。",z:"這輛車是德國的。",e:"This car is from Germany."}},

// 動詞
// ── 一段動詞（る動詞）──
{w:"食べる",r:"たべる",m:"吃",c:"動",e:[{j:"朝ごはんを食べる。",z:"吃早餐。"},{j:"何が食べたいですか。",z:"想吃什麼？"}],t:"他",ex:{j:"朝ごはんはパンを食べます。",z:"早餐吃麵包。",e:"I eat bread for breakfast."}},
{w:"見る",r:"みる",m:"看",c:"動",e:[{j:"映画を見る。",z:"看電影。"},{j:"夢を見ました。",z:"做了夢。"}],t:"他",ex:{j:"きのう映画を見ました。",z:"昨天看了電影。",e:"I watched a movie yesterday."}},
{w:"起きる",r:"おきる",m:"起床",c:"動",t:"自",ex:{j:"毎朝六時に起きます。",z:"每天早上六點起床。",e:"I get up at six every morning."}},
{w:"寝る",r:"ねる",m:"睡覺",c:"動",t:"自",ex:{j:"きのうは早く寝ました。",z:"昨天很早就睡了。",e:"I went to bed early yesterday."}},
{w:"出る",r:"でる",m:"出去",c:"動",t:"自",ex:{j:"七時に家を出ます。",z:"七點出門(離開家)。",e:"I leave the house at seven."}},
{w:"入れる",r:"いれる",m:"放入",c:"動",t:"他",ex:{j:"コーヒーに砂糖を入れます。",z:"在咖啡裡放糖。",e:"I put sugar in my coffee."}},
{w:"出かける",r:"でかける",m:"出門",c:"動",t:"自",ex:{j:"母は買い物に出かけました。",z:"媽媽出門去買東西了。",e:"My mother went out to shop."}},
{w:"開ける",r:"あける",m:"打開",c:"動",t:"他",ex:{j:"暑いので窓を開けます。",z:"因為很熱,所以打開窗戶。",e:"It's hot, so I'll open the window."}},
{w:"閉める",r:"しめる",m:"關閉",c:"動",t:"他",ex:{j:"寒いですから、ドアを閉めてください。",z:"因為很冷,請把門關上。",e:"It's cold, so please close the door."}},
{w:"つける",r:"つける",m:"開(電器)",c:"動",t:"他",ex:{j:"暗いので電気をつけます。",z:"因為很暗,所以開燈。",e:"It's dark, so I'll turn on the light."}},
{w:"消す",r:"けす",m:"關・擦掉",c:"動",t:"他",ex:{j:"寝る前に電気を消します。",z:"睡前把燈關掉。",e:"I turn off the light before going to bed."}},
{w:"教える",r:"おしえる",m:"教・告訴",c:"動",t:"他",ex:{j:"先生は日本語を教えます。",z:"老師教日語。",e:"The teacher teaches Japanese."}},
{w:"覚える",r:"おぼえる",m:"記住",c:"動",t:"他",ex:{j:"新しい言葉を覚えました。",z:"記住了新的單字。",e:"I memorized a new word."}},
{w:"忘れる",r:"わすれる",m:"忘記",c:"動",t:"他",ex:{j:"かさを電車に忘れました。",z:"把傘忘在電車上了。",e:"I left my umbrella on the train."}},
{w:"見せる",r:"みせる",m:"給…看",c:"動",t:"他",ex:{j:"パスポートを見せてください。",z:"請出示護照給我看。",e:"Please show me your passport."}},
{w:"答える",r:"こたえる",m:"回答",c:"動",t:"両",ex:{j:"先生の質問に答えます。",z:"回答老師的問題。",e:"I answer the teacher's question."}},
{w:"借りる",r:"かりる",m:"借入",c:"動",t:"他",ex:{j:"図書館で本を借りました。",z:"在圖書館借了書。",e:"I borrowed a book from the library."}},
{w:"浴びる",r:"あびる",m:"淋",c:"動",t:"他",ex:{j:"毎朝シャワーを浴びます。",z:"每天早上淋浴。",e:"I take a shower every morning."}},
{w:"降りる",r:"おりる",m:"下(車)",c:"動",t:"自",ex:{j:"次の駅で電車を降ります。",z:"在下一站下車。",e:"I get off the train at the next station."}},
{w:"着る",r:"きる",m:"穿(上衣)",c:"動",t:"他",ex:{j:"寒いのでコートを着ます。",z:"因為很冷,所以穿上大衣。",e:"It's cold, so I put on a coat."}},
{w:"できる",r:"できる",m:"能・會",c:"動",t:"自",ex:{j:"わたしは日本語が少しできます。",z:"我會一點日語。",e:"I can speak a little Japanese."}},
{w:"いる",r:"いる",m:"在(生物)",c:"動",t:"自",ex:{j:"部屋に猫がいます。",z:"房間裡有一隻貓。",e:"There is a cat in the room."}},
{w:"掛ける",r:"かける",m:"打(電話)",c:"動",t:"他",ex:{j:"あとで電話を掛けます。",z:"待會兒打電話。",e:"I'll make a phone call later."}},
{w:"疲れる",r:"つかれる",m:"累",c:"動",t:"自",ex:{j:"今日はとても疲れました。",z:"今天非常累。",e:"I'm very tired today."}},
{w:"止める",r:"とめる",m:"停止",c:"動",t:"他",ex:{j:"ここに車を止めてください。",z:"請把車停在這裡。",e:"Please stop the car here."}},
{w:"並べる",r:"ならべる",m:"排列",c:"動",t:"他",ex:{j:"机の上に本を並べます。",z:"把書排列在桌上。",e:"I line up the books on the desk."}},
{w:"始める",r:"はじめる",m:"開始",c:"動",t:"他",ex:{j:"九時に授業を始めます。",z:"九點開始上課。",e:"We start the class at nine o'clock."}},
{w:"生まれる",r:"うまれる",m:"出生",c:"動",t:"自",ex:{j:"私は東京で生まれました。",z:"我在東京出生。",e:"I was born in Tokyo."}},
{w:"考える",r:"かんがえる",m:"思考",c:"動",t:"他",ex:{j:"答えをよく考えてください。",z:"請好好思考答案。",e:"Please think carefully about the answer."}},
// ── 五段動詞（う動詞）──
{w:"行く",r:"いく",m:"去",c:"動",e:[{j:"明日学校へ行きます。",z:"明天去學校。"},{j:"一緒に行こう。",z:"一起去吧。"}],t:"自",ex:{j:"明日、友だちと海へ行きます。",z:"明天要和朋友去海邊。",e:"Tomorrow I will go to the sea with my friend."}},
{w:"来る",r:"くる",m:"來",c:"動",t:"自",ex:{j:"母が家に来ました。",z:"媽媽來家裡了。",e:"My mother came to the house."}},
{w:"帰る",r:"かえる",m:"回去",c:"動",t:"自",ex:{j:"六時に家へ帰ります。",z:"六點回家。",e:"I go home at six o'clock."}},
{w:"ある",r:"ある",m:"在(非生物)",c:"動",t:"自",ex:{j:"机の上に本があります。",z:"桌上有書。",e:"There is a book on the desk."}},
{w:"する",r:"する",m:"做",c:"動",t:"他",ex:{j:"日曜日に掃除をします。",z:"星期天做打掃。",e:"I do the cleaning on Sunday."}},
{w:"なる",r:"なる",m:"變成",c:"動",t:"自",ex:{j:"弟は医者になりました。",z:"弟弟成為醫生了。",e:"My younger brother became a doctor."}},
{w:"言う",r:"いう",m:"說",c:"動",t:"他",ex:{j:"先生に「ありがとう」と言いました。",z:"我對老師說了「謝謝」。",e:"I said \"thank you\" to the teacher."}},
{w:"聞く",r:"きく",m:"聽・問",c:"動",t:"他",ex:{j:"毎朝、音楽を聞きます。",z:"每天早上聽音樂。",e:"I listen to music every morning."}},
{w:"話す",r:"はなす",m:"說話",c:"動",t:"両",ex:{j:"友だちと日本語で話します。",z:"和朋友用日語說話。",e:"I talk with my friend in Japanese."}},
{w:"読む",r:"よむ",m:"讀",c:"動",t:"他",ex:{j:"夜、新聞を読みます。",z:"晚上讀報紙。",e:"I read the newspaper at night."}},
{w:"書く",r:"かく",m:"寫",c:"動",t:"他",ex:{j:"ノートに名前を書いてください。",z:"請在筆記本上寫名字。",e:"Please write your name in the notebook."}},
{w:"飲む",r:"のむ",m:"喝",c:"動",e:[{j:"水を飲む。",z:"喝水。"},{j:"薬を飲んでください。",z:"請吃藥。"}],t:"他",ex:{j:"朝、コーヒーを飲みます。",z:"早上喝咖啡。",e:"I drink coffee in the morning."}},
{w:"買う",r:"かう",m:"買",c:"動",t:"他",ex:{j:"スーパーで野菜を買います。",z:"在超市買蔬菜。",e:"I buy vegetables at the supermarket."}},
{w:"売る",r:"うる",m:"賣",c:"動",t:"他",ex:{j:"あの店はパンを売っています。",z:"那家店在賣麵包。",e:"That shop sells bread."}},
{w:"待つ",r:"まつ",m:"等",c:"動",t:"他",ex:{j:"駅で友だちを待ちます。",z:"在車站等朋友。",e:"I wait for my friend at the station."}},
{w:"立つ",r:"たつ",m:"站",c:"動",t:"自",ex:{j:"椅子から立ちます。",z:"從椅子上站起來。",e:"I stand up from the chair."}},
{w:"座る",r:"すわる",m:"坐",c:"動",t:"自",ex:{j:"どうぞ、ここに座ってください。",z:"請坐這裡。",e:"Please sit here."}},
{w:"入る",r:"はいる",m:"進入",c:"動",t:"自",ex:{j:"教室に入ります。",z:"進入教室。",e:"I enter the classroom."}},
{w:"乗る",r:"のる",m:"搭乘",c:"動",t:"自",ex:{j:"毎日、電車に乗ります。",z:"每天搭電車。",e:"I ride the train every day."}},
{w:"走る",r:"はしる",m:"跑",c:"動",t:"自",ex:{j:"公園を毎朝走ります。",z:"每天早上在公園跑步。",e:"I run in the park every morning."}},
{w:"歩く",r:"あるく",m:"走路",c:"動",t:"自",ex:{j:"駅まで歩きます。",z:"走路到車站。",e:"I walk to the station."}},
{w:"泳ぐ",r:"およぐ",m:"游泳",c:"動",t:"自",ex:{j:"夏は海で泳ぎます。",z:"夏天在海裡游泳。",e:"In summer I swim in the sea."}},
{w:"遊ぶ",r:"あそぶ",m:"玩",c:"動",t:"自",ex:{j:"公園で子どもと遊びます。",z:"在公園和小孩玩。",e:"I play with the children in the park."}},
{w:"使う",r:"つかう",m:"使用",c:"動",t:"他",ex:{j:"この部屋でパソコンを使います。",z:"在這個房間使用電腦。",e:"I use the computer in this room."}},
{w:"作る",r:"つくる",m:"做・製作",c:"動",t:"他",ex:{j:"母は毎日ご飯を作ります。",z:"媽媽每天做飯。",e:"My mother makes meals every day."}},
{w:"持つ",r:"もつ",m:"拿・擁有",c:"動",t:"他",ex:{j:"かばんを持って、出かけます。",z:"拿著包包出門。",e:"I take my bag and go out."}},
{w:"置く",r:"おく",m:"放置",c:"動",t:"他",ex:{j:"かばんはそこに置いてください。",z:"請把包包放在那裡。",e:"Please put your bag over there."}},
{w:"送る",r:"おくる",m:"送",c:"動",t:"他",ex:{j:"友だちにメールを送りました。",z:"我寄了電子郵件給朋友。",e:"I sent an email to my friend."}},
{w:"返す",r:"かえす",m:"歸還",c:"動",t:"他",ex:{j:"あした本を返します。",z:"我明天會歸還書。",e:"I'll return the book tomorrow."}},
{w:"貸す",r:"かす",m:"借出",c:"動",t:"他",ex:{j:"ペンを貸してください。",z:"請借我一支筆。",e:"Please lend me a pen."}},
{w:"押す",r:"おす",m:"推・按",c:"動",t:"他",ex:{j:"このボタンを押してください。",z:"請按這個按鈕。",e:"Please press this button."}},
{w:"引く",r:"ひく",m:"拉・彈",c:"動",t:"他",ex:{j:"このドアは引いて開けます。",z:"這扇門要拉開。",e:"You open this door by pulling it."}},
{w:"切る",r:"きる",m:"切",c:"動",t:"他",ex:{j:"ナイフでパンを切ります。",z:"用刀子切麵包。",e:"I cut the bread with a knife."}},
{w:"撮る",r:"とる",m:"拍(照)",c:"動",t:"他",ex:{j:"公園で写真を撮りました。",z:"我在公園拍了照片。",e:"I took photos at the park."}},
{w:"取る",r:"とる",m:"拿取",c:"動",t:"他",ex:{j:"その塩を取ってください。",z:"請把那個鹽拿給我。",e:"Please pass me that salt."}},
{w:"吸う",r:"すう",m:"吸",c:"動",t:"他",ex:{j:"ここでたばこを吸わないでください。",z:"請不要在這裡抽菸。",e:"Please don't smoke here."}},
{w:"洗う",r:"あらう",m:"洗",c:"動",t:"他",ex:{j:"ごはんの前に手を洗います。",z:"吃飯前洗手。",e:"I wash my hands before meals."}},
{w:"磨く",r:"みがく",m:"刷(牙)",c:"動",t:"他",ex:{j:"毎朝、歯を磨きます。",z:"每天早上刷牙。",e:"I brush my teeth every morning."}},
{w:"渡す",r:"わたす",m:"交給",c:"動",t:"他",ex:{j:"先生にレポートを渡しました。",z:"我把報告交給老師了。",e:"I handed the report to the teacher."}},
{w:"渡る",r:"わたる",m:"過(橋)",c:"動",t:"自",ex:{j:"あの橋を渡ってください。",z:"請過那座橋。",e:"Please cross that bridge."}},
{w:"曲がる",r:"まがる",m:"轉彎",c:"動",t:"自",ex:{j:"次の角を右に曲がってください。",z:"請在下一個轉角向右轉。",e:"Please turn right at the next corner."}},
{w:"止まる",r:"とまる",m:"停下",c:"動",t:"自",ex:{j:"バスがえきの前に止まりました。",z:"公車停在車站前面了。",e:"The bus stopped in front of the station."}},
{w:"動く",r:"うごく",m:"動",c:"動",t:"自",ex:{j:"この時計は動きません。",z:"這個時鐘不動了。",e:"This clock doesn't work."}},
{w:"開く",r:"あく",m:"開(自動)",c:"動",t:"自",ex:{j:"ドアが自動で開きます。",z:"門會自動打開。",e:"The door opens automatically."}},
{w:"閉まる",r:"しまる",m:"關(自動)",c:"動",t:"自",ex:{j:"店は九時に閉まります。",z:"店在九點關門。",e:"The store closes at nine."}},
{w:"付く",r:"つく",m:"亮(自動)",c:"動",t:"自",ex:{j:"部屋の電気が付きました。",z:"房間的燈亮了。",e:"The light in the room came on."}},
{w:"消える",r:"きえる",m:"消失",c:"動",t:"自",ex:{j:"電気が消えて、へやが暗くなりました。",z:"燈熄了，房間變暗了。",e:"The light went out and the room got dark."}},
{w:"掛かる",r:"かかる",m:"花(時間)",c:"動",t:"自",ex:{j:"駅まで三十分かかります。",z:"到車站要花三十分鐘。",e:"It takes thirty minutes to the station."}},
{w:"始まる",r:"はじまる",m:"開始(自)",c:"動",t:"自",ex:{j:"授業は九時に始まります。",z:"課程在九點開始。",e:"Class starts at nine."}},
{w:"終わる",r:"おわる",m:"結束",c:"動",t:"自",ex:{j:"仕事は五時に終わります。",z:"工作在五點結束。",e:"Work finishes at five."}},
{w:"住む",r:"すむ",m:"住",c:"動",t:"自",ex:{j:"わたしは東京に住んでいます。",z:"我住在東京。",e:"I live in Tokyo."}},
{w:"働く",r:"はたらく",m:"工作",c:"動",t:"自",ex:{j:"父は銀行で働いています。",z:"我爸爸在銀行工作。",e:"My father works at a bank."}},
{w:"休む",r:"やすむ",m:"休息",c:"動",t:"自",ex:{j:"きのうは会社を休みました。",z:"我昨天向公司請假了。",e:"I took the day off work yesterday."}},
{w:"出す",r:"だす",m:"拿出",c:"動",t:"他",ex:{j:"かばんから本を出しました。",z:"我從包包裡拿出了書。",e:"I took a book out of my bag."}},
{w:"届く",r:"とどく",m:"送達",c:"動",t:"自",ex:{j:"きのう荷物が届きました。",z:"包裹昨天送到了。",e:"The package arrived yesterday."}},
{w:"習う",r:"ならう",m:"學習",c:"動",t:"他",ex:{j:"わたしは日本語を習っています。",z:"我正在學日語。",e:"I'm learning Japanese."}},
{w:"会う",r:"あう",m:"見面",c:"動",t:"自",ex:{j:"明日、駅で友だちに会います。",z:"明天在車站跟朋友見面。",e:"I'm meeting a friend at the station tomorrow."}},
{w:"歌う",r:"うたう",m:"唱歌",c:"動",t:"他",ex:{j:"わたしはカラオケで日本の歌を歌います。",z:"我在卡拉OK唱日本歌。",e:"I sing Japanese songs at karaoke."}},
{w:"弾く",r:"ひく",m:"彈(琴)",c:"動",t:"他",ex:{j:"姉は毎日ピアノを弾きます。",z:"姊姊每天彈鋼琴。",e:"My older sister plays the piano every day."}},
{w:"吹く",r:"ふく",m:"吹",c:"動",t:"両",ex:{j:"今日は風が強く吹いています。",z:"今天風吹得很強。",e:"The wind is blowing hard today."}},
{w:"降る",r:"ふる",m:"下(雨雪)",c:"動",t:"自",ex:{j:"朝から雨がたくさん降っています。",z:"從早上開始下了很多雨。",e:"It has been raining a lot since morning."}},
{w:"飛ぶ",r:"とぶ",m:"飛",c:"動",t:"自",ex:{j:"空を鳥が飛んでいます。",z:"鳥在天空中飛。",e:"A bird is flying in the sky."}},
{w:"死ぬ",r:"しぬ",m:"死",c:"動",t:"自",ex:{j:"魚が水がなくて死にました。",z:"魚因為沒有水死掉了。",e:"The fish died because there was no water."}},
{w:"要る",r:"いる",m:"需要",c:"動",t:"自",ex:{j:"この仕事にはお金がたくさん要ります。",z:"這份工作需要很多錢。",e:"This job requires a lot of money."}},
{w:"知る",r:"しる",m:"知道",c:"動",t:"他",ex:{j:"あの人の名前を知っていますか。",z:"你知道那個人的名字嗎?",e:"Do you know that person's name?"}},
{w:"分かる",r:"わかる",m:"明白",c:"動",t:"自",ex:{j:"先生の説明がよく分かりました。",z:"老師的說明我很清楚地明白了。",e:"I understood the teacher's explanation well."}},
{w:"思う",r:"おもう",m:"想・認為",c:"動",t:"他",ex:{j:"明日は晴れると思います。",z:"我覺得明天會放晴。",e:"I think it will be sunny tomorrow."}},
{w:"困る",r:"こまる",m:"困擾",c:"動",t:"自",ex:{j:"お金がなくて、とても困っています。",z:"因為沒有錢,非常困擾。",e:"I have no money and I'm really in trouble."}},
{w:"頼む",r:"たのむ",m:"拜託",c:"動",t:"他",ex:{j:"友だちに買い物を頼みました。",z:"我拜託朋友幫忙買東西。",e:"I asked my friend to do the shopping for me."}},
{w:"呼ぶ",r:"よぶ",m:"叫",c:"動",t:"他",ex:{j:"母がわたしの名前を呼びました。",z:"媽媽叫了我的名字。",e:"My mother called my name."}},
{w:"笑う",r:"わらう",m:"笑",c:"動",t:"自",ex:{j:"みんなが楽しそうに笑っています。",z:"大家都開心地笑著。",e:"Everyone is laughing happily."}},
{w:"泣く",r:"なく",m:"哭",c:"動",t:"自",ex:{j:"赤ちゃんが大きな声で泣いています。",z:"嬰兒大聲地哭著。",e:"The baby is crying loudly."}},
{w:"怒る",r:"おこる",m:"生氣",c:"動",t:"両",ex:{j:"父はときどき大きな声で怒ります。",z:"爸爸有時會大聲生氣。",e:"My father sometimes gets angry in a loud voice."}},
{w:"違う",r:"ちがう",m:"不同",c:"動",t:"自",ex:{j:"わたしの答えは先生のと違います。",z:"我的答案和老師的不一樣。",e:"My answer is different from the teacher's."}},
{w:"並ぶ",r:"ならぶ",m:"排隊",c:"動",t:"自",ex:{j:"みんな駅の前に並んでいます。",z:"大家在車站前排隊。",e:"Everyone is lining up in front of the station."}},
{w:"登る",r:"のぼる",m:"爬(山)",c:"動",t:"自",ex:{j:"夏休みに富士山に登りました。",z:"暑假時爬了富士山。",e:"I climbed Mt. Fuji during summer vacation."}},
{w:"脱ぐ",r:"ぬぐ",m:"脫",c:"動",t:"他",ex:{j:"家に入るとき、くつを脱ぎます。",z:"進家門的時候要脫鞋。",e:"You take off your shoes when you enter the house."}},
{w:"履く",r:"はく",m:"穿(下半)",c:"動",t:"他",ex:{j:"公園でスニーカーを履いて走ります。",z:"在公園穿著運動鞋跑步。",e:"I put on sneakers and run in the park."}},
{w:"被る",r:"かぶる",m:"戴(帽子)",c:"動",t:"他",ex:{j:"暑いので、帽子を被って出かけます。",z:"因為很熱,所以戴帽子出門。",e:"It's hot, so I put on a hat before going out."}},
{w:"もらう",r:"もらう",m:"收到",c:"動",t:"他",ex:{j:"誕生日に父から時計をもらいました。",z:"生日時收到爸爸送的手錶。",e:"I received a watch from my father for my birthday."}},
{w:"あげる",r:"あげる",m:"給",c:"動",t:"他",ex:{j:"わたしは妹に本をあげました。",z:"我給了妹妹一本書。",e:"I gave my younger sister a book."}},
{w:"くれる",r:"くれる",m:"(對方)給我",c:"動",t:"他",ex:{j:"友だちがわたしにおみやげをくれました。",z:"朋友給了我伴手禮。",e:"My friend gave me a souvenir."}},
{w:"なくす",r:"なくす",m:"弄丟",c:"動",t:"他",ex:{j:"電車の中でさいふをなくしました。",z:"我在電車裡把錢包弄丟了。",e:"I lost my wallet on the train."}},
// ── 複合・特殊 ──
{w:"勉強する",r:"べんきょうする",m:"學習",c:"動",t:"他",ex:{j:"毎晩、日本語を勉強します。",z:"每天晚上學習日語。",e:"I study Japanese every night."}},
{w:"散歩する",r:"さんぽする",m:"散步",c:"動",t:"自",ex:{j:"朝、公園を散歩するのが好きです。",z:"我喜歡早上在公園散步。",e:"I like taking a walk in the park in the morning."}},
{w:"旅行する",r:"りょこうする",m:"旅行",c:"動",t:"自",ex:{j:"来月、家族と京都へ旅行します。",z:"下個月要和家人去京都旅行。",e:"Next month I will travel to Kyoto with my family."}},
{w:"買い物する",r:"かいものする",m:"購物",c:"動",t:"自",ex:{j:"きのう デパートで 買い物しました。",z:"昨天在百貨公司購物了。",e:"I went shopping at the department store yesterday."}},
{w:"料理する",r:"りょうりする",m:"做菜",c:"動",t:"他",ex:{j:"母は まいにち 料理します。",z:"媽媽每天做菜。",e:"My mother cooks every day."}},
{w:"洗濯する",r:"せんたくする",m:"洗衣服",c:"動",t:"他",ex:{j:"日曜日に シャツを 洗濯します。",z:"星期天洗襯衫。",e:"I do the laundry (wash shirts) on Sunday."}},
{w:"掃除する",r:"そうじする",m:"打掃",c:"動",t:"他",ex:{j:"へやを きれいに 掃除しました。",z:"把房間打掃乾淨了。",e:"I cleaned the room until it was tidy."}},
{w:"電話する",r:"でんわする",m:"打電話",c:"動",t:"自",ex:{j:"あとで 友だちに 電話します。",z:"待會兒要打電話給朋友。",e:"I'll call my friend later."}},
{w:"結婚する",r:"けっこんする",m:"結婚",c:"動",t:"自",ex:{j:"あねは きょねん 結婚しました。",z:"姊姊去年結婚了。",e:"My older sister got married last year."}},
{w:"練習する",r:"れんしゅうする",m:"練習",c:"動",t:"他",ex:{j:"まいにち 日本語を 練習しています。",z:"每天都在練習日語。",e:"I practice Japanese every day."}},
{w:"コピーする",r:"こぴーする",m:"複印",c:"動",t:"他",ex:{j:"この 書類を コピーしてください。",z:"請影印這份文件。",e:"Please make a copy of this document."}},
{w:"運動する",r:"うんどうする",m:"運動",c:"動",t:"自",ex:{j:"わたしは まいあさ 運動します。",z:"我每天早上都運動。",e:"I exercise every morning."}},
{w:"心配する",r:"しんぱいする",m:"擔心",c:"動",t:"他",ex:{j:"だいじょうぶですから、心配しないでください。",z:"沒問題的,請不要擔心。",e:"It's all right, so please don't worry."}},
{w:"食事する",r:"しょくじする",m:"用餐",c:"動",t:"自",ex:{j:"かぞくと いっしょに 食事します。",z:"和家人一起用餐。",e:"I have a meal together with my family."}},
{w:"準備する",r:"じゅんびする",m:"準備",c:"動",t:"他",ex:{j:"あしたの テストの じゅんびを しています。",z:"正在準備明天的考試。",e:"I'm getting ready for tomorrow's test."}},
{w:"紹介する",r:"しょうかいする",m:"介紹",c:"動",t:"他",ex:{j:"友だちを みんなに 紹介しました。",z:"把朋友介紹給大家了。",e:"I introduced my friend to everyone."}},

// い形容詞
{w:"大きい",r:"おおきい",m:"大的",c:"い形",ex:{j:"この かばんは とても 大きいです。",z:"這個包包很大。",e:"This bag is very big."}},
{w:"小さい",r:"ちいさい",m:"小的",c:"い形",ex:{j:"うちの ねこは まだ 小さいです。",z:"我家的貓還很小。",e:"My cat is still small."}},
{w:"高い",r:"たかい",m:"高的・貴的",c:"い形",ex:{j:"この とけいは 高いです。",z:"這支手錶很貴。",e:"This watch is expensive."}},
{w:"安い",r:"やすい",m:"便宜的",c:"い形",ex:{j:"この みせは やさいが 安いです。",z:"這家店的蔬菜很便宜。",e:"The vegetables at this store are cheap."}},
{w:"低い",r:"ひくい",m:"低的",c:"い形",ex:{j:"この つくえは すこし 低いです。",z:"這張桌子有點低。",e:"This desk is a little low."}},
{w:"新しい",r:"あたらしい",m:"新的",c:"い形",ex:{j:"新しい くつを 買いました。",z:"買了新鞋子。",e:"I bought new shoes."}},
{w:"古い",r:"ふるい",m:"舊的",c:"い形",ex:{j:"この ビルは とても 古いです。",z:"這棟大樓很舊。",e:"This building is very old."}},
{w:"良い",r:"いい",m:"好的",c:"い形",ex:{j:"きょうは てんきが 良いです。",z:"今天天氣很好。",e:"The weather is good today."}},
{w:"悪い",r:"わるい",m:"壞的",c:"い形",ex:{j:"きのうは たいちょうが 悪かったです。",z:"昨天身體狀況很差。",e:"I was in bad shape yesterday."}},
{w:"多い",r:"おおい",m:"多的",c:"い形",ex:{j:"この まちは 人が 多いです。",z:"這座城市人很多。",e:"There are a lot of people in this town."}},
{w:"少ない",r:"すくない",m:"少的",c:"い形",ex:{j:"きょうは しゅくだいが 少ないです。",z:"今天作業很少。",e:"There is little homework today."}},
{w:"長い",r:"ながい",m:"長的",c:"い形",ex:{j:"この かわは とても 長いです。",z:"這條河很長。",e:"This river is very long."}},
{w:"短い",r:"みじかい",m:"短的",c:"い形",ex:{j:"この えんぴつは 短いです。",z:"這支鉛筆很短。",e:"This pencil is short."}},
{w:"広い",r:"ひろい",m:"寬廣的",c:"い形",ex:{j:"この こうえんは 広いです。",z:"這座公園很寬廣。",e:"This park is spacious."}},
{w:"狭い",r:"せまい",m:"狹窄的",c:"い形",ex:{j:"わたしの へやは 狭いです。",z:"我的房間很狹小。",e:"My room is small (cramped)."}},
{w:"重い",r:"おもい",m:"重的",c:"い形",ex:{j:"この にもつは 重いです。",z:"這件行李很重。",e:"This luggage is heavy."}},
{w:"軽い",r:"かるい",m:"輕的",c:"い形",ex:{j:"この パソコンは 軽いです。",z:"這台筆電很輕。",e:"This laptop is light."}},
{w:"太い",r:"ふとい",m:"粗的",c:"い形",ex:{j:"この木はとても太いです。",z:"這棵樹很粗。",e:"This tree is very thick."}},
{w:"細い",r:"ほそい",m:"細的",c:"い形",ex:{j:"彼女の指は細いです。",z:"她的手指很細。",e:"Her fingers are thin."}},
{w:"近い",r:"ちかい",m:"近的",c:"い形",ex:{j:"駅は家から近いです。",z:"車站離家很近。",e:"The station is close to my house."}},
{w:"遠い",r:"とおい",m:"遠的",c:"い形",ex:{j:"学校は少し遠いです。",z:"學校有點遠。",e:"The school is a little far."}},
{w:"速い",r:"はやい",m:"快的",c:"い形",ex:{j:"この電車はとても速いです。",z:"這輛電車非常快。",e:"This train is very fast."}},
{w:"遅い",r:"おそい",m:"慢的・晚的",c:"い形",ex:{j:"このバスはいつも遅いです。",z:"這輛公車總是很慢。",e:"This bus is always slow."}},
{w:"早い",r:"はやい",m:"早的",c:"い形",ex:{j:"今日は朝が早いです。",z:"今天早上很早。",e:"This morning is early."}},
{w:"強い",r:"つよい",m:"強的",c:"い形",ex:{j:"今日は風が強いです。",z:"今天風很強。",e:"The wind is strong today."}},
{w:"弱い",r:"よわい",m:"弱的",c:"い形",ex:{j:"私はお酒に弱いです。",z:"我不太會喝酒(酒量弱)。",e:"I have a weak tolerance for alcohol."}},
{w:"暑い",r:"あつい",m:"(天氣)熱",c:"い形",ex:{j:"夏はとても暑いです。",z:"夏天非常熱。",e:"Summer is very hot."}},
{w:"熱い",r:"あつい",m:"(物體)燙",c:"い形",ex:{j:"このお茶は熱いです。",z:"這杯茶很燙。",e:"This tea is hot."}},
{w:"寒い",r:"さむい",m:"(天氣)冷",c:"い形",ex:{j:"今日は寒いですね。",z:"今天很冷呢。",e:"It's cold today, isn't it?"}},
{w:"冷たい",r:"つめたい",m:"(物體)冰",c:"い形",ex:{j:"この水は冷たいです。",z:"這水很冰。",e:"This water is cold."}},
{w:"暖かい",r:"あたたかい",m:"溫暖的",c:"い形",ex:{j:"春は暖かいです。",z:"春天很溫暖。",e:"Spring is warm."}},
{w:"涼しい",r:"すずしい",m:"涼爽的",c:"い形",ex:{j:"秋の風は涼しいです。",z:"秋天的風很涼爽。",e:"The autumn breeze is cool."}},
{w:"甘い",r:"あまい",m:"甜的",c:"い形",ex:{j:"このケーキは甘いです。",z:"這個蛋糕很甜。",e:"This cake is sweet."}},
{w:"辛い",r:"からい",m:"辣的",c:"い形",ex:{j:"このカレーは辛いです。",z:"這咖哩很辣。",e:"This curry is spicy."}},
{w:"美味しい",r:"おいしい",m:"好吃的",c:"い形",ex:{j:"このラーメンは美味しいです。",z:"這碗拉麵很好吃。",e:"This ramen is delicious."}},
{w:"不味い",r:"まずい",m:"難吃的",c:"い形",ex:{j:"この料理は不味いです。",z:"這道菜很難吃。",e:"This dish tastes bad."}},
{w:"忙しい",r:"いそがしい",m:"忙的",c:"い形",ex:{j:"今週はとても忙しいです。",z:"這週非常忙。",e:"I'm very busy this week."}},
{w:"楽しい",r:"たのしい",m:"快樂的",c:"い形",ex:{j:"パーティーはとても楽しいです。",z:"派對非常好玩。",e:"The party is a lot of fun."}},
{w:"嬉しい",r:"うれしい",m:"高興的",c:"い形",ex:{j:"プレゼントをもらって嬉しいです。",z:"收到禮物很高興。",e:"I'm happy to receive a present."}},
{w:"悲しい",r:"かなしい",m:"悲傷的",c:"い形",ex:{j:"その映画はとても悲しいです。",z:"那部電影非常悲傷。",e:"That movie is very sad."}},
{w:"寂しい",r:"さびしい",m:"寂寞的",c:"い形",ex:{j:"一人の夜は寂しいです。",z:"一個人的夜晚很寂寞。",e:"The nights alone are lonely."}},
{w:"怖い",r:"こわい",m:"可怕的",c:"い形",ex:{j:"この犬は少し怖いです。",z:"這隻狗有點可怕。",e:"This dog is a little scary."}},
{w:"痛い",r:"いたい",m:"痛的",c:"い形",ex:{j:"頭が痛いです。",z:"我頭痛。",e:"My head hurts."}},
{w:"面白い",r:"おもしろい",m:"有趣的",c:"い形",ex:{j:"この本はとても面白いです。",z:"這本書非常有趣。",e:"This book is very interesting."}},
{w:"つまらない",r:"つまらない",m:"無聊的",c:"い形",ex:{j:"この番組はつまらないです。",z:"這個節目很無聊。",e:"This show is boring."}},
{w:"難しい",r:"むずかしい",m:"難的",c:"い形",ex:{j:"この問題は難しいです。",z:"這個問題很難。",e:"This question is difficult."}},
{w:"易しい",r:"やさしい",m:"簡單的",c:"い形",ex:{j:"このテストは易しいです。",z:"這個測驗很簡單。",e:"This test is easy."}},
{w:"優しい",r:"やさしい",m:"溫柔的",c:"い形",ex:{j:"田中さんはとても優しい人です。",z:"田中先生是很溫柔的人。",e:"Mr. Tanaka is a very kind person."}},
{w:"厳しい",r:"きびしい",m:"嚴格的",c:"い形",ex:{j:"あの先生はとても厳しいです。",z:"那位老師非常嚴格。",e:"That teacher is very strict."}},
{w:"明るい",r:"あかるい",m:"明亮的",c:"い形",ex:{j:"この部屋は明るくて気持ちがいいです。",z:"這個房間很明亮，感覺很舒服。",e:"This room is bright and feels nice."}},
{w:"暗い",r:"くらい",m:"暗的",c:"い形",ex:{j:"外はもう暗いですね。",z:"外面已經暗了呢。",e:"It's already dark outside."}},
{w:"白い",r:"しろい",m:"白色的",c:"い形",ex:{j:"白いシャツを買いました。",z:"我買了白色的襯衫。",e:"I bought a white shirt."}},
{w:"黒い",r:"くろい",m:"黑色的",c:"い形",ex:{j:"あの黒い犬はかわいいです。",z:"那隻黑色的狗很可愛。",e:"That black dog is cute."}},
{w:"赤い",r:"あかい",m:"紅色的",c:"い形",ex:{j:"赤いりんごを三つ食べました。",z:"我吃了三顆紅蘋果。",e:"I ate three red apples."}},
{w:"青い",r:"あおい",m:"藍色的",c:"い形",ex:{j:"今日は空が青いです。",z:"今天天空很藍。",e:"The sky is blue today."}},
{w:"黄色い",r:"きいろい",m:"黃色的",c:"い形",ex:{j:"黄色い花がきれいですね。",z:"黃色的花好漂亮呢。",e:"The yellow flowers are pretty."}},
{w:"丸い",r:"まるい",m:"圓的",c:"い形",ex:{j:"テーブルは丸い形です。",z:"桌子是圓形的。",e:"The table is round."}},
{w:"四角い",r:"しかくい",m:"方形的",c:"い形",ex:{j:"四角い箱にお菓子を入れました。",z:"我把點心放進方形的盒子裡。",e:"I put the sweets in a square box."}},
{w:"若い",r:"わかい",m:"年輕的",c:"い形",ex:{j:"あの歌手はまだとても若いです。",z:"那位歌手還很年輕。",e:"That singer is still very young."}},
{w:"欲しい",r:"ほしい",m:"想要的",c:"い形",ex:{j:"新しいかばんが欲しいです。",z:"我想要一個新包包。",e:"I want a new bag."}},
{w:"眠い",r:"ねむい",m:"睏的",c:"い形",ex:{j:"昨日あまり寝なかったので、眠いです。",z:"昨天睡得不多，所以很睏。",e:"I didn't sleep much yesterday, so I'm sleepy."}},
{w:"うるさい",r:"うるさい",m:"吵的",c:"い形",ex:{j:"外がうるさくて勉強できません。",z:"外面很吵，沒辦法讀書。",e:"It's noisy outside, so I can't study."}},
{w:"汚い",r:"きたない",m:"髒的",c:"い形",ex:{j:"この部屋は汚いですから、掃除します。",z:"這個房間很髒，所以我要打掃。",e:"This room is dirty, so I'll clean it."}},
{w:"危ない",r:"あぶない",m:"危險的",c:"い形",ex:{j:"ここは危ないですから、気をつけてください。",z:"這裡很危險，請小心。",e:"It's dangerous here, so please be careful."}},
{w:"珍しい",r:"めずらしい",m:"稀奇的",c:"い形",ex:{j:"これは珍しい切手です。",z:"這是很稀奇的郵票。",e:"This is a rare stamp."}},
{w:"可愛い",r:"かわいい",m:"可愛的",c:"い形",ex:{j:"妹の猫はとても可愛いです。",z:"妹妹的貓非常可愛。",e:"My little sister's cat is very cute."}},
{w:"かっこいい",r:"かっこいい",m:"帥的",c:"い形",ex:{j:"あの車はかっこいいですね。",z:"那輛車好帥呢。",e:"That car is cool."}},
{w:"すごい",r:"すごい",m:"厲害的",c:"い形",ex:{j:"日本語が上手で、すごいですね。",z:"你日文很好，好厲害呢。",e:"Your Japanese is great, that's amazing."}},
{w:"素晴らしい",r:"すばらしい",m:"精彩的",c:"い形",ex:{j:"昨日のコンサートは素晴らしかったです。",z:"昨天的演唱會很精彩。",e:"Yesterday's concert was wonderful."}},
{w:"正しい",r:"ただしい",m:"正確的",c:"い形",ex:{j:"この答えは正しいです。",z:"這個答案是正確的。",e:"This answer is correct."}},

// な形容詞
{w:"元気",r:"げんき",m:"有精神的",c:"な形",ex:{j:"祖母は今もとても元気です。",z:"祖母現在也很有精神。",e:"My grandmother is still very healthy and energetic."}},
{w:"好き",r:"すき",m:"喜歡的",c:"な形",ex:{j:"私は音楽が好きです。",z:"我喜歡音樂。",e:"I like music."}},
{w:"嫌い",r:"きらい",m:"討厭的",c:"な形",ex:{j:"弟は野菜が嫌いです。",z:"弟弟討厭蔬菜。",e:"My little brother dislikes vegetables."}},
{w:"大好き",r:"だいすき",m:"最喜歡",c:"な形",ex:{j:"私は犬が大好きです。",z:"我最喜歡狗了。",e:"I love dogs."}},
{w:"大嫌い",r:"だいきらい",m:"最討厭",c:"な形",ex:{j:"私は虫が大嫌いです。",z:"我最討厭蟲子了。",e:"I really hate bugs."}},
{w:"上手",r:"じょうず",m:"擅長的",c:"な形",ex:{j:"姉は料理が上手です。",z:"姐姐很擅長做菜。",e:"My older sister is good at cooking."}},
{w:"下手",r:"へた",m:"不擅長的",c:"な形",ex:{j:"私は歌が下手です。",z:"我不擅長唱歌。",e:"I'm bad at singing."}},
{w:"有名",r:"ゆうめい",m:"有名的",c:"な形",ex:{j:"この店はとても有名です。",z:"這家店非常有名。",e:"This shop is very famous."}},
{w:"静か",r:"しずか",m:"安靜的",c:"な形",ex:{j:"図書館はいつも静かです。",z:"圖書館總是很安靜。",e:"The library is always quiet."}},
{w:"賑やか",r:"にぎやか",m:"熱鬧的",c:"な形",ex:{j:"週末の駅前は賑やかです。",z:"週末的車站前很熱鬧。",e:"The area in front of the station is lively on weekends."}},
{w:"親切",r:"しんせつ",m:"親切的",c:"な形",ex:{j:"駅員さんはとても親切でした。",z:"站務員非常親切。",e:"The station attendant was very kind."}},
{w:"丁寧",r:"ていねい",m:"有禮貌的",c:"な形",ex:{j:"店員さんの話し方は丁寧です。",z:"店員的說話方式很有禮貌。",e:"The clerk's way of speaking is polite."}},
{w:"便利",r:"べんり",m:"方便的",c:"な形",ex:{j:"このアプリはとても便利です。",z:"這個應用程式非常方便。",e:"This app is very convenient."}},
{w:"不便",r:"ふべん",m:"不方便的",c:"な形",ex:{j:"この町はバスが少なくて不便です。",z:"這個城鎮公車很少,很不方便。",e:"This town is inconvenient because there are few buses."}},
{w:"簡単",r:"かんたん",m:"簡單的",c:"な形",ex:{j:"このテストは簡単でした。",z:"這個考試很簡單。",e:"This test was easy."}},
{w:"複雑",r:"ふくざつ",m:"複雜的",c:"な形",ex:{j:"この道は複雑で、難しいです。",z:"這條路很複雜,很難。",e:"This road is complicated and difficult."}},
{w:"大切",r:"たいせつ",m:"重要的",c:"な形",ex:{j:"家族はとても大切です。",z:"家人非常重要。",e:"Family is very important."}},
{w:"大丈夫",r:"だいじょうぶ",m:"沒問題的",c:"な形",ex:{j:"心配しないでください。大丈夫です。",z:"請不要擔心,沒問題的。",e:"Please don't worry. It's fine."}},
{w:"綺麗",r:"きれい",m:"美麗・乾淨",c:"な形",ex:{j:"部屋がとても綺麗になりました。",z:"房間變得非常乾淨了。",e:"The room has become very clean."}},
{w:"暇",r:"ひま",m:"空閒的",c:"な形",ex:{j:"今日は暇だから映画を見ます。",z:"今天有空,所以要看電影。",e:"I'm free today, so I'll watch a movie."}},
{w:"色々",r:"いろいろ",m:"各種各樣",c:"な形",ex:{j:"店で色々な物を買いました。",z:"在店裡買了各種各樣的東西。",e:"I bought all kinds of things at the store."}},
{w:"大変",r:"たいへん",m:"辛苦的",c:"な形",ex:{j:"毎日の仕事は大変です。",z:"每天的工作很辛苦。",e:"My daily work is tough."}},
{w:"立派",r:"りっぱ",m:"出色的",c:"な形",ex:{j:"あの人は立派な先生です。",z:"那個人是位出色的老師。",e:"That person is a fine teacher."}},
{w:"特別",r:"とくべつ",m:"特別的",c:"な形",ex:{j:"今日は特別な日です。",z:"今天是特別的日子。",e:"Today is a special day."}},
{w:"同じ",r:"おなじ",m:"相同的",c:"な形",ex:{j:"私と兄は同じ学校です。",z:"我和哥哥是同一所學校。",e:"My older brother and I go to the same school."}},
{w:"ハンサム",r:"はんさむ",m:"帥的",c:"な形",ex:{j:"彼はとてもハンサムです。",z:"他非常帥。",e:"He is very handsome."}},

// 副詞
{w:"とても",r:"とても",m:"非常",c:"副",ex:{j:"この料理はとても美味しいです。",z:"這道菜非常好吃。",e:"This dish is very delicious."}},
{w:"たくさん",r:"たくさん",m:"很多",c:"副",ex:{j:"公園に人がたくさんいます。",z:"公園裡有很多人。",e:"There are a lot of people in the park."}},
{w:"少し",r:"すこし",m:"一點",c:"副",ex:{j:"日本語が少し分かります。",z:"我懂一點日文。",e:"I understand a little Japanese."}},
{w:"ちょっと",r:"ちょっと",m:"稍微",c:"副",ex:{j:"ちょっと待ってください。",z:"請稍微等一下。",e:"Please wait a moment."}},
{w:"もっと",r:"もっと",m:"更",c:"副",ex:{j:"もっと勉強したいです。",z:"我想更用功讀書。",e:"I want to study more."}},
{w:"一番",r:"いちばん",m:"最",c:"副",ex:{j:"クラスで彼が一番背が高いです。",z:"班上他個子最高。",e:"He is the tallest in the class."}},
{w:"よく",r:"よく",m:"經常・好好地",c:"副",ex:{j:"友達とよく映画を見ます。",z:"我常和朋友看電影。",e:"I often watch movies with my friends."}},
{w:"いつも",r:"いつも",m:"總是",c:"副",ex:{j:"父はいつも六時に起きます。",z:"爸爸總是六點起床。",e:"My father always gets up at six."}},
{w:"時々",r:"ときどき",m:"有時候",c:"副",ex:{j:"時々コーヒーを飲みます。",z:"我有時候喝咖啡。",e:"I sometimes drink coffee."}},
{w:"たまに",r:"たまに",m:"偶爾",c:"副",ex:{j:"たまに外で晩ご飯を食べます。",z:"我偶爾在外面吃晚餐。",e:"I occasionally eat dinner out."}},
{w:"あまり",r:"あまり",m:"不太",c:"副",ex:{j:"肉はあまり食べません。",z:"我不太吃肉。",e:"I don't eat much meat."}},
{w:"全然",r:"ぜんぜん",m:"完全(不)",c:"副",ex:{j:"この本は全然おもしろくないです。",z:"這本書一點也不有趣。",e:"This book is not interesting at all."}},
{w:"まだ",r:"まだ",m:"還・尚未",c:"副",ex:{j:"ごはんはまだできていません。",z:"飯還沒做好。",e:"The meal is not ready yet."}},
{w:"もう",r:"もう",m:"已經",c:"副",ex:{j:"宿題はもう終わりました。",z:"作業已經做完了。",e:"I have already finished my homework."}},
{w:"すぐ",r:"すぐ",m:"馬上",c:"副",ex:{j:"すぐ行きますから、待ってください。",z:"我馬上去,請等一下。",e:"I'll go right away, so please wait."}},
{w:"ゆっくり",r:"ゆっくり",m:"慢慢地",c:"副",ex:{j:"もっとゆっくり話してください。",z:"請說慢一點。",e:"Please speak more slowly."}},
{w:"だんだん",r:"だんだん",m:"漸漸",c:"副",ex:{j:"だんだん寒くなりました。",z:"漸漸變冷了。",e:"It has gradually gotten cold."}},
{w:"初めて",r:"はじめて",m:"第一次",c:"副",ex:{j:"初めて日本に来ました。",z:"我第一次來日本。",e:"I came to Japan for the first time."}},
{w:"まず",r:"まず",m:"首先",c:"副",ex:{j:"まず手を洗ってください。",z:"請先洗手。",e:"First, please wash your hands."}},
{w:"多分",r:"たぶん",m:"大概",c:"副",ex:{j:"明日は多分雨が降ります。",z:"明天大概會下雨。",e:"It will probably rain tomorrow."}},
{w:"きっと",r:"きっと",m:"一定",c:"副",ex:{j:"彼はきっと来ます。",z:"他一定會來。",e:"He will surely come."}},
{w:"本当に",r:"ほんとうに",m:"真的",c:"副",ex:{j:"この料理は本当においしいです。",z:"這道菜真的很好吃。",e:"This dish is really delicious."}},
{w:"大体",r:"だいたい",m:"大致",c:"副",ex:{j:"仕事は大体終わりました。",z:"工作大致做完了。",e:"The work is mostly finished."}},
{w:"一緒に",r:"いっしょに",m:"一起",c:"副",ex:{j:"一緒に昼ごはんを食べましょう。",z:"一起吃午餐吧。",e:"Let's eat lunch together."}},
{w:"また",r:"また",m:"再・又",c:"副",ex:{j:"また明日会いましょう。",z:"明天再見吧。",e:"Let's meet again tomorrow."}},
{w:"まっすぐ",r:"まっすぐ",m:"筆直地",c:"副",ex:{j:"この道をまっすぐ行ってください。",z:"請沿著這條路直走。",e:"Please go straight down this road."}},
{w:"ちゃんと",r:"ちゃんと",m:"好好地",c:"副",ex:{j:"毎日ちゃんと勉強します。",z:"我每天好好念書。",e:"I study properly every day."}},
{w:"はっきり",r:"はっきり",m:"清楚地",c:"副",ex:{j:"もっとはっきり言ってください。",z:"請說得更清楚一點。",e:"Please say it more clearly."}},
{w:"どうぞ",r:"どうぞ",m:"請",c:"副",ex:{j:"どうぞこちらへ座ってください。",z:"請往這邊坐。",e:"Please sit over here."}},
{w:"どう",r:"どう",m:"如何",c:"副",ex:{j:"日本の生活はどうですか。",z:"日本的生活如何?",e:"How is life in Japan?"}},
{w:"なぜ",r:"なぜ",m:"為什麼",c:"副",ex:{j:"なぜ学校を休みましたか。",z:"為什麼向學校請假了?",e:"Why did you take a day off from school?"}},
{w:"どうして",r:"どうして",m:"為什麼",c:"副",ex:{j:"どうして泣いているんですか。",z:"你為什麼在哭?",e:"Why are you crying?"}},
{w:"どうやって",r:"どうやって",m:"怎麼做",c:"副",ex:{j:"駅までどうやって行きますか。",z:"要怎麼去車站?",e:"How do you get to the station?"}},
{w:"どのくらい",r:"どのくらい",m:"多少程度",c:"副",ex:{j:"駅までどのくらいかかりますか。",z:"到車站要花多久?",e:"How long does it take to the station?"}},
{w:"いくら",r:"いくら",m:"多少錢",c:"副",ex:{j:"このかばんはいくらですか。",z:"這個包包多少錢?",e:"How much is this bag?"}},
{w:"いくつ",r:"いくつ",m:"幾個・幾歲",c:"副",ex:{j:"りんごはいくつありますか。",z:"有幾個蘋果?",e:"How many apples are there?"}},
{w:"いつ",r:"いつ",m:"什麼時候",c:"副",ex:{j:"誕生日はいつですか。",z:"你的生日是什麼時候?",e:"When is your birthday?"}},
{w:"どこ",r:"どこ",m:"哪裡",c:"副",ex:{j:"トイレはどこですか。",z:"廁所在哪裡?",e:"Where is the restroom?"}},
{w:"何",r:"なに",m:"什麼",c:"副",ex:{j:"それは何ですか。",z:"那是什麼?",e:"What is that?"}},
{w:"誰",r:"だれ",m:"誰",c:"副",ex:{j:"あの人は誰ですか。",z:"那個人是誰?",e:"Who is that person?"}},
{w:"もう少し",r:"もうすこし",m:"再一點",c:"副",ex:{j:"もう少し待ってください。",z:"請再等一下。",e:"Please wait a little longer."}},
{w:"そろそろ",r:"そろそろ",m:"差不多該",c:"副",ex:{j:"そろそろ帰りましょう。",z:"差不多該回去了。",e:"It's about time we headed home."}},
{w:"やっと",r:"やっと",m:"終於",c:"副",ex:{j:"やっと宿題が終わりました。",z:"作業終於做完了。",e:"I finally finished my homework."}},
{w:"さっき",r:"さっき",m:"剛才",c:"副",ex:{j:"さっき田中さんに会いました。",z:"我剛才遇到了田中先生。",e:"I met Mr. Tanaka just now."}},
{w:"もう一度",r:"もういちど",m:"再一次",c:"副",ex:{j:"すみません、もう一度言ってください。",z:"不好意思，請再說一次。",e:"Excuse me, please say it one more time."}},
{w:"必ず",r:"かならず",m:"一定",c:"副",ex:{j:"明日は必ず来てください。",z:"明天請一定要來。",e:"Please be sure to come tomorrow."}},
{w:"絶対",r:"ぜったい",m:"絕對",c:"副",ex:{j:"この映画は絶対おもしろいです。",z:"這部電影絕對很有趣。",e:"This movie is absolutely interesting."}},
{w:"特に",r:"とくに",m:"特別",c:"副",ex:{j:"果物が好きです。特にりんごが好きです。",z:"我喜歡水果，特別喜歡蘋果。",e:"I like fruit, especially apples."}},
{w:"普通",r:"ふつう",m:"普通",c:"副",ex:{j:"わたしは普通、七時に起きます。",z:"我通常七點起床。",e:"I usually get up at seven."}},

// その他（接続詞・感嘆詞・助詞用法・挨拶等）
{w:"はい",r:"はい",m:"是",c:"他",ex:{j:"「学生ですか。」「はい、そうです。」",z:"「你是學生嗎？」「是的。」",e:"\"Are you a student?\" \"Yes, I am.\""}},
{w:"いいえ",r:"いいえ",m:"不是",c:"他",ex:{j:"「これはあなたの本ですか。」「いいえ、違います。」",z:"「這是你的書嗎？」「不，不是。」",e:"\"Is this your book?\" \"No, it isn't.\""}},
{w:"ええ",r:"ええ",m:"是(口語)",c:"他",ex:{j:"「一緒に行きますか。」「ええ、行きます。」",z:"「要一起去嗎？」「嗯，去。」",e:"\"Shall we go together?\" \"Yeah, let's go.\""}},
{w:"いい",r:"いい",m:"好",c:"他",ex:{j:"今日はとてもいい天気です。",z:"今天天氣非常好。",e:"The weather is very nice today."}},
{w:"おはようございます",r:"おはようございます",m:"早安",c:"他",ex:{j:"先生、おはようございます。",z:"老師，早安。",e:"Good morning, teacher."}},
{w:"こんにちは",r:"こんにちは",m:"你好",c:"他",ex:{j:"こんにちは、お元気ですか。",z:"你好，你好嗎？",e:"Hello, how are you?"}},
{w:"こんばんは",r:"こんばんは",m:"晚上好",c:"他",ex:{j:"こんばんは、今日は寒いですね。",z:"晚上好，今天很冷呢。",e:"Good evening, it's cold today, isn't it?"}},
{w:"さようなら",r:"さようなら",m:"再見",c:"他",ex:{j:"では、さようなら。また明日。",z:"那麼，再見。明天見。",e:"Well then, goodbye. See you tomorrow."}},
{w:"おやすみなさい",r:"おやすみなさい",m:"晚安",c:"他",ex:{j:"もう遅いですね。おやすみなさい。",z:"已經很晚了呢。晚安。",e:"It's late now. Good night."}},
{w:"すみません",r:"すみません",m:"對不起",c:"他",ex:{j:"すみません、駅はどこですか。",z:"不好意思，車站在哪裡？",e:"Excuse me, where is the station?"}},
{w:"ごめんなさい",r:"ごめんなさい",m:"抱歉",c:"他",ex:{j:"遅れて、ごめんなさい。",z:"遲到了，對不起。",e:"I'm sorry for being late."}},
{w:"ありがとうございます",r:"ありがとうございます",m:"謝謝",c:"他",ex:{j:"手伝ってくれて、ありがとうございます。",z:"謝謝你幫我。",e:"Thank you for helping me."}},
{w:"どういたしまして",r:"どういたしまして",m:"不客氣",c:"他",ex:{j:"「ありがとうございます。」「どういたしまして。」",z:"「謝謝。」「不客氣。」",e:"\"Thank you.\" \"You're welcome.\""}},
{w:"いただきます",r:"いただきます",m:"我開動了",c:"他",ex:{j:"では、いただきます。",z:"那麼，我開動了。",e:"Well then, let's eat."}},
{w:"ごちそうさまでした",r:"ごちそうさまでした",m:"多謝款待",c:"他",ex:{j:"おいしかったです。ごちそうさまでした。",z:"很好吃。多謝款待。",e:"It was delicious. Thank you for the meal."}},
{w:"行ってきます",r:"いってきます",m:"我出門了",c:"他",ex:{j:"お母さん、行ってきます。",z:"媽媽，我出門了。",e:"Mom, I'm off."}},
{w:"行ってらっしゃい",r:"いってらっしゃい",m:"路上小心",c:"他",ex:{j:"気をつけて、行ってらっしゃい。",z:"小心點，路上小心。",e:"Take care, have a good day."}},
{w:"ただいま",r:"ただいま",m:"我回來了",c:"他",ex:{j:"ただいま。おなかがすきました。",z:"我回來了。肚子餓了。",e:"I'm home. I'm hungry."}},
{w:"お帰りなさい",r:"おかえりなさい",m:"你回來了",c:"他",ex:{j:"あ、お父さん、お帰りなさい。",z:"啊，爸爸，你回來了。",e:"Oh, Dad, welcome home."}},
{w:"お願いします",r:"おねがいします",m:"拜託了",c:"他",ex:{j:"コーヒーを一つ、お願いします。",z:"請給我一杯咖啡，拜託了。",e:"One coffee, please."}},
{w:"初めまして",r:"はじめまして",m:"初次見面",c:"他",ex:{j:"初めまして、田中と申します。",z:"初次見面，我叫田中。",e:"Nice to meet you, my name is Tanaka."}},
{w:"よろしくお願いします",r:"よろしくおねがいします",m:"請多指教",c:"他",ex:{j:"これからよろしくお願いします。",z:"今後請多指教。",e:"I look forward to working with you."}},
{w:"お元気ですか",r:"おげんきですか",m:"你好嗎",c:"他",ex:{j:"田中さん、お元気ですか。",z:"田中先生，你好嗎？",e:"Mr. Tanaka, how are you?"}},
{w:"お大事に",r:"おだいじに",m:"請保重",c:"他",ex:{j:"風邪ですか。どうぞお大事に。",z:"感冒了嗎？請多保重。",e:"You have a cold? Please take care of yourself."}},
{w:"お誕生日おめでとう",r:"おたんじょうびおめでとう",m:"生日快樂",c:"他",ex:{j:"お母さん、お誕生日おめでとう。",z:"媽媽，生日快樂。",e:"Happy birthday, Mom."}},
{w:"おめでとうございます",r:"おめでとうございます",m:"恭喜",c:"他",ex:{j:"ご結婚、おめでとうございます。",z:"恭喜你結婚。",e:"Congratulations on your marriage."}},
{w:"失礼します",r:"しつれいします",m:"打擾了",c:"他",ex:{j:"すみません、失礼します。",z:"不好意思，先離開了。",e:"Excuse me, I'll be leaving now."}},
{w:"ちょっと待ってください",r:"ちょっとまってください",m:"請稍等",c:"他",ex:{j:"ちょっと待ってください。今行きます。",z:"請稍等一下，我馬上來。",e:"Please wait a moment. I'm coming now."}},
// ── 接続詞 ──
{w:"でも",r:"でも",m:"但是",c:"他",ex:{j:"日本語は難しいです。でも、面白いです。",z:"日語很難，但是很有趣。",e:"Japanese is difficult, but it's interesting."}},
{w:"しかし",r:"しかし",m:"然而",c:"他",ex:{j:"雨が降りました。しかし、出かけました。",z:"下雨了，然而我還是出門了。",e:"It rained. However, I went out."}},
{w:"そして",r:"そして",m:"然後",c:"他",ex:{j:"公園へ行きました。そして、写真を撮りました。",z:"我去了公園，然後拍了照片。",e:"I went to the park. And then I took photos."}},
{w:"それから",r:"それから",m:"之後",c:"他",ex:{j:"朝ご飯を食べました。それから、学校へ行きました。",z:"我吃了早餐，之後去了學校。",e:"I ate breakfast. After that, I went to school."}},
{w:"それで",r:"それで",m:"因此",c:"他",ex:{j:"熱があります。それで、休みます。",z:"我發燒了，所以要休息。",e:"I have a fever. That's why I'm taking a rest."}},
{w:"だから",r:"だから",m:"所以",c:"他",ex:{j:"明日はテストです。だから、勉強します。",z:"明天有考試，所以我要唸書。",e:"There's a test tomorrow. So I'll study."}},
{w:"けれども",r:"けれども",m:"雖然",c:"他",ex:{j:"高いです。けれども、買います。",z:"雖然很貴，但我還是要買。",e:"It's expensive, but I'll buy it."}},
{w:"それに",r:"それに",m:"而且",c:"他",ex:{j:"この店は安いです。それに、おいしいです。",z:"這家店很便宜，而且很好吃。",e:"This shop is cheap. Besides, it's delicious."}},
{w:"または",r:"または",m:"或者",c:"他",ex:{j:"ペンまたは鉛筆で書いてください。",z:"請用筆或鉛筆寫。",e:"Please write with a pen or a pencil."}},
// ── 指示詞 ──
{w:"これ",r:"これ",m:"這個",c:"他",ex:{j:"これは私の傘です。",z:"這個是我的傘。",e:"This is my umbrella."}},
{w:"それ",r:"それ",m:"那個",c:"他",ex:{j:"それは何ですか。",z:"那個是什麼？",e:"What is that?"}},
{w:"あれ",r:"あれ",m:"那個(遠)",c:"他",ex:{j:"あれは駅です。",z:"那個(遠處)是車站。",e:"That over there is the station."}},
{w:"どれ",r:"どれ",m:"哪個",c:"他",ex:{j:"あなたのかばんはどれですか。",z:"你的包包是哪個？",e:"Which one is your bag?"}},
{w:"この",r:"この",m:"這個~",c:"他",ex:{j:"この本はとても面白いです。",z:"這本書非常有趣。",e:"This book is very interesting."}},
{w:"その",r:"その",m:"那個~",c:"他",ex:{j:"その写真を見せてください。",z:"請給我看那張照片。",e:"Please show me that photo."}},
{w:"あの",r:"あの",m:"那個(遠)~",c:"他",ex:{j:"あの人は先生です。",z:"那個(遠處)人是老師。",e:"That person over there is a teacher."}},
{w:"どの",r:"どの",m:"哪個~",c:"他",ex:{j:"どの電車に乗りますか。",z:"你要搭哪一班電車？",e:"Which train will you take?"}},
{w:"ここ",r:"ここ",m:"這裡",c:"他",ex:{j:"ここは私の教室です。",z:"這裡是我的教室。",e:"This place is my classroom."}},
{w:"そこ",r:"そこ",m:"那裡",c:"他",ex:{j:"そこに座ってください。",z:"請坐在那裡。",e:"Please sit there."}},
{w:"あそこ",r:"あそこ",m:"那裡(遠)",c:"他",ex:{j:"あそこにコンビニがあります。",z:"那裡(遠處)有便利商店。",e:"There's a convenience store over there."}},
{w:"こう",r:"こう",m:"這樣",c:"他",ex:{j:"こう書いてください。",z:"請這樣寫。",e:"Please write it like this."}},
{w:"そう",r:"そう",m:"那樣",c:"他",ex:{j:"そうしましょう。",z:"就那樣做吧。",e:"Let's do it that way."}},
{w:"ああ",r:"ああ",m:"那樣(遠)",c:"他",ex:{j:"彼はいつもああ話します。",z:"他總是那樣說話。",e:"He always talks like that."}},
{w:"こんな",r:"こんな",m:"這樣的",c:"他",ex:{j:"こんな服がほしいです。",z:"我想要這樣的衣服。",e:"I want clothes like this."}},
{w:"そんな",r:"そんな",m:"那樣的",c:"他",ex:{j:"そんな話は知りません。",z:"那樣的事我不知道。",e:"I don't know about that kind of thing."}},
{w:"あんな",r:"あんな",m:"那樣的(遠)",c:"他",ex:{j:"あんな大きい犬は初めて見ました。",z:"那麼大的狗我是第一次看到。",e:"That's the first time I've seen a dog that big."}},
{w:"どんな",r:"どんな",m:"怎樣的",c:"他",ex:{j:"どんな音楽が好きですか。",z:"你喜歡怎樣的音樂?",e:"What kind of music do you like?"}},
// ── その他表現 ──
{w:"ぐらい",r:"ぐらい",m:"大約",c:"他",ex:{j:"駅まで十分ぐらいかかります。",z:"到車站大約要花十分鐘。",e:"It takes about ten minutes to the station."}},
{w:"ごろ",r:"ごろ",m:"左右(時刻)",c:"他",ex:{j:"毎朝七時ごろ起きます。",z:"每天早上七點左右起床。",e:"I get up around seven every morning."}},
{w:"まで",r:"まで",m:"到~為止",c:"他",ex:{j:"月曜日から金曜日まで働きます。",z:"從星期一工作到星期五。",e:"I work from Monday to Friday."}},
{w:"から",r:"から",m:"從~",c:"他",ex:{j:"日本語の授業は九時から始まります。",z:"日語課從九點開始。",e:"The Japanese class starts from nine o'clock."}},
{w:"と",r:"と",m:"和",c:"他",ex:{j:"わたしは友だちと映画を見ました。",z:"我和朋友看了電影。",e:"I watched a movie with my friend."}},
{w:"や",r:"や",m:"和(列舉)",c:"他",ex:{j:"かばんの中に本やノートがあります。",z:"包包裡有書和筆記本等等。",e:"There are books and notebooks and such in the bag."}},
{w:"など",r:"など",m:"等等",c:"他",ex:{j:"果物、りんごやみかんなどを買いました。",z:"買了水果,蘋果和橘子等等。",e:"I bought fruit, like apples and oranges."}},
{w:"だけ",r:"だけ",m:"只有",c:"他",ex:{j:"きょうは水だけ飲みました。",z:"今天只喝了水。",e:"Today I only drank water."}},
{w:"しか",r:"しか",m:"只(+否定)",c:"他",ex:{j:"お金は百円しかありません。",z:"錢只有一百日圓。",e:"I only have a hundred yen."}},
{w:"ほう",r:"ほう",m:"~方面",c:"他",ex:{j:"わたしはコーヒーのほうが好きです。",z:"我比較喜歡咖啡。",e:"I prefer coffee."}},
{w:"みんな",r:"みんな",m:"大家",c:"他",ex:{j:"クラスのみんなは元気です。",z:"班上的大家都很有精神。",e:"Everyone in the class is doing well."}},
{w:"自分",r:"じぶん",m:"自己",c:"他",ex:{j:"朝ごはんは自分で作ります。",z:"早餐我自己做。",e:"I make breakfast by myself."}},
{w:"こと",r:"こと",m:"事情",c:"他",ex:{j:"わたしの趣味は絵をかくことです。",z:"我的興趣是畫畫這件事。",e:"My hobby is drawing pictures."}},
{w:"ため",r:"ため",m:"為了",c:"他",ex:{j:"家族のために働いています。",z:"我為了家人而工作。",e:"I work for my family."}},
{w:"つもり",r:"つもり",m:"打算",c:"他",ex:{j:"あした図書館へ行くつもりです。",z:"我打算明天去圖書館。",e:"I plan to go to the library tomorrow."}},
{w:"はず",r:"はず",m:"應該",c:"他",ex:{j:"彼はもう家に着いたはずです。",z:"他應該已經到家了。",e:"He should have already arrived home."}},
{w:"ところ",r:"ところ",m:"正要…時",c:"他",ex:{j:"今から出かけるところです。",z:"我正要出門。",e:"I'm just about to go out."}},
{w:"ばかり",r:"ばかり",m:"淨是・剛",c:"他",ex:{j:"弟はゲームばかりしています。",z:"弟弟淨是在打電動。",e:"My little brother does nothing but play games."}},
{w:"そうです",r:"そうです",m:"聽說",c:"他",ex:{j:"あしたは雨が降るそうです。",z:"聽說明天會下雨。",e:"I heard it will rain tomorrow."}},
{w:"ようだ",r:"ようだ",m:"好像",c:"他",ex:{j:"田中さんは風邪をひいたようだ。",z:"田中先生好像感冒了。",e:"It seems Mr. Tanaka has caught a cold."}},
{w:"かもしれない",r:"かもしれない",m:"也許",c:"他",ex:{j:"あしたは寒いかもしれない。",z:"明天也許會冷。",e:"It might be cold tomorrow."}},
{w:"なければならない",r:"なければならない",m:"必須",c:"他",ex:{j:"あしたは早く起きなければならない。",z:"明天必須早起。",e:"I have to get up early tomorrow."}},
{w:"てもいい",r:"てもいい",m:"可以",c:"他",ex:{j:"ここで写真を撮ってもいいですか。",z:"可以在這裡拍照嗎?",e:"May I take photos here?"}},
{w:"てはいけない",r:"てはいけない",m:"不可以",c:"他",ex:{j:"ここでたばこを吸ってはいけません。",z:"這裡不可以抽菸。",e:"You must not smoke here."}},
{w:"たい",r:"たい",m:"想要~",c:"他",ex:{j:"わたしは日本へ行きたいです。",z:"我想去日本。",e:"I want to go to Japan."}},
{w:"ましょう",r:"ましょう",m:"~吧",c:"他",ex:{j:"いっしょに昼ごはんを食べましょう。",z:"一起吃午餐吧。",e:"Let's eat lunch together."}},
{w:"でしょう",r:"でしょう",m:"~吧(推測)",c:"他",ex:{j:"あしたはいい天気でしょう。",z:"明天天氣應該會很好吧。",e:"The weather will probably be nice tomorrow."}},
{w:"そうだ",r:"そうだ",m:"看起來~",c:"他",ex:{j:"この ケーキは おいしそうだ。",z:"這個蛋糕看起來很好吃。",e:"This cake looks delicious."}},
{w:"ください",r:"ください",m:"請~",c:"他",ex:{j:"水を 一杯 ください。",z:"請給我一杯水。",e:"Please give me a glass of water."}},
{w:"お疲れ様です",r:"おつかれさまです",m:"辛苦了",c:"他",ex:{j:"お疲れ様です。お先に 失礼します。",z:"辛苦了。我先下班了。",e:"Good work today. I'll head off first."}},
{w:"あのう",r:"あのう",m:"那個(語氣)",c:"他",ex:{j:"あのう、駅は どこですか。",z:"那個…請問車站在哪裡?",e:"Um, where is the station?"}},
{w:"ええと",r:"ええと",m:"嗯(思考)",c:"他",ex:{j:"ええと、私の 名前は 田中です。",z:"嗯…我的名字是田中。",e:"Um, my name is Tanaka."}}
];
