// vocab-n4-en.js — N4 單字英文(pilot,未上線;lang=en by-index merge)。Sonnet 翻+Haiku 校+Opus 裁決修正。w/r 日文不動。
const VOCAB_N4_EN = [
  {"w": "経験", "m": "experience", "c": "n."},
  {"w": "社会", "m": "society", "c": "n."},
  {"w": "政治", "m": "politics", "c": "n."},
  {"w": "経済", "m": "economy", "c": "n."},
  {"w": "文化", "m": "culture", "c": "n."},
  {"w": "歴史", "m": "history", "c": "n."},
  {"w": "技術", "m": "technology, technique", "c": "n."},
  {"w": "産業", "m": "industry", "c": "n."},
  {"w": "貿易", "m": "trade", "c": "n."},
  {"w": "製品", "m": "product", "c": "n."},
  {"w": "原因", "m": "cause", "c": "n."},
  {"w": "理由", "m": "reason", "c": "n."},
  {"w": "目的", "m": "purpose", "c": "n."},
  {"w": "計画", "m": "plan", "c": "n."},
  {"w": "予定", "m": "schedule, plan", "c": "n."},
  {"w": "準備", "m": "preparation", "c": "n."},
  {"w": "関係", "m": "relationship", "c": "n."},
  {"w": "連絡", "m": "contact", "c": "n."},
  {"w": "相談", "m": "to consult, to talk over", "c": "n."},
  {"w": "説明", "m": "explanation", "c": "n."},
  {"w": "意見", "m": "opinion", "c": "n."},
  {"w": "返事", "m": "reply", "c": "n."},
  {"w": "挨拶", "m": "greeting", "c": "n."},
  {"w": "紹介", "m": "introduction", "c": "n."},
  {"w": "約束", "m": "promise", "c": "n."},
  {"w": "習慣", "m": "custom, habit", "c": "n."},
  {"w": "趣味", "m": "hobby", "c": "n."},
  {"w": "興味", "m": "interest", "c": "n."},
  {"w": "気持ち", "m": "feeling", "c": "n."},
  {"w": "気分", "m": "mood", "c": "n."},
  {"w": "心", "m": "heart, mind", "c": "n."},
  {"w": "夢", "m": "dream", "c": "n."},
  {"w": "思い出", "m": "memory", "c": "n."},
  {"w": "お祝い", "m": "celebration", "c": "n."},
  {"w": "お見舞い", "m": "visit (to sick person)", "c": "n."},
  {"w": "お礼", "m": "thanks, gratitude", "c": "n."},
  {"w": "お土産", "m": "souvenir", "c": "n."},
  {"w": "お釣り", "m": "change (money)", "c": "n."},
  {"w": "値段", "m": "price", "c": "n."},
  {"w": "割引", "m": "discount", "c": "n."},
  {"w": "売り場", "m": "sales floor", "c": "n."},
  {"w": "品物", "m": "goods, item", "c": "n."},
  {"w": "届け", "m": "delivery", "c": "n."},
  {"w": "受付", "m": "reception", "c": "n."},
  {"w": "会場", "m": "venue", "c": "n."},
  {"w": "会議", "m": "meeting", "c": "n."},
  {"w": "会話", "m": "conversation", "c": "n."},
  {"w": "発表", "m": "presentation, announcement", "c": "n."},
  {"w": "研究", "m": "research", "c": "n."},
  {"w": "教育", "m": "education", "c": "n."},
  {"w": "卒業", "m": "graduation", "c": "n."},
  {"w": "入学", "m": "school entrance", "c": "n."},
  {"w": "試験", "m": "exam", "c": "n."},
  {"w": "合格", "m": "pass (an exam)", "c": "n."},
  {"w": "点", "m": "score, point", "c": "n."},
  {"w": "成績", "m": "grades, performance", "c": "n."},
  {"w": "文法", "m": "grammar", "c": "n."},
  {"w": "文章", "m": "sentence, essay", "c": "n."},
  {"w": "漢字", "m": "kanji, Chinese character", "c": "n."},
  {"w": "翻訳", "m": "translation", "c": "n."},
  {"w": "意味", "m": "meaning", "c": "n."},
  {"w": "中学校", "m": "junior high school", "c": "n."},
  {"w": "高校", "m": "high school", "c": "n."},
  {"w": "大学院", "m": "graduate school", "c": "n."},
  {"w": "授業", "m": "class, lesson", "c": "n."},
  {"w": "宿題", "m": "homework", "c": "n."},
  {"w": "科目", "m": "subject", "c": "n."},
  {"w": "数学", "m": "mathematics", "c": "n."},
  {"w": "科学", "m": "science", "c": "n."},
  {"w": "地理", "m": "geography", "c": "n."},
  {"w": "法律", "m": "law", "c": "n."},
  {"w": "就職", "m": "finding employment", "c": "n."},
  {"w": "転職", "m": "job change", "c": "n."},
  {"w": "仕事", "m": "work, job", "c": "n."},
  {"w": "職業", "m": "occupation", "c": "n."},
  {"w": "会社員", "m": "company employee", "c": "n."},
  {"w": "社長", "m": "company president", "c": "n."},
  {"w": "部長", "m": "department manager", "c": "n."},
  {"w": "課長", "m": "section chief", "c": "n."},
  {"w": "係", "m": "person in charge", "c": "n."},
  {"w": "同僚", "m": "colleague", "c": "n."},
  {"w": "上司", "m": "superior, boss", "c": "n."},
  {"w": "部下", "m": "subordinate", "c": "n."},
  {"w": "客", "m": "customer, guest", "c": "n."},
  {"w": "お客様", "m": "customer (polite)", "c": "n."},
  {"w": "相手", "m": "the other party", "c": "n."},
  {"w": "彼", "m": "he; boyfriend", "c": "n."},
  {"w": "彼女", "m": "she; girlfriend", "c": "n."},
  {"w": "親", "m": "parent", "c": "n."},
  {"w": "息子", "m": "son", "c": "n."},
  {"w": "娘", "m": "daughter", "c": "n."},
  {"w": "祖父", "m": "grandfather", "c": "n."},
  {"w": "祖母", "m": "grandmother", "c": "n."},
  {"w": "孫", "m": "grandchild", "c": "n."},
  {"w": "親戚", "m": "relative", "c": "n."},
  {"w": "隣", "m": "next door, neighbor", "c": "n."},
  {"w": "近所", "m": "neighborhood", "c": "n."},
  {"w": "人口", "m": "population", "c": "n."},
  {"w": "国際", "m": "international", "c": "n."},
  {"w": "世界", "m": "world", "c": "n."},
  {"w": "国民", "m": "citizens, people (of a nation)", "c": "n."},
  {"w": "島", "m": "island", "c": "n."},
  {"w": "都会", "m": "city, urban area", "c": "n."},
  {"w": "田舎", "m": "countryside", "c": "n."},
  {"w": "地方", "m": "region, locality", "c": "n."},
  {"w": "交通", "m": "traffic, transportation", "c": "n."},
  {"w": "道路", "m": "road", "c": "n."},
  {"w": "交差点", "m": "intersection", "c": "n."},
  {"w": "信号", "m": "traffic light, signal", "c": "n."},
  {"w": "駐車場", "m": "parking lot", "c": "n."},
  {"w": "乗り物", "m": "vehicle", "c": "n."},
  {"w": "飛行機", "m": "airplane", "c": "n."},
  {"w": "船", "m": "ship, boat", "c": "n."},
  {"w": "席", "m": "seat", "c": "n."},
  {"w": "特急", "m": "limited express (train)", "c": "n."},
  {"w": "急行", "m": "express (train)", "c": "n."},
  {"w": "片道", "m": "one way (trip)", "c": "n."},
  {"w": "往復", "m": "round trip", "c": "n."},
  {"w": "出発", "m": "departure", "c": "n."},
  {"w": "到着", "m": "arrival", "c": "n."},
  {"w": "出口", "m": "exit", "c": "n."},
  {"w": "入口", "m": "entrance", "c": "n."},
  {"w": "乗り換え", "m": "transfer (trains, etc.)", "c": "n."},
  {"w": "景色", "m": "scenery, view", "c": "n."},
  {"w": "観光", "m": "sightseeing", "c": "n."},
  {"w": "旅館", "m": "Japanese-style inn", "c": "n."},
  {"w": "建物", "m": "building", "c": "n."},
  {"w": "寺", "m": "temple", "c": "n."},
  {"w": "神社", "m": "shrine", "c": "n."},
  {"w": "美術館", "m": "art museum", "c": "n."},
  {"w": "博物館", "m": "museum", "c": "n."},
  {"w": "動物園", "m": "zoo", "c": "n."},
  {"w": "遊園地", "m": "amusement park", "c": "n."},
  {"w": "広場", "m": "plaza, square", "c": "n."},
  {"w": "工場", "m": "factory", "c": "n."},
  {"w": "事務所", "m": "office", "c": "n."},
  {"w": "屋上", "m": "rooftop", "c": "n."},
  {"w": "地下", "m": "basement, underground", "c": "n."},
  {"w": "階段", "m": "stairs", "c": "n."},
  {"w": "壁", "m": "wall", "c": "n."},
  {"w": "天井", "m": "ceiling", "c": "n."},
  {"w": "床", "m": "floor", "c": "n."},
  {"w": "畳", "m": "tatami mat", "c": "n."},
  {"w": "押入れ", "m": "closet", "c": "n."},
  {"w": "布団", "m": "futon, bedding", "c": "n."},
  {"w": "枕", "m": "pillow", "c": "n."},
  {"w": "棚", "m": "shelf", "c": "n."},
  {"w": "引き出し", "m": "drawer", "c": "n."},
  {"w": "鏡", "m": "mirror", "c": "n."},
  {"w": "石鹸", "m": "soap", "c": "n."},
  {"w": "タオル", "m": "towel", "c": "n."},
  {"w": "歯磨き", "m": "brushing teeth", "c": "n."},
  {"w": "ごみ", "m": "trash, garbage", "c": "n."},
  {"w": "ごみ箱", "m": "trash can", "c": "n."},
  {"w": "火", "m": "fire", "c": "n."},
  {"w": "湯", "m": "hot water", "c": "n."},
  {"w": "ガス", "m": "gas", "c": "n."},
  {"w": "冷房", "m": "air conditioning (cooling)", "c": "n."},
  {"w": "暖房", "m": "heating", "c": "n."},
  {"w": "エアコン", "m": "air conditioner", "c": "n."},
  {"w": "道具", "m": "tool", "c": "n."},
  {"w": "はさみ", "m": "scissors", "c": "n."},
  {"w": "糊", "m": "glue", "c": "n."},
  {"w": "定規", "m": "ruler", "c": "n."},
  {"w": "ボール", "m": "ball", "c": "n."},
  {"w": "人形", "m": "doll", "c": "n."},
  {"w": "お祭り", "m": "festival", "c": "n."},
  {"w": "お正月", "m": "New Year", "c": "n."},
  {"w": "花見", "m": "cherry blossom viewing", "c": "n."},
  {"w": "試合", "m": "match, game", "c": "n."},
  {"w": "番組", "m": "TV program", "c": "n."},
  {"w": "小説", "m": "novel", "c": "n."},
  {"w": "漫画", "m": "comic, manga", "c": "n."},
  {"w": "日記", "m": "diary", "c": "n."},
  {"w": "アルバム", "m": "album", "c": "n."},
  {"w": "展覧会", "m": "exhibition", "c": "n."},
  {"w": "音楽", "m": "music", "c": "n."},
  {"w": "楽器", "m": "musical instrument", "c": "n."},
  {"w": "ピアノ", "m": "piano", "c": "n."},
  {"w": "歌", "m": "song", "c": "n."},
  {"w": "絵", "m": "picture, painting", "c": "n."},
  {"w": "写真", "m": "photograph", "c": "n."},
  {"w": "味", "m": "taste, flavor", "c": "n."},
  {"w": "材料", "m": "ingredients, material", "c": "n."},
  {"w": "食料品", "m": "groceries, foodstuffs", "c": "n."},
  {"w": "お菓子", "m": "snack, sweets", "c": "n."},
  {"w": "ご飯", "m": "cooked rice, meal", "c": "n."},
  {"w": "丼", "m": "rice bowl dish", "c": "n."},
  {"w": "味噌", "m": "miso", "c": "n."},
  {"w": "醤油", "m": "soy sauce", "c": "n."},
  {"w": "砂糖", "m": "sugar", "c": "n."},
  {"w": "塩", "m": "salt", "c": "n."},
  {"w": "酢", "m": "vinegar", "c": "n."},
  {"w": "漬物", "m": "pickles", "c": "n."},
  {"w": "お弁当", "m": "boxed lunch", "c": "n."},
  {"w": "定食", "m": "set meal", "c": "n."},
  {"w": "丼", "m": "rice bowl dish", "c": "n."},
  {"w": "レジ", "m": "cash register", "c": "n."},
  {"w": "メニュー", "m": "menu", "c": "n."},
  {"w": "注文", "m": "order (food, etc.)", "c": "n."},
  {"w": "体", "m": "body", "c": "n."},
  {"w": "頭", "m": "head", "c": "n."},
  {"w": "顔", "m": "face", "c": "n."},
  {"w": "髪", "m": "hair", "c": "n."},
  {"w": "背", "m": "back, height", "c": "n."},
  {"w": "指", "m": "finger", "c": "n."},
  {"w": "腕", "m": "arm", "c": "n."},
  {"w": "首", "m": "neck", "c": "n."},
  {"w": "肩", "m": "shoulder", "c": "n."},
  {"w": "腰", "m": "waist, lower back", "c": "n."},
  {"w": "背中", "m": "back (of body)", "c": "n."},
  {"w": "喉", "m": "throat", "c": "n."},
  {"w": "胸", "m": "chest", "c": "n."},
  {"w": "血", "m": "blood", "c": "n."},
  {"w": "涙", "m": "tears", "c": "n."},
  {"w": "汗", "m": "sweat", "c": "n."},
  {"w": "息", "m": "breath", "c": "n."},
  {"w": "力", "m": "strength, power", "c": "n."},
  {"w": "声", "m": "voice", "c": "n."},
  {"w": "健康", "m": "health", "c": "n."},
  {"w": "病気", "m": "illness", "c": "n."},
  {"w": "風邪", "m": "cold (illness)", "c": "n."},
  {"w": "熱", "m": "fever", "c": "n."},
  {"w": "怪我", "m": "injury", "c": "n."},
  {"w": "傷", "m": "wound, cut", "c": "n."},
  {"w": "薬", "m": "medicine", "c": "n."},
  {"w": "注射", "m": "injection", "c": "n."},
  {"w": "入院", "m": "hospitalization", "c": "n."},
  {"w": "退院", "m": "discharge from hospital", "c": "n."},
  {"w": "治療", "m": "medical treatment", "c": "n."},
  {"w": "手術", "m": "surgery", "c": "n."},
  {"w": "救急車", "m": "ambulance", "c": "n."},
  {"w": "天気予報", "m": "weather forecast", "c": "n."},
  {"w": "台風", "m": "typhoon", "c": "n."},
  {"w": "地震", "m": "earthquake", "c": "n."},
  {"w": "津波", "m": "tsunami", "c": "n."},
  {"w": "雲", "m": "cloud", "c": "n."},
  {"w": "風", "m": "wind", "c": "n."},
  {"w": "雷", "m": "thunder", "c": "n."},
  {"w": "虹", "m": "rainbow", "c": "n."},
  {"w": "星", "m": "star", "c": "n."},
  {"w": "月", "m": "moon", "c": "n."},
  {"w": "空", "m": "sky", "c": "n."},
  {"w": "太陽", "m": "sun", "c": "n."},
  {"w": "海岸", "m": "coast, seashore", "c": "n."},
  {"w": "湖", "m": "lake", "c": "n."},
  {"w": "森", "m": "forest", "c": "n."},
  {"w": "林", "m": "woods, grove", "c": "n."},
  {"w": "草", "m": "grass", "c": "n."},
  {"w": "葉", "m": "leaf", "c": "n."},
  {"w": "枝", "m": "branch", "c": "n."},
  {"w": "砂", "m": "sand", "c": "n."},
  {"w": "石", "m": "stone", "c": "n."},
  {"w": "泥", "m": "mud", "c": "n."},
  {"w": "虫", "m": "insect, bug", "c": "n."},
  {"w": "動物", "m": "animal", "c": "n."},
  {"w": "植物", "m": "plant", "c": "n."},
  {"w": "ペット", "m": "pet", "c": "n."},
  {"w": "毛", "m": "hair, fur", "c": "n."},
  {"w": "羽", "m": "feather", "c": "n."},
  {"w": "事故", "m": "accident", "c": "n."},
  {"w": "事件", "m": "incident", "c": "n."},
  {"w": "犯罪", "m": "crime", "c": "n."},
  {"w": "泥棒", "m": "thief, burglar", "c": "n."},
  {"w": "警察", "m": "police", "c": "n."},
  {"w": "消防署", "m": "fire station", "c": "n."},
  {"w": "市役所", "m": "city hall", "c": "n."},
  {"w": "届出", "m": "notification form", "c": "n."},
  {"w": "番号", "m": "number", "c": "n."},
  {"w": "住所", "m": "address", "c": "n."},
  {"w": "パスポート", "m": "passport", "c": "n."},
  {"w": "ビザ", "m": "visa", "c": "n."},
  {"w": "申込み", "m": "application", "c": "n."},
  {"w": "予約", "m": "reservation", "c": "n."},
  {"w": "キャンセル", "m": "cancellation", "c": "n."},
  {"w": "手続き", "m": "procedure", "c": "n."},
  {"w": "金額", "m": "amount of money", "c": "n."},
  {"w": "税金", "m": "tax", "c": "n."},
  {"w": "収入", "m": "income", "c": "n."},
  {"w": "支出", "m": "expenditure", "c": "n."},
  {"w": "貯金", "m": "savings", "c": "n."},
  {"w": "経費", "m": "expenses", "c": "n."},
  {"w": "送料", "m": "shipping fee", "c": "n."},
  {"w": "無料", "m": "free of charge", "c": "n."},
  {"w": "有料", "m": "charged, paid (fee)", "c": "n."},
  {"w": "レシート", "m": "receipt", "c": "n."},
  {"w": "通帳", "m": "bankbook", "c": "n."},
  {"w": "現金", "m": "cash", "c": "n."},
  {"w": "小銭", "m": "small change", "c": "n."},
  {"w": "カード", "m": "card", "c": "n."},
  {"w": "サイン", "m": "signature", "c": "n."},
  {"w": "印鑑", "m": "personal seal, stamp", "c": "n."},
  {"w": "封筒", "m": "envelope", "c": "n."},
  {"w": "切手", "m": "postage stamp", "c": "n."},
  {"w": "小包", "m": "small package", "c": "n."},
  {"w": "荷物", "m": "luggage, baggage", "c": "n."},
  {"w": "機械", "m": "machine", "c": "n."},
  {"w": "コンピューター", "m": "computer", "c": "n."},
  {"w": "ファイル", "m": "file", "c": "n."},
  {"w": "データ", "m": "data", "c": "n."},
  {"w": "コピー", "m": "copy", "c": "n."},
  {"w": "プリント", "m": "printout, printing", "c": "n."},
  {"w": "アルバイト", "m": "part-time job", "c": "n."},
  {"w": "サラリーマン", "m": "office worker, salaryman", "c": "n."},
  {"w": "スーツ", "m": "suit", "c": "n."},
  {"w": "ネクタイ", "m": "necktie", "c": "n."},
  {"w": "アクセサリー", "m": "accessory", "c": "n."},
  {"w": "指輪", "m": "ring", "c": "n."},
  {"w": "柄", "m": "pattern, design", "c": "n."},
  {"w": "模様", "m": "pattern, design", "c": "n."},
  {"w": "届ける", "m": "to deliver", "c": "v."},
  {"w": "届く", "m": "to arrive, to reach", "c": "v."},
  {"w": "伝える", "m": "to convey, to communicate", "c": "v."},
  {"w": "伝わる", "m": "to be conveyed, to spread", "c": "v."},
  {"w": "集める", "m": "to collect, to gather (something)", "c": "v."},
  {"w": "集まる", "m": "to gather, to assemble", "c": "v."},
  {"w": "決める", "m": "to decide", "c": "v."},
  {"w": "決まる", "m": "to be decided", "c": "v."},
  {"w": "変える", "m": "to change (something)", "c": "v."},
  {"w": "変わる", "m": "to change, to be altered", "c": "v."},
  {"w": "始める", "m": "to start, to begin (something)", "c": "v."},
  {"w": "始まる", "m": "to start, to begin", "c": "v."},
  {"w": "続ける", "m": "to continue (something)", "c": "v."},
  {"w": "続く", "m": "to continue", "c": "v."},
  {"w": "上げる", "m": "to raise, to lift", "c": "v."},
  {"w": "上がる", "m": "to rise, to go up", "c": "v."},
  {"w": "下げる", "m": "to lower", "c": "v."},
  {"w": "下がる", "m": "to go down, to fall", "c": "v."},
  {"w": "見つける", "m": "to find", "c": "v."},
  {"w": "見つかる", "m": "to be found", "c": "v."},
  {"w": "壊す", "m": "to break (something)", "c": "v."},
  {"w": "壊れる", "m": "to break, to be broken", "c": "v."},
  {"w": "汚す", "m": "to soil, to make dirty", "c": "v."},
  {"w": "汚れる", "m": "to get dirty", "c": "v."},
  {"w": "落とす", "m": "to drop (something)", "c": "v."},
  {"w": "落ちる", "m": "to fall, to drop", "c": "v."},
  {"w": "起こす", "m": "to wake (someone) up", "c": "v."},
  {"w": "起きる", "m": "to wake up, to get up", "c": "v."},
  {"w": "倒す", "m": "to knock down", "c": "v."},
  {"w": "倒れる", "m": "to fall over, to collapse", "c": "v."},
  {"w": "回す", "m": "to turn, to spin (something)", "c": "v."},
  {"w": "回る", "m": "to turn, to go around", "c": "v."},
  {"w": "動かす", "m": "to move (something)", "c": "v."},
  {"w": "動く", "m": "to move", "c": "v."},
  {"w": "止める", "m": "to stop (something)", "c": "v."},
  {"w": "止まる", "m": "to stop, to come to a halt", "c": "v."},
  {"w": "直す", "m": "to fix, to correct", "c": "v."},
  {"w": "直る", "m": "to be fixed, to be cured", "c": "v."},
  {"w": "戻す", "m": "to put back, to return (something)", "c": "v."},
  {"w": "戻る", "m": "to go back, to return", "c": "v."},
  {"w": "片付ける", "m": "to tidy up, to put away", "c": "v."},
  {"w": "片付く", "m": "to be tidied up", "c": "v."},
  {"w": "開ける", "m": "to open (something)", "c": "v."},
  {"w": "開く", "m": "to open", "c": "v."},
  {"w": "閉める", "m": "to close (something)", "c": "v."},
  {"w": "閉まる", "m": "to close, to be closed", "c": "v."},
  {"w": "付ける", "m": "to attach, to put on", "c": "v."},
  {"w": "付く", "m": "to be attached, to stick", "c": "v."},
  {"w": "並べる", "m": "to line up, to arrange", "c": "v."},
  {"w": "並ぶ", "m": "to line up, to stand in a row", "c": "v."},
  {"w": "建てる", "m": "to build", "c": "v."},
  {"w": "建つ", "m": "to be built", "c": "v."},
  {"w": "焼く", "m": "to grill, roast, bake", "c": "v."},
  {"w": "焼ける", "m": "to get scorched, burned", "c": "v."},
  {"w": "沸かす", "m": "to boil (water)", "c": "v."},
  {"w": "沸く", "m": "to boil, come to a boil", "c": "v."},
  {"w": "冷やす", "m": "to cool, chill (something)", "c": "v."},
  {"w": "冷える", "m": "to get cold, cool down", "c": "v."},
  {"w": "乾かす", "m": "to dry (something)", "c": "v."},
  {"w": "乾く", "m": "to dry, become dry", "c": "v."},
  {"w": "増やす", "m": "to increase (something)", "c": "v."},
  {"w": "増える", "m": "to increase, grow in number", "c": "v."},
  {"w": "減らす", "m": "to decrease, reduce (something)", "c": "v."},
  {"w": "減る", "m": "to decrease, decline", "c": "v."},
  {"w": "起こる", "m": "to occur, happen", "c": "v."},
  {"w": "慣れる", "m": "to get used to", "c": "v."},
  {"w": "間に合う", "m": "to be in time, make it", "c": "v."},
  {"w": "足りる", "m": "to be enough, suffice", "c": "v."},
  {"w": "似合う", "m": "to suit, match", "c": "v."},
  {"w": "似る", "m": "to resemble, look like", "c": "v."},
  {"w": "合う", "m": "to fit, match", "c": "v."},
  {"w": "通う", "m": "to commute, go regularly", "c": "v."},
  {"w": "通る", "m": "to pass through", "c": "v."},
  {"w": "通す", "m": "to let pass, let through", "c": "v."},
  {"w": "送る", "m": "to send", "c": "v."},
  {"w": "受ける", "m": "to receive, take (a test, offer)", "c": "v."},
  {"w": "受け取る", "m": "to receive, accept", "c": "v."},
  {"w": "申し込む", "m": "to apply for", "c": "v."},
  {"w": "断る", "m": "to refuse, decline", "c": "v."},
  {"w": "許す", "m": "to forgive", "c": "v."},
  {"w": "叱る", "m": "to scold", "c": "v."},
  {"w": "褒める", "m": "to praise", "c": "v."},
  {"w": "謝る", "m": "to apologize", "c": "v."},
  {"w": "祈る", "m": "to pray", "c": "v."},
  {"w": "祝う", "m": "to celebrate", "c": "v."},
  {"w": "喜ぶ", "m": "to be glad, pleased", "c": "v."},
  {"w": "悲しむ", "m": "to be sad, grieve", "c": "v."},
  {"w": "驚く", "m": "to be surprised", "c": "v."},
  {"w": "怒る", "m": "to get angry", "c": "v."},
  {"w": "笑う", "m": "to laugh", "c": "v."},
  {"w": "泣く", "m": "to cry", "c": "v."},
  {"w": "困る", "m": "to be troubled, in trouble", "c": "v."},
  {"w": "迷う", "m": "to hesitate, be lost", "c": "v."},
  {"w": "悩む", "m": "to worry, agonize", "c": "v."},
  {"w": "心配する", "m": "to worry, be anxious", "c": "v."},
  {"w": "安心する", "m": "to feel relieved", "c": "v."},
  {"w": "感動する", "m": "to be moved, touched", "c": "v."},
  {"w": "感謝する", "m": "to thank, be grateful", "c": "v."},
  {"w": "我慢する", "m": "to endure, put up with", "c": "v."},
  {"w": "注意する", "m": "to be careful, pay attention", "c": "v."},
  {"w": "遠慮する", "m": "to be reserved, hold back", "c": "v."},
  {"w": "反対する", "m": "to oppose", "c": "v."},
  {"w": "賛成する", "m": "to agree, approve", "c": "v."},
  {"w": "相談する", "m": "to consult, discuss", "c": "v."},
  {"w": "説明する", "m": "to explain", "c": "v."},
  {"w": "紹介する", "m": "to introduce", "c": "v."},
  {"w": "連絡する", "m": "to contact", "c": "v."},
  {"w": "約束する", "m": "to promise", "c": "v."},
  {"w": "挨拶する", "m": "to greet", "c": "v."},
  {"w": "準備する", "m": "to prepare", "c": "v."},
  {"w": "計画する", "m": "to plan", "c": "v."},
  {"w": "予約する", "m": "to reserve, book", "c": "v."},
  {"w": "参加する", "m": "to participate", "c": "v."},
  {"w": "出席する", "m": "to attend", "c": "v."},
  {"w": "欠席する", "m": "to be absent", "c": "v."},
  {"w": "出発する", "m": "to depart", "c": "v."},
  {"w": "到着する", "m": "to arrive", "c": "v."},
  {"w": "卒業する", "m": "to graduate", "c": "v."},
  {"w": "入学する", "m": "to enter school", "c": "v."},
  {"w": "合格する", "m": "to pass (a test)", "c": "v."},
  {"w": "就職する", "m": "to get a job, find employment", "c": "v."},
  {"w": "入院する", "m": "to be hospitalized", "c": "v."},
  {"w": "退院する", "m": "to leave the hospital", "c": "v."},
  {"w": "翻訳する", "m": "to translate", "c": "v."},
  {"w": "輸出する", "m": "to export", "c": "v."},
  {"w": "輸入する", "m": "to import", "c": "v."},
  {"w": "利用する", "m": "to use, utilize", "c": "v."},
  {"w": "確認する", "m": "to confirm, check", "c": "v."},
  {"w": "発表する", "m": "to announce, present", "c": "v."},
  {"w": "報告する", "m": "to report", "c": "v."},
  {"w": "研究する", "m": "to research, study", "c": "v."},
  {"w": "修理する", "m": "to repair", "c": "v."},
  {"w": "掃除する", "m": "to clean", "c": "v."},
  {"w": "洗濯する", "m": "to do laundry", "c": "v."},
  {"w": "料理する", "m": "to cook", "c": "v."},
  {"w": "運動する", "m": "to exercise", "c": "v."},
  {"w": "散歩する", "m": "to take a walk", "c": "v."},
  {"w": "引っ越す", "m": "to move (residence)", "c": "v."},
  {"w": "運ぶ", "m": "to carry, transport", "c": "v."},
  {"w": "拾う", "m": "to pick up", "c": "v."},
  {"w": "捨てる", "m": "to throw away", "c": "v."},
  {"w": "拭く", "m": "to wipe", "c": "v."},
  {"w": "磨く", "m": "to polish, brush", "c": "v."},
  {"w": "干す", "m": "to dry (in the sun)", "c": "v."},
  {"w": "畳む", "m": "to fold", "c": "v."},
  {"w": "包む", "m": "to wrap", "c": "v."},
  {"w": "縛る", "m": "to tie, bind", "c": "v."},
  {"w": "植える", "m": "to plant", "c": "v."},
  {"w": "育てる", "m": "to raise, bring up", "c": "v."},
  {"w": "育つ", "m": "to grow up", "c": "v."},
  {"w": "飼う", "m": "to keep, raise (an animal)", "c": "v."},
  {"w": "触る", "m": "to touch", "c": "v."},
  {"w": "踏む", "m": "to step on", "c": "v."},
  {"w": "蹴る", "m": "to kick", "c": "v."},
  {"w": "投げる", "m": "to throw", "c": "v."},
  {"w": "打つ", "m": "to hit", "c": "v."},
  {"w": "引く", "m": "to pull", "c": "v."},
  {"w": "押す", "m": "to push", "c": "v."},
  {"w": "振る", "m": "to wave, shake", "c": "v."},
  {"w": "握る", "m": "to grip, grasp", "c": "v."},
  {"w": "掴む", "m": "to grab, seize", "c": "v."},
  {"w": "抱く", "m": "to hold, embrace", "c": "v."},
  {"w": "叩く", "m": "to hit, tap", "c": "v."},
  {"w": "噛む", "m": "to bite", "c": "v."},
  {"w": "吸う", "m": "to inhale, suck, smoke", "c": "v."},
  {"w": "吹く", "m": "to blow", "c": "v."},
  {"w": "数える", "m": "to count", "c": "v."},
  {"w": "調べる", "m": "to investigate, check", "c": "v."},
  {"w": "比べる", "m": "to compare", "c": "v."},
  {"w": "試す", "m": "to try, test", "c": "v."},
  {"w": "確かめる", "m": "to confirm, to make sure", "c": "v."},
  {"w": "探す", "m": "to look for, to search", "c": "v."},
  {"w": "選ぶ", "m": "to choose, to select", "c": "v."},
  {"w": "捕まえる", "m": "to catch, to capture", "c": "v."},
  {"w": "捕まる", "m": "to be caught, to be arrested", "c": "v."},
  {"w": "逃げる", "m": "to run away, to escape", "c": "v."},
  {"w": "追いかける", "m": "to chase, to run after", "c": "v."},
  {"w": "守る", "m": "to obey (rules); to protect", "c": "v."},
  {"w": "戦う", "m": "to fight", "c": "v."},
  {"w": "競争する", "m": "to compete", "c": "v."},
  {"w": "勝つ", "m": "to win", "c": "v."},
  {"w": "負ける", "m": "to lose", "c": "v."},
  {"w": "諦める", "m": "to give up", "c": "v."},
  {"w": "頑張る", "m": "to do one's best, to try hard", "c": "v."},
  {"w": "努力する", "m": "to make an effort", "c": "v."},
  {"w": "信じる", "m": "to believe, to trust", "c": "v."},
  {"w": "疑う", "m": "to doubt, to suspect", "c": "v."},
  {"w": "思い出す", "m": "to recall, to remember", "c": "v."},
  {"w": "忘れる", "m": "to forget", "c": "v."},
  {"w": "気がつく", "m": "to notice", "c": "v."},
  {"w": "気にする", "m": "to mind, to care about", "c": "v."},
  {"w": "考える", "m": "to think, to consider", "c": "v."},
  {"w": "思う", "m": "to think, to feel", "c": "v."},
  {"w": "感じる", "m": "to feel", "c": "v."},
  {"w": "理解する", "m": "to understand", "c": "v."},
  {"w": "知る", "m": "to know", "c": "v."},
  {"w": "覚える", "m": "to memorize, to learn", "c": "v."},
  {"w": "見える", "m": "to be visible, to be able to see", "c": "v."},
  {"w": "聞こえる", "m": "to be audible, to be able to hear", "c": "v."},
  {"w": "匂う", "m": "to smell (of something)", "c": "v."},
  {"w": "構う", "m": "to mind, to care", "c": "v."},
  {"w": "尋ねる", "m": "to ask, to inquire", "c": "v."},
  {"w": "訪ねる", "m": "to visit", "c": "v."},
  {"w": "答える", "m": "to answer", "c": "v."},
  {"w": "話し合う", "m": "to discuss", "c": "v."},
  {"w": "申す", "m": "to say (humble)", "c": "v."},
  {"w": "参る", "m": "to go, to come (humble)", "c": "v."},
  {"w": "いらっしゃる", "m": "to be, to go, to come (honorific)", "c": "v."},
  {"w": "おっしゃる", "m": "to say (honorific)", "c": "v."},
  {"w": "召し上がる", "m": "to eat, to drink (honorific)", "c": "v."},
  {"w": "いただく", "m": "to receive (humble)", "c": "v."},
  {"w": "差し上げる", "m": "to give (humble)", "c": "v."},
  {"w": "ご覧になる", "m": "to see, to look at (honorific)", "c": "v."},
  {"w": "致す", "m": "to do (humble)", "c": "v."},
  {"w": "存じる", "m": "to know (humble)", "c": "v."},
  {"w": "願う", "m": "to wish, to pray for", "c": "v."},
  {"w": "頼む", "m": "to ask, to request", "c": "v."},
  {"w": "誘う", "m": "to invite", "c": "v."},
  {"w": "招待する", "m": "to invite (as a guest)", "c": "v."},
  {"w": "案内する", "m": "to guide, to show around", "c": "v."},
  {"w": "汚い", "m": "dirty", "c": "i-adj"},
  {"w": "美しい", "m": "beautiful", "c": "i-adj"},
  {"w": "激しい", "m": "intense, violent", "c": "i-adj"},
  {"w": "厳しい", "m": "strict, severe", "c": "i-adj"},
  {"w": "優しい", "m": "kind, gentle", "c": "i-adj"},
  {"w": "正しい", "m": "correct, right", "c": "i-adj"},
  {"w": "詳しい", "m": "detailed; knowledgeable (about)", "c": "i-adj"},
  {"w": "珍しい", "m": "rare, unusual", "c": "i-adj"},
  {"w": "恥ずかしい", "m": "embarrassing, shy", "c": "i-adj"},
  {"w": "悔しい", "m": "frustrating, regrettable", "c": "i-adj"},
  {"w": "寂しい", "m": "lonely", "c": "i-adj"},
  {"w": "嬉しい", "m": "happy, glad", "c": "i-adj"},
  {"w": "悲しい", "m": "sad", "c": "i-adj"},
  {"w": "苦しい", "m": "painful, hard to bear", "c": "i-adj"},
  {"w": "楽しい", "m": "fun, enjoyable", "c": "i-adj"},
  {"w": "恐ろしい", "m": "frightening, terrible", "c": "i-adj"},
  {"w": "羨ましい", "m": "envious", "c": "i-adj"},
  {"w": "素晴らしい", "m": "wonderful, splendid", "c": "i-adj"},
  {"w": "懐かしい", "m": "nostalgic", "c": "i-adj"},
  {"w": "親しい", "m": "close, intimate", "c": "i-adj"},
  {"w": "等しい", "m": "equal", "c": "i-adj"},
  {"w": "眠い", "m": "sleepy", "c": "i-adj"},
  {"w": "痒い", "m": "itchy", "c": "i-adj"},
  {"w": "痛い", "m": "painful, sore", "c": "i-adj"},
  {"w": "辛い", "m": "hard, painful, tough", "c": "i-adj"},
  {"w": "酸っぱい", "m": "sour", "c": "i-adj"},
  {"w": "苦い", "m": "bitter", "c": "i-adj"},
  {"w": "しょっぱい", "m": "salty", "c": "i-adj"},
  {"w": "柔らかい", "m": "soft", "c": "i-adj"},
  {"w": "硬い", "m": "hard, tough", "c": "i-adj"},
  {"w": "濃い", "m": "thick, strong (flavor/color)", "c": "i-adj"},
  {"w": "薄い", "m": "thin; light, weak (flavor/color)", "c": "i-adj"},
  {"w": "太い", "m": "thick, fat", "c": "i-adj"},
  {"w": "細い", "m": "thin, slender", "c": "i-adj"},
  {"w": "丸い", "m": "round", "c": "i-adj"},
  {"w": "平たい", "m": "flat", "c": "i-adj"},
  {"w": "深い", "m": "deep", "c": "i-adj"},
  {"w": "浅い", "m": "shallow", "c": "i-adj"},
  {"w": "鋭い", "m": "sharp", "c": "i-adj"},
  {"w": "鈍い", "m": "dull, slow-witted", "c": "i-adj"},
  {"w": "明るい", "m": "bright", "c": "i-adj"},
  {"w": "暗い", "m": "dark", "c": "i-adj"},
  {"w": "偉い", "m": "great, admirable", "c": "i-adj"},
  {"w": "凄い", "m": "amazing, terrible", "c": "i-adj"},
  {"w": "可愛い", "m": "cute", "c": "i-adj"},
  {"w": "格好いい", "m": "cool, good-looking", "c": "i-adj"},
  {"w": "だらしない", "m": "sloppy, slovenly", "c": "i-adj"},
  {"w": "情けない", "m": "pathetic, miserable", "c": "i-adj"},
  {"w": "仕方がない", "m": "it can't be helped", "c": "i-adj"},
  {"w": "勿体ない", "m": "wasteful", "c": "i-adj"},
  {"w": "うるさい", "m": "noisy, annoying", "c": "i-adj"},
  {"w": "煩い", "m": "annoying, noisy", "c": "i-adj"},
  {"w": "恐い", "m": "scary", "c": "i-adj"},
  {"w": "臭い", "m": "smelly", "c": "i-adj"},
  {"w": "だるい", "m": "sluggish, listless", "c": "i-adj"},
  {"w": "丁寧", "m": "polite, courteous", "c": "na-adj"},
  {"w": "親切", "m": "kind", "c": "na-adj"},
  {"w": "熱心", "m": "enthusiastic", "c": "na-adj"},
  {"w": "真剣", "m": "serious", "c": "na-adj"},
  {"w": "素直", "m": "obedient, honest", "c": "na-adj"},
  {"w": "正直", "m": "honest", "c": "na-adj"},
  {"w": "器用", "m": "skillful, dexterous", "c": "na-adj"},
  {"w": "不器用", "m": "clumsy", "c": "na-adj"},
  {"w": "乱暴", "m": "rough, violent", "c": "na-adj"},
  {"w": "意地悪", "m": "mean, spiteful", "c": "na-adj"},
  {"w": "勝手", "m": "selfish", "c": "na-adj"},
  {"w": "わがまま", "m": "selfish, willful", "c": "na-adj"},
  {"w": "贅沢", "m": "luxurious", "c": "na-adj"},
  {"w": "派手", "m": "flashy, showy", "c": "na-adj"},
  {"w": "地味", "m": "plain, sober", "c": "na-adj"},
  {"w": "素敵", "m": "nice; wonderful, cool (attractive)", "c": "na-adj"},
  {"w": "立派", "m": "splendid, admirable", "c": "na-adj"},
  {"w": "見事", "m": "magnificent, splendid", "c": "na-adj"},
  {"w": "盛ん", "m": "thriving, flourishing", "c": "na-adj"},
  {"w": "自然", "m": "natural", "c": "na-adj"},
  {"w": "複雑", "m": "complicated", "c": "na-adj"},
  {"w": "簡単", "m": "simple, easy", "c": "na-adj"},
  {"w": "適当", "m": "suitable, appropriate; sloppy, halfhearted", "c": "na-adj"},
  {"w": "正確", "m": "correct, accurate", "c": "na-adj"},
  {"w": "確か", "m": "certain, sure", "c": "na-adj"},
  {"w": "明らか", "m": "clear, obvious", "c": "na-adj"},
  {"w": "豊か", "m": "rich, abundant", "c": "na-adj"},
  {"w": "穏やか", "m": "calm, gentle", "c": "na-adj"},
  {"w": "爽やか", "m": "refreshing", "c": "na-adj"},
  {"w": "急", "m": "urgent; sudden", "c": "na-adj"},
  {"w": "特別", "m": "special", "c": "na-adj"},
  {"w": "普通", "m": "ordinary, usual", "c": "na-adj"},
  {"w": "当然", "m": "natural, obvious, of course", "c": "na-adj"},
  {"w": "十分", "m": "sufficient, enough", "c": "na-adj"},
  {"w": "不十分", "m": "insufficient", "c": "na-adj"},
  {"w": "必要", "m": "necessary", "c": "na-adj"},
  {"w": "不要", "m": "unnecessary", "c": "na-adj"},
  {"w": "大切", "m": "important, precious", "c": "na-adj"},
  {"w": "大事", "m": "important", "c": "na-adj"},
  {"w": "駄目", "m": "no good, not allowed", "c": "na-adj"},
  {"w": "不思議", "m": "mysterious, strange", "c": "na-adj"},
  {"w": "幸福", "m": "happiness, well-being", "c": "na-adj"},
  {"w": "満足", "m": "satisfied", "c": "na-adj"},
  {"w": "不満", "m": "dissatisfied", "c": "na-adj"},
  {"w": "退屈", "m": "boring", "c": "na-adj"},
  {"w": "夢中", "m": "absorbed, engrossed", "c": "na-adj"},
  {"w": "得意", "m": "good at, proud of", "c": "na-adj"},
  {"w": "苦手", "m": "poor at, weak at", "c": "na-adj"},
  {"w": "上手", "m": "skillful, good at", "c": "na-adj"},
  {"w": "下手", "m": "unskillful, poor at", "c": "na-adj"},
  {"w": "楽", "m": "comfortable, easy", "c": "na-adj"},
  {"w": "無事", "m": "safe, well", "c": "na-adj"},
  {"w": "新鮮", "m": "fresh", "c": "na-adj"},
  {"w": "有名", "m": "famous", "c": "na-adj"},
  {"w": "邪魔", "m": "in the way, a hindrance", "c": "na-adj"},
  {"w": "特に", "m": "especially, particularly", "c": "adv"},
  {"w": "必ず", "m": "surely, always", "c": "adv"},
  {"w": "絶対", "m": "absolutely", "c": "adv"},
  {"w": "決して", "m": "never (with negative)", "c": "adv"},
  {"w": "全然", "m": "(not) at all, entirely", "c": "adv"},
  {"w": "全く", "m": "entirely, completely; (not) at all", "c": "adv"},
  {"w": "少しも", "m": "not in the least", "c": "adv"},
  {"w": "ほとんど", "m": "almost, mostly", "c": "adv"},
  {"w": "かなり", "m": "quite, fairly", "c": "adv"},
  {"w": "ずいぶん", "m": "very, quite", "c": "adv"},
  {"w": "なかなか", "m": "quite, considerably / not easily, not readily", "c": "adv"},
  {"w": "すっかり", "m": "completely, entirely", "c": "adv"},
  {"w": "やっと", "m": "finally, at last", "c": "adv"},
  {"w": "とうとう", "m": "finally, at last", "c": "adv"},
  {"w": "やがて", "m": "soon, before long", "c": "adv"},
  {"w": "そろそろ", "m": "soon, before long; about time to", "c": "adv"},
  {"w": "いよいよ", "m": "finally, at last", "c": "adv"},
  {"w": "さっき", "m": "a while ago, just now", "c": "adv"},
  {"w": "たった今", "m": "just now", "c": "adv"},
  {"w": "先ほど", "m": "a short while ago (polite)", "c": "adv"},
  {"w": "突然", "m": "suddenly", "c": "adv"},
  {"w": "急に", "m": "suddenly", "c": "adv"},
  {"w": "たまに", "m": "occasionally", "c": "adv"},
  {"w": "時々", "m": "sometimes", "c": "adv"},
  {"w": "しばらく", "m": "for a while", "c": "adv"},
  {"w": "しょっちゅう", "m": "constantly, all the time", "c": "adv"},
  {"w": "いつも", "m": "always", "c": "adv"},
  {"w": "相変わらず", "m": "as usual", "c": "adv"},
  {"w": "直接", "m": "directly", "c": "adv"},
  {"w": "間接", "m": "indirectly", "c": "adv"},
  {"w": "自由に", "m": "freely", "c": "adv"},
  {"w": "自然に", "m": "naturally", "c": "adv"},
  {"w": "正式に", "m": "formally, officially", "c": "adv"},
  {"w": "実際に", "m": "actually, in practice", "c": "adv"},
  {"w": "確かに", "m": "certainly, indeed", "c": "adv"},
  {"w": "正確に", "m": "correctly, accurately", "c": "adv"},
  {"w": "丁寧に", "m": "carefully, politely", "c": "adv"},
  {"w": "大体", "m": "generally, roughly", "c": "adv"},
  {"w": "だいぶ", "m": "considerably, quite", "c": "adv"},
  {"w": "多少", "m": "somewhat, a little", "c": "adv"},
  {"w": "少々", "m": "a little, a bit", "c": "adv"},
  {"w": "次々", "m": "one after another", "c": "adv"},
  {"w": "段々", "m": "gradually", "c": "adv"},
  {"w": "益々", "m": "more and more", "c": "adv"},
  {"w": "どんどん", "m": "steadily, rapidly", "c": "adv"},
  {"w": "ぐんぐん", "m": "steadily, rapidly (growing)", "c": "adv"},
  {"w": "ゆっくり", "m": "slowly", "c": "adv"},
  {"w": "のんびり", "m": "leisurely", "c": "adv"},
  {"w": "はっきり", "m": "clearly", "c": "adv"},
  {"w": "うっかり", "m": "carelessly, inadvertently", "c": "adv"},
  {"w": "きちんと", "m": "neatly, properly", "c": "adv"},
  {"w": "ちゃんと", "m": "properly, correctly", "c": "adv"},
  {"w": "しっかり", "m": "firmly, steadily", "c": "adv"},
  {"w": "ぴったり", "m": "exactly, perfectly (fitting)", "c": "adv"},
  {"w": "そっくり", "m": "exactly alike, just like", "c": "adv"},
  {"w": "ぐっすり", "m": "soundly (sleeping)", "c": "adv"},
  {"w": "ぺらぺら", "m": "fluently", "c": "adv"},
  {"w": "ぼんやり", "m": "vacantly, absentmindedly", "c": "adv"},
  {"w": "ぎりぎり", "m": "barely, just (making it)", "c": "adv"},
  {"w": "わざわざ", "m": "specially, going out of one's way", "c": "adv"},
  {"w": "わざと", "m": "on purpose, intentionally", "c": "adv"},
  {"w": "せっかく", "m": "with much effort; a rare opportunity", "c": "adv"},
  {"w": "もし", "m": "if", "c": "adv"},
  {"w": "たとえ", "m": "even if", "c": "adv"},
  {"w": "まさか", "m": "surely not, no way", "c": "adv"},
  {"w": "一体", "m": "on earth, exactly (what/who)", "c": "adv"},
  {"w": "果たして", "m": "as expected, sure enough", "c": "adv"},
  {"w": "やはり", "m": "as expected, after all", "c": "adv"},
  {"w": "さすが", "m": "as expected of, no wonder", "c": "adv"},
  {"w": "まるで", "m": "as if, just like", "c": "adv"},
  {"w": "それに", "m": "besides, moreover", "c": "other"},
  {"w": "それで", "m": "so, therefore", "c": "other"},
  {"w": "それでは", "m": "well then", "c": "other"},
  {"w": "それなら", "m": "if that's the case", "c": "other"},
  {"w": "それとも", "m": "or, or else", "c": "other"},
  {"w": "ところが", "m": "however, but", "c": "other"},
  {"w": "ところで", "m": "by the way", "c": "other"},
  {"w": "しかし", "m": "but, however", "c": "other"},
  {"w": "けれども", "m": "but, however", "c": "other"},
  {"w": "ただし", "m": "however, provided that", "c": "other"},
  {"w": "すなわち", "m": "namely, that is to say", "c": "other"},
  {"w": "なぜなら", "m": "because, the reason is", "c": "other"},
  {"w": "したがって", "m": "therefore, accordingly", "c": "other"},
  {"w": "そのため", "m": "therefore, for that reason", "c": "other"},
  {"w": "そのうえ", "m": "moreover, besides", "c": "other"},
  {"w": "そのうち", "m": "soon, before long", "c": "other"},
  {"w": "その他", "m": "the others, and so on", "c": "other"},
  {"w": "すると", "m": "then, and so", "c": "other"},
  {"w": "すぐに", "m": "immediately, right away", "c": "other"},
  {"w": "まず", "m": "first, first of all", "c": "other"},
  {"w": "次に", "m": "next", "c": "other"},
  {"w": "最後に", "m": "finally, lastly", "c": "other"},
  {"w": "一方", "m": "on the other hand", "c": "other"},
  {"w": "反面", "m": "the other side, conversely", "c": "other"},
  {"w": "または", "m": "or", "c": "other"},
  {"w": "あるいは", "m": "or, perhaps", "c": "other"},
  {"w": "及び", "m": "and, as well as", "c": "other"},
  {"w": "なお", "m": "besides, additionally", "c": "other"},
  {"w": "ちなみに", "m": "by the way, incidentally", "c": "other"},
  {"w": "さて", "m": "well, now (then)", "c": "other"},
  {"w": "では", "m": "well then", "c": "other"},
  {"w": "じゃ", "m": "well then (casual)", "c": "other"},
  {"w": "よろしく", "m": "please be kind to me, best regards", "c": "other"},
  {"w": "お陰様で", "m": "thanks to you", "c": "other"},
  {"w": "お疲れ様", "m": "good work, thank you for your hard work", "c": "other"},
  {"w": "ご苦労様", "m": "thank you for your hard work", "c": "other"},
  {"w": "お先に", "m": "excuse me for going ahead/leaving first", "c": "other"},
  {"w": "失礼します", "m": "excuse me (for the intrusion)", "c": "other"},
  {"w": "お邪魔します", "m": "excuse me for intruding, sorry to bother you", "c": "other"},
  {"w": "ご馳走様", "m": "thank you for the meal", "c": "other"},
];
