#!/usr/bin/env node
// 多人聲(B9,2026-09-17):幫 N5/N4 單字多生 2 個聲音(8 春日部つむぎ 女・柔, 13 青山龍星 男),
// 檔案放 audio/tts-v/<speaker>/<hash>.mp3(hash 與主音檔相同 = 同一文字),清單 audio/tts-v/manifest.js → window.__TTS_V。
// 只做單字(讀音為 key),不做例句/文章(檔案量與時間成本)。用法:node scripts/tts/gen-voices.mjs [--levels n5,n4] [--speakers 8,13]
import fs from 'node:fs';
import path from 'node:path';
import { ROOT, hashText, loadOverrides, applyOverrides, audioQuery, synthesis, checkEngine, wavToMp3 } from './_lib.mjs';
const args = process.argv.slice(2);
const opt = (k, d) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : d; };
const levels = opt('--levels', 'n5,n4').split(',');
const speakers = opt('--speakers', '8,13').split(',').map(Number);
const OUT = path.join(ROOT, 'audio/tts-v');
const MAIN = JSON.parse(fs.readFileSync(path.join(ROOT, 'audio/tts/manifest.js'), 'utf8').replace(/^[^{]*/, '').replace(/;\s*$/, ''));
await checkEngine();
const overrides = loadOverrides();
// 單字文字:主清單裡有的 key 才做(讀音優先,否則表記),確保 hash 對得上前端 speak()
const texts = new Set();
for (const lv of levels) {
  const src = fs.readFileSync(path.join(ROOT, `vocab-${lv}.js`), 'utf8');
  for (const m of src.matchAll(/\{w:"([^"]+)",r:"([^"]*)"/g)) {
    const key = (m[2] && MAIN[m[2]]) ? m[2] : (MAIN[m[1]] ? m[1] : null);
    if (key) texts.add(key);
  }
}
console.log(`words: ${texts.size} × speakers ${speakers.join(',')}`);
const manifest = fs.existsSync(path.join(OUT, 'manifest.js')) ? JSON.parse(fs.readFileSync(path.join(OUT, 'manifest.js'), 'utf8').replace(/^[^{]*/, '').replace(/;\s*$/, '')) : {};
function writeManifest() {
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, 'manifest.js'), '// Generated by scripts/tts/gen-voices.mjs — do not edit by hand. {speaker:{hash:1}}\nwindow.__TTS_V = ' + JSON.stringify(manifest) + ';\n');
}
let made = 0, skipped = 0, failed = 0; const t0 = Date.now();
for (const sp of speakers) {
  fs.mkdirSync(path.join(OUT, String(sp)), { recursive: true });
  manifest[sp] = manifest[sp] || {};
  for (const text of texts) {
    const hash = MAIN[text];
    const mp3 = path.join(OUT, String(sp), `${hash}.mp3`);
    if (fs.existsSync(mp3)) { manifest[sp][hash] = 1; skipped++; continue; }
    try {
      const fed = applyOverrides(text, overrides); if (fed === '__SKIP__') { skipped++; continue; }
      const q = await audioQuery(fed, sp);
      q.speedScale = 1.0;
      const wav = await synthesis(q, sp);
      wavToMp3(wav, mp3); manifest[sp][hash] = 1; made++;
      if (made % 100 === 0) { writeManifest(); console.log(`sp${sp} made ${made} skipped ${skipped} failed ${failed} ${(Date.now() - t0) / 1000 | 0}s`); }
    } catch (e) { failed++; if (failed < 5) console.error('fail', sp, text, e.message); }
  }
  writeManifest();
}
writeManifest();
console.log(`DONE made ${made} skipped ${skipped} failed ${failed} in ${(Date.now() - t0) / 1000 | 0}s`);
