#!/usr/bin/env node
// Generate audio/tts/<hash>.mp3 for every entry in texts.json (run collect.mjs first).
// Pipeline per text: VOICEVOX audio_query -> synthesis (wav) -> ffmpeg pipe -> mp3.
// Skips entries whose mp3 already exists unless --force.
// Writes audio/tts/manifest.js for the frontend.
//
// Optional filter: --only <comma list of source prefixes>
//   e.g. --only grammar-n5,grammar-n4   (great for phased rollout / testing)

import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import {
  ROOT, OUT_DIR, MANIFEST_JS, TEXTS_JSON,
  loadOverrides, applyOverrides,
  audioQuery, synthesis, checkEngine, wavToMp3,
} from './_lib.mjs';

const args = process.argv.slice(2);
const force = args.includes('--force');
const onlyIdx = args.indexOf('--only');
const onlyFilter = onlyIdx >= 0 ? new Set(args[onlyIdx + 1].split(',')) : null;

fs.mkdirSync(OUT_DIR, { recursive: true });

const ver = await checkEngine();
console.log(`VOICEVOX ${ver} reachable, output=${path.relative(ROOT, OUT_DIR)}/`);

const texts = JSON.parse(fs.readFileSync(TEXTS_JSON, 'utf8'));
const overrides = loadOverrides();

// Filter texts to generate this run.
const work = onlyFilter
  ? texts.filter(t => t.sources.some(s => onlyFilter.has(s.split('#')[0])))
  : texts;
console.log(`Targets: ${work.length}/${texts.length}${onlyFilter ? ' (filtered: --only ' + [...onlyFilter].join(',') + ')' : ''}`);

function writeManifest() {
  const manifest = {};
  for (const t of texts) {
    const mp3 = path.join(OUT_DIR, `${t.hash}.mp3`);
    if (fs.existsSync(mp3)) manifest[t.text] = t.hash;
  }
  const js = `// Generated by scripts/tts/generate.mjs — do not edit by hand.\nwindow.__TTS = ${JSON.stringify(manifest)};\n`;
  fs.writeFileSync(MANIFEST_JS, js, 'utf8');
  return Object.keys(manifest).length;
}

// Flush manifest up-front so already-generated files are reachable from the page during this run.
writeManifest();

let made = 0, skipped = 0, failed = 0;
let consecutiveFailures = 0;
const startMs = Date.now();
for (let i = 0; i < work.length; i++) {
  const { text, hash } = work[i];
  const mp3 = path.join(OUT_DIR, `${hash}.mp3`);
  if (!force && fs.existsSync(mp3)) { skipped++; continue; }
  const fed = applyOverrides(text, overrides);
  if (fed === '__SKIP__') { skipped++; continue; }  // 跳過預生成 → fallback 瀏覽器 TTS
  try {
    const q = await audioQuery(fed);
    const wav = await synthesis(q);
    wavToMp3(wav, mp3);
    made++;
    consecutiveFailures = 0;
    if (made % 25 === 0) {
      const elapsed = (Date.now() - startMs) / 1000;
      const rate = made / elapsed;
      const remaining = (work.length - i - 1) / rate;
      const total = writeManifest();
      console.log(`  ${i + 1}/${work.length} (made=${made}, manifest=${total}, ${rate.toFixed(1)}/s, ETA ${(remaining / 60).toFixed(1)}m)`);
    }
  } catch (e) {
    failed++;
    consecutiveFailures++;
    console.error(`  FAIL "${text.slice(0, 30)}…": ${e.message}`);
    // If the engine is in a bad state, blindly retrying makes it worse. Bail out and tell
    // the user to restart VOICEVOX. They can re-run the script and we'll skip what's done.
    if (consecutiveFailures >= 5) {
      console.error(`\nABORT: ${consecutiveFailures} consecutive failures — VOICEVOX engine looks wedged.`);
      console.error(`Quit the VOICEVOX app (Cmd+Q), reopen it, then re-run this script. Already-made files will be skipped.`);
      break;
    }
  }
}

// manifest 內容變了(即使 made=0,例如新增內容源只補回對應)也要 bump sw,
// 否則客戶端 cache 的舊 manifest 查不到新句 → 靜默掉瀏覽器語音(今日故事就是這樣壞的)。
const _manifestBefore = fs.existsSync(MANIFEST_JS) ? fs.readFileSync(MANIFEST_JS, 'utf8') : '';
const finalCount = writeManifest();
const _manifestChanged = fs.readFileSync(MANIFEST_JS, 'utf8') !== _manifestBefore;

console.log(`\nDone. made=${made} skipped=${skipped} failed=${failed}`);
console.log(`Manifest entries: ${finalCount} → ${path.relative(ROOT, MANIFEST_JS)}`);

// 生過 mp3 或 manifest 有變,就 bump sw.js 的 CACHE_NAME
if (made > 0 || _manifestChanged) {
  const swPath = path.join(ROOT, 'sw.js');
  try {
    const sw = fs.readFileSync(swPath, 'utf8');
    const m = sw.match(/(CACHE_NAME\s*=\s*['"]stayjp-v)(\d+)(['"])/);
    if (m) {
      const next = parseInt(m[2], 10) + 1;
      fs.writeFileSync(swPath, sw.replace(m[0], `${m[1]}${next}${m[3]}`), 'utf8');
      console.log(`sw.js CACHE_NAME: stayjp-v${m[2]} → stayjp-v${next} (bumped to invalidate audio cache)`);
    } else {
      console.warn(`sw.js: CACHE_NAME pattern not matched — please bump manually.`);
    }
  } catch (e) {
    console.warn(`sw.js bump failed: ${e.message}`);
  }
}

// 自動跑發音稽核(VOICEVOX 這時本來就開著,順手比對揪多音字誤讀;沒開會靜默跳過)。
// 用 --no-audit 可略過。這樣「生語音」與「檢查發音」永遠綁在一起,不用人工另外跑。
if (!args.includes('--no-audit')) {
  spawnSync('node', [path.join(ROOT, 'scripts/tts/audit-pronunciation.mjs')], { stdio: 'inherit' });
}
